use rusqlite::{params, Connection};
use serde::{Deserialize, Serialize};
use tauri::AppHandle;
use crate::local_db;

const INVENTORY_SCHEMA_VERSION: &str = "003_local_inventory_movements";
#[derive(Debug, Deserialize, Serialize)]
pub struct LocalInventoryItem { pub item_id: String, pub sku: Option<String>, pub name: String, pub description: Option<String>, pub unit: Option<String>, pub current_quantity: f64, pub reorder_level: Option<f64>, pub updated_at: String }
#[derive(Debug, Deserialize)]
pub struct InventoryAdjustmentInput { pub item_id: String, pub delta: f64, pub reason: String, pub reference: Option<String> }
#[derive(Debug, Serialize)]
pub struct InventoryAdjustmentResult { pub change_id: String, pub item_id: String, pub previous_quantity: f64, pub new_quantity: f64, pub delta: f64 }
#[derive(Debug, Deserialize)]
pub struct LocalMovementWriteInput { pub snapshot_json: String, pub movement_json: String, pub change_id: String, pub item_id: String }

fn connection(app: &AppHandle) -> Result<Connection, String> { local_db::open_local_connection(app) }
fn ensure_inventory_schema(conn: &Connection) -> Result<(), String> {
    conn.execute_batch(r#"
        CREATE TABLE IF NOT EXISTS local_inventory_items (item_id TEXT PRIMARY KEY, sku TEXT, name TEXT NOT NULL, description TEXT, unit TEXT, current_quantity REAL NOT NULL DEFAULT 0, reorder_level REAL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
        CREATE UNIQUE INDEX IF NOT EXISTS idx_local_inventory_items_sku ON local_inventory_items(sku) WHERE sku IS NOT NULL;
        CREATE TABLE IF NOT EXISTS local_inventory_movements (movement_id TEXT PRIMARY KEY, item_id TEXT NOT NULL REFERENCES local_inventory_items(item_id), delta REAL NOT NULL, quantity_after REAL NOT NULL, reason TEXT NOT NULL, reference TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
        CREATE INDEX IF NOT EXISTS idx_local_inventory_movements_item ON local_inventory_movements(item_id, created_at);
        CREATE TABLE IF NOT EXISTS local_inventory_movement_records (movement_id TEXT PRIMARY KEY, item_id TEXT NOT NULL, movement_json TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
        CREATE INDEX IF NOT EXISTS idx_local_inventory_movement_records_item ON local_inventory_movement_records(item_id, created_at);
    "#).map_err(|err| format!("Unable to initialize local inventory schema: {err}"))?;
    conn.execute("INSERT OR IGNORE INTO local_schema_migrations(version) VALUES (?1)", [INVENTORY_SCHEMA_VERSION]).map_err(|err| format!("Unable to record local inventory schema version: {err}"))?; Ok(())
}
pub fn initialize(app: &AppHandle) -> Result<(), String> { let conn = connection(app)?; ensure_inventory_schema(&conn) }

#[tauri::command]
pub fn list_local_inventory(app: AppHandle) -> Result<Vec<LocalInventoryItem>, String> {
    let conn=connection(&app)?; ensure_inventory_schema(&conn)?; let mut stmt=conn.prepare("SELECT item_id,sku,name,description,unit,current_quantity,reorder_level,updated_at FROM local_inventory_items ORDER BY name COLLATE NOCASE ASC").map_err(|e|format!("Unable to prepare local inventory query: {e}"))?; let rows=stmt.query_map([],|r|Ok(LocalInventoryItem{item_id:r.get(0)?,sku:r.get(1)?,name:r.get(2)?,description:r.get(3)?,unit:r.get(4)?,current_quantity:r.get(5)?,reorder_level:r.get(6)?,updated_at:r.get(7)?})).map_err(|e|format!("Unable to read local inventory: {e}"))?; rows.collect::<Result<Vec<_>,_>>().map_err(|e|format!("Unable to decode local inventory: {e}"))
}
#[tauri::command]
pub fn upsert_local_inventory_item(app: AppHandle,item: LocalInventoryItem)->Result<(),String>{let conn=connection(&app)?;ensure_inventory_schema(&conn)?;conn.execute(r#"INSERT INTO local_inventory_items(item_id,sku,name,description,unit,current_quantity,reorder_level,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,CURRENT_TIMESTAMP) ON CONFLICT(item_id) DO UPDATE SET sku=excluded.sku,name=excluded.name,description=excluded.description,unit=excluded.unit,reorder_level=excluded.reorder_level,updated_at=CURRENT_TIMESTAMP"#,params![item.item_id,item.sku,item.name,item.description,item.unit,item.current_quantity,item.reorder_level]).map_err(|e|format!("Unable to save local inventory item: {e}"))?;Ok(())}
#[tauri::command]
pub fn adjust_local_inventory(app: AppHandle,input:InventoryAdjustmentInput)->Result<InventoryAdjustmentResult,String>{if input.delta==0.0{return Err("Inventory adjustment cannot be zero".into())}if input.reason.trim().is_empty(){return Err("Inventory adjustment reason is required".into())}let item_id=input.item_id.clone();let mut conn=connection(&app)?;ensure_inventory_schema(&conn)?;let tx=conn.transaction().map_err(|e|format!("Unable to begin local inventory transaction: {e}"))?;let previous:f64=tx.query_row("SELECT current_quantity FROM local_inventory_items WHERE item_id=?1",[&item_id],|r|r.get(0)).map_err(|e|format!("Unable to read local inventory quantity: {e}"))?;let new=previous+input.delta;if new<0.0{return Err("Inventory quantity cannot become negative".into())}let movement_id:String=tx.query_row("SELECT lower(hex(randomblob(16)))",[],|r|r.get(0)).map_err(|e|format!("Unable to create inventory movement id: {e}"))?;tx.execute("UPDATE local_inventory_items SET current_quantity=?1,updated_at=CURRENT_TIMESTAMP WHERE item_id=?2",params![new,&item_id]).map_err(|e|format!("Unable to update local inventory quantity: {e}"))?;tx.execute("INSERT INTO local_inventory_movements(movement_id,item_id,delta,quantity_after,reason,reference) VALUES (?1,?2,?3,?4,?5,?6)",params![movement_id,&item_id,input.delta,new,&input.reason,&input.reference]).map_err(|e|format!("Unable to record local inventory movement: {e}"))?;let device:String=tx.query_row("SELECT device_id FROM device_identity WHERE id=1",[],|r|r.get(0)).map_err(|e|format!("Unable to read device identity: {e}"))?;let change:String=tx.query_row("SELECT lower(hex(randomblob(16)))",[],|r|r.get(0)).map_err(|e|format!("Unable to create sync change id: {e}"))?;let payload=serde_json::json!({"movement_id":movement_id,"item_id":&item_id,"delta":input.delta,"quantity_after":new,"reason":&input.reason,"reference":&input.reference});tx.execute("INSERT INTO sync_outbox(change_id,device_id,entity_type,entity_id,operation,payload_json) VALUES (?1,?2,'inventory_movement',?3,'create',?4)",params![change,device,&item_id,payload.to_string()]).map_err(|e|format!("Unable to queue inventory movement for sync: {e}"))?;tx.commit().map_err(|e|format!("Unable to commit local inventory transaction: {e}"))?;Ok(InventoryAdjustmentResult{change_id:change,item_id,previous_quantity:previous,new_quantity:new,delta:input.delta})}

#[tauri::command]
pub fn list_local_inventory_movements(app: AppHandle,item_id:String)->Result<Option<Vec<String>>,String>{let conn=connection(&app)?;ensure_inventory_schema(&conn)?;let mut stmt=conn.prepare("SELECT movement_json FROM local_inventory_movement_records WHERE item_id=?1 ORDER BY created_at DESC").map_err(|e|format!("Unable to prepare local movement query: {e}"))?;let rows=stmt.query_map([item_id],|r|r.get(0)).map_err(|e|format!("Unable to read local movements: {e}"))?;let values=rows.collect::<Result<Vec<_>,_>>().map_err(|e|format!("Unable to decode local movements: {e}"))?;Ok(if values.is_empty(){None}else{Some(values)})}

#[tauri::command]
pub fn cache_local_inventory_movements(app: AppHandle,item_id:String,movements_json:String)->Result<(),String>{if movements_json.trim().is_empty(){return Err("Local movement list cannot be empty".into())}let values:Vec<serde_json::Value>=serde_json::from_str(&movements_json).map_err(|e|format!("Invalid movement list JSON: {e}"))?;let mut conn=connection(&app)?;ensure_inventory_schema(&conn)?;let tx=conn.transaction().map_err(|e|format!("Unable to begin movement cache transaction: {e}"))?;tx.execute("DELETE FROM local_inventory_movement_records WHERE item_id=?1",[&item_id]).map_err(|e|format!("Unable to replace movement cache: {e}"))?;for movement in values{let id=movement.get("id").and_then(|v|v.as_str()).ok_or_else(||"Movement id is required".to_string())?;tx.execute("INSERT INTO local_inventory_movement_records(movement_id,item_id,movement_json) VALUES (?1,?2,?3)",params![id,&item_id,movement.to_string()]).map_err(|e|format!("Unable to cache movement: {e}"))?;}tx.commit().map_err(|e|format!("Unable to commit movement cache: {e}"))?;Ok(())}

#[tauri::command]
pub fn save_local_inventory_movement(app: AppHandle,input:LocalMovementWriteInput)->Result<(),String>{if input.snapshot_json.trim().is_empty()||input.movement_json.trim().is_empty(){return Err("Local movement data cannot be empty".into())}serde_json::from_str::<serde_json::Value>(&input.snapshot_json).map_err(|e|format!("Invalid inventory snapshot JSON: {e}"))?;let movement:serde_json::Value=serde_json::from_str(&input.movement_json).map_err(|e|format!("Invalid movement JSON: {e}"))?;let id=movement.get("id").and_then(|v|v.as_str()).ok_or_else(||"Movement id is required".to_string())?.to_string();let mut conn=connection(&app)?;ensure_inventory_schema(&conn)?;let tx=conn.transaction().map_err(|e|format!("Unable to begin local movement transaction: {e}"))?;tx.execute("INSERT INTO sync_state(key,value) VALUES ('inventory_snapshot',?1) ON CONFLICT(key) DO UPDATE SET value=excluded.value",[&input.snapshot_json]).map_err(|e|format!("Unable to save inventory snapshot: {e}"))?;tx.execute("INSERT OR REPLACE INTO local_inventory_movement_records(movement_id,item_id,movement_json) VALUES (?1,?2,?3)",params![id,&input.item_id,&input.movement_json]).map_err(|e|format!("Unable to save local movement: {e}"))?;let device:String=tx.query_row("SELECT device_id FROM device_identity WHERE id=1",[],|r|r.get(0)).map_err(|e|format!("Unable to read device identity: {e}"))?;tx.execute("INSERT INTO sync_outbox(change_id,device_id,entity_type,entity_id,operation,payload_json) VALUES (?1,?2,'item_movement',?3,'create',?4)",params![input.change_id,device,&input.item_id,input.movement_json]).map_err(|e|format!("Unable to queue movement for sync: {e}"))?;tx.commit().map_err(|e|format!("Unable to commit local movement transaction: {e}"))?;Ok(())}
