import { apiFetch } from './http';
import { ensureItemSku } from './item-sku';
import { bulkDeleteLocalInventoryItems, bulkUpdateLocalInventoryStatus, cacheLocalInventorySnapshot, cacheLocalItemMovements, createLocalInventoryItem, createLocalItemMovement, deleteLocalInventoryItem, getLocalInventoryOrRemote, getLocalInventorySnapshot, getLocalItemMovements, updateLocalInventoryItem } from './local-inventory';
export interface Item { id:string; name:string; type:string; status:'available'|'in_use'|'damaged'|'needs_repair'|'needs_replacement'|'low_stock'|'retired'; location_id?:string; storage_location?:string|null; current_quantity:number; initial_quantity:number; unit?:string; sku?:string; category?:string; dimensions?:string; unit_cost?:number; replacement_cost?:number; condition_notes?:string; next_maintenance_date?:string|null; maintenance_interval_days?:number|null; image_resource_id?:string|null; manufacturer?:string|null; model_number?:string|null; serial_number?:string|null; asset_tag?:string|null; calibration_interval_days?:number|null; next_calibration_date?:string|null; assigned_to?:string|null; assigned_to_username?:string|null; supplier?:string|null; supplier_id?:string|null; part_number?:string|null; acquisition_method?:'unspecified'|'purchased'|'salvaged'|'donated'|'transferred'|'fabricated'|'other'; acquisition_source?:string|null; acquisition_notes?:string|null; created_at:string; updated_at:string; }
async function getItemsRemote(filters?:{type?:string;status?:string;location?:string;location_id?:string;low_stock?:boolean}):Promise<Item[]>{const p=new URLSearchParams();if(filters?.type)p.append('type',filters.type);if(filters?.status)p.append('status',filters.status);if(filters?.location)p.append('location',filters.location);if(filters?.location_id)p.append('location_id',filters.location_id);if(filters?.low_stock)p.append('low_stock','true');const r=await apiFetch(`/items?${p}`);if(!r.ok)throw new Error('Failed to fetch items');return r.json();}
export async function getItems(filters?:{type?:string;status?:string;location?:string;location_id?:string;low_stock?:boolean}):Promise<Item[]>{return getLocalInventoryOrRemote(()=>getItemsRemote(filters),filters);}
export async function getItem(id:string):Promise<Item>{const local=await getLocalInventorySnapshot();const cached=local?.find(i=>i.id===id);if(cached)return cached;const r=await apiFetch(`/items/${id}`);if(!r.ok)throw new Error('Failed to fetch item');return r.json();}
export interface ItemHistoryEntry{id:string;item_id:string;field_name:string;old_value:string|null;new_value:string|null;changed_at:string;}
export async function getItemHistory(id:string):Promise<ItemHistoryEntry[]>{const r=await apiFetch(`/items/${id}/history`);if(!r.ok)throw new Error('Failed to fetch item history');return r.json();}
export interface ItemAssignmentHistoryEntry{id:string;action:string;old_assignee_username?:string|null;new_assignee_username?:string|null;actor_username?:string|null;created_at:string;}
export async function getItemAssignmentHistory(id:string):Promise<ItemAssignmentHistoryEntry[]>{const r=await apiFetch(`/items/${id}/assignment-history`);if(!r.ok)throw new Error('Failed to fetch item assignment history');return r.json();}
export async function getItemBySku(sku:string):Promise<Item>{const local=await getLocalInventorySnapshot();if(local){const normalized=sku.trim().toLowerCase();const cached=local.find(i=>String(i.sku||'').trim().toLowerCase()===normalized);if(cached)return cached;throw new Error('Item not found');}const r=await apiFetch(`/items/by-sku/${encodeURIComponent(sku)}`);if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||'Item not found');return r.json();}
export async function createItem(item:Omit<Item,'id'|'created_at'|'updated_at'>):Promise<Item>{const normalized={...item,sku:ensureItemSku(item.sku,item.name,item.type)};const local=await createLocalInventoryItem(normalized);if(local)return local;const r=await apiFetch('/items',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(normalized)});if(!r.ok)throw new Error('Failed to create item');const created:Item=await r.json();const snapshot=await getLocalInventorySnapshot();if(snapshot)await cacheLocalInventorySnapshot([...snapshot,created]);return created;}
export async function updateItem(id:string,item:Partial<Item>):Promise<Item>{const local=await updateLocalInventoryItem(id,item);if(local)return local;const r=await apiFetch(`/items/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)});if(!r.ok)throw new Error('Failed to update item');const updated:Item=await r.json();const snapshot=await getLocalInventorySnapshot();if(snapshot)await cacheLocalInventorySnapshot(snapshot.map(e=>e.id===id?updated:e));return updated;}
export async function deleteItem(id:string):Promise<void>{if(await deleteLocalInventoryItem(id))return;const r=await apiFetch(`/items/${id}`,{method:'DELETE'});if(!r.ok)throw new Error('Failed to delete item');const snapshot=await getLocalInventorySnapshot();if(snapshot)await cacheLocalInventorySnapshot(snapshot.filter(e=>e.id!==id));}
export async function bulkUpdateItemStatus(ids:string[],status:Item['status']):Promise<{updated:number}>{const local=await bulkUpdateLocalInventoryStatus(ids,status);if(local!==null)return{updated:local};const r=await apiFetch('/items/bulk-status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids,status})});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||'Failed to update items');return r.json();}
export async function bulkDeleteItems(ids:string[]):Promise<{deleted:number}>{const local=await bulkDeleteLocalInventoryItems(ids);if(local!==null)return{deleted:local};const r=await apiFetch('/items/bulk-delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids})});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||'Failed to delete items');return r.json();}
export type MovementType='receive'|'checkout'|'return'|'consume'|'adjust'|'transfer'|'damage'|'loss'|'repair_out'|'repair_in';
export interface ItemMovement{id:string;item_id:string;movement_type:MovementType;quantity:number;quantity_before:number;quantity_after:number;from_location_id?:string|null;to_location_id?:string|null;from_location_name?:string|null;to_location_name?:string|null;from_storage_location?:string|null;to_storage_location?:string|null;project_id?:string|null;project_name?:string|null;reason?:string|null;reference?:string|null;performed_by?:string|null;performed_by_username?:string|null;created_at:string;}
export interface MaintenanceRecord{id:string;item_id:string;maintenance_type:'routine'|'repair'|'inspection'|'calibration'|'cleaning'|'other';status:'scheduled'|'in_progress'|'completed'|'cancelled';scheduled_date?:string|null;completed_date?:string|null;performed_by?:string|null;performed_by_username?:string|null;notes?:string|null;cost?:number|null;created_at:string;}
export async function getItemMovements(id:string):Promise<ItemMovement[]>{const local=await getLocalItemMovements(id);if(local!==null)return local;const r=await apiFetch(`/items/${id}/movements`);if(!r.ok)throw new Error('Failed to fetch item movements');const remote:ItemMovement[]=await r.json();await cacheLocalItemMovements(id,remote);return remote;}
export async function createItemMovement(id:string,movement:{movement_type:MovementType;quantity:number;to_storage_location?:string;to_location_id?:string;project_id?:string;reason?:string;reference?:string;}):Promise<{item:Item;movement:ItemMovement}>{const local=await createLocalItemMovement(id,movement);if(local)return local;const r=await apiFetch(`/items/${id}/movements`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(movement)});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body?.error?.message||body?.error||'Failed to record movement');const snapshot=await getLocalInventorySnapshot();if(snapshot)await cacheLocalInventorySnapshot(snapshot.map(e=>e.id===id?body.item:e));await cacheLocalItemMovements(id,[body.movement,...(await getLocalItemMovements(id)??[])]);return body;}
export async function getMaintenanceRecords(id:string):Promise<MaintenanceRecord[]>{const r=await apiFetch(`/items/${id}/maintenance`);if(!r.ok)throw new Error('Failed to fetch maintenance records');return r.json();}
export async function createMaintenanceRecord(id:string,record:Partial<MaintenanceRecord>):Promise<MaintenanceRecord>{const r=await apiFetch(`/items/${id}/maintenance`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(record)});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error?.message||b?.error||'Failed to create maintenance record');return b;}
export async function updateMaintenanceRecord(itemId:string,maintenanceId:string,record:Partial<MaintenanceRecord>):Promise<MaintenanceRecord>{const r=await apiFetch(`/items/${itemId}/maintenance/${maintenanceId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(record)});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error?.message||b?.error||'Failed to update maintenance record');return b;}
export async function deleteMaintenanceRecord(itemId:string,maintenanceId:string):Promise<void>{const r=await apiFetch(`/items/${itemId}/maintenance/${maintenanceId}`,{method:'DELETE'});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error?.message||b?.error||'Failed to delete maintenance record');}
