import {useState} from 'react';
import {solveLinear,solveQuadratic} from '../lib/equationSolvers';
type Solved={expression:string;answer:string};
const names=['x','y','z'];
const format=(n:number)=>Number(n.toPrecision(10)).toString();
export default function EquationWorkspace({onSolved}:{onSolved:(result:Solved)=>void}){
 const [mode,setMode]=useState<'2'|'3'|'quadratic'>('2');
 const [matrix,setMatrix]=useState<string[][]>([['2','1','5'],['1','-1','1'],['1','1','1']]);
 const [quad,setQuad]=useState(['1','-3','2']);
 const [solution,setSolution]=useState<{lines:string[];note:string}|null>(null);
 const [error,setError]=useState('');
 const update=(row:number,col:number,value:string)=>{setMatrix(previous=>previous.map((r,i)=>i===row?r.map((v,j)=>j===col?value:v):r));setSolution(null);setError('')};
 const solve=()=>{setError('');try{
  if(mode==='quadratic'){if(quad.some(v=>!v.trim()))throw Error('Enter all three coefficients.');const [a,b,c]=quad.map(Number);const s=solveQuadratic(a,b,c);const lines=s.roots?.map((root,i)=>`x${s.roots!.length>1?i+1:''} = ${root}`)||[s.kind==='infinite'?'All values of x satisfy the equation.':'No solution.'];const note=s.kind==='complex'?'Complex conjugate roots':s.kind==='repeated'?'Repeated real root':s.kind==='linear'?'Linear equation (a = 0)':s.kind==='infinite'?'Identity':s.kind==='inconsistent'?'Contradiction':'Two real roots';if(s.vertex)lines.push(`Vertex: (${format(s.vertex.x)}, ${format(s.vertex.y)})`);setSolution({lines,note});onSolved({expression:`${a}x² + (${b})x + (${c}) = 0`,answer:lines.join('; ')});return}
  const n=Number(mode);if(matrix.slice(0,n).some(row=>row.slice(0,n+1).some(v=>!v.trim())))throw Error('Enter all coefficients and constants.');const numbers=matrix.slice(0,n).map(row=>row.slice(0,n+1).map(Number));const s=solveLinear(numbers.map(row=>row.slice(0,n)),numbers.map(row=>row[n]));const lines=s.kind==='unique'?s.values!.map((v,i)=>`${names[i]} = ${format(v)}`):[s.kind==='infinite'?'Infinitely many solutions.':'No solution: the equations are inconsistent.'];const note=s.kind==='unique'?`Maximum residual: ${format(s.residual||0)}`:s.kind==='infinite'?'Dependent equations':'Inconsistent system';setSolution({lines,note});const expression=numbers.map(row=>row.slice(0,n).map((v,j)=>`(${v})${names[j]}`).join(' + ')+` = ${row[n]}`).join(' ; ');onSolved({expression,answer:lines.join('; ')});
 }catch(e){setSolution(null);setError(e instanceof Error?e.message:'Unable to solve equations')}};
 const changeMode=(next:typeof mode)=>{setMode(next);setSolution(null);setError('')};
 return <div className="space-y-3 rounded-xl border border-border bg-surface-raised p-3 sm:p-4">
  <div><h3 className="text-sm font-semibold">Equation solver</h3><p className="mt-1 text-xs text-text-secondary">Solve real-coefficient systems or quadratic equations offline.</p></div>
  <div className="grid grid-cols-3 gap-1.5" role="group" aria-label="Equation type">{([['2','2 unknowns'],['3','3 unknowns'],['quadratic','Quadratic']] as const).map(([id,label])=><button key={id} type="button" aria-pressed={mode===id} onClick={()=>changeMode(id)} className={'rounded-lg border px-2 py-2 text-xs font-medium '+(mode===id?'border-accent bg-accent/10 text-accent':'border-border bg-bg hover:border-accent/50')}>{label}</button>)}</div>
  {mode==='quadratic'?<div><p className="mb-2 text-xs font-mono">ax² + bx + c = 0</p><div className="grid grid-cols-3 gap-2">{quad.map((v,i)=><label key={i} className="text-xs">{['a','b','c'][i]}<input type="number" step="any" value={v} onChange={e=>{setQuad(q=>q.map((old,j)=>j===i?e.target.value:old));setSolution(null)}} className="mt-1 w-full min-w-0 rounded-md border border-border bg-bg px-2 py-2 font-mono"/></label>)}</div></div>:<div className="space-y-2"><p className="text-xs text-text-secondary">Enter each row's coefficients and the constant on the right.</p>{matrix.slice(0,Number(mode)).map((row,i)=><div key={i} className="flex min-w-0 items-center gap-1.5"><span className="w-4 shrink-0 text-xs text-text-secondary">{i+1}.</span>{row.slice(0,Number(mode)+1).map((v,j)=><div key={j} className="flex min-w-0 flex-1 items-center gap-1"><label className="min-w-0 flex-1"><span className="sr-only">Equation {i+1}, {j===Number(mode)?'constant':names[j]+' coefficient'}</span><input type="number" step="any" value={v} onChange={e=>update(i,j,e.target.value)} className="w-full min-w-0 rounded-md border border-border bg-bg px-1.5 py-2 text-center font-mono text-sm"/></label><span className="shrink-0 text-xs text-text-secondary">{j===Number(mode)?'':j===Number(mode)-1?'=':names[j]+' +'}</span></div>)}</div>)}</div>}
  {error&&<p role="alert" className="rounded-md border border-status-danger/40 p-2 text-xs text-status-danger">{error}</p>}
  <button type="button" onClick={solve} className="w-full rounded-lg bg-accent px-3 py-2.5 text-sm font-semibold text-bg focus:outline-none focus:ring-2 focus:ring-accent/50">Solve equation{mode==='quadratic'?'':'s'}</button>
  {solution&&<div aria-live="polite" className="space-y-1 rounded-lg border border-accent/30 bg-bg p-3"><div className="text-[11px] font-semibold uppercase tracking-wide text-accent">{solution.note}</div>{solution.lines.map((line,i)=><div key={i} className="break-all font-mono text-sm">{line}</div>)}<p className="pt-1 text-[11px] text-text-secondary">Use “Add question & answer” to keep this solution in the right panel.</p></div>}
 </div>;
}
