import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Clock3, Download, Pause, Play, X, Trash2, Save } from 'lucide-react';
import { getDownloadJobs, getDownloadSettings, saveDownloadSettings, updateDownloadJob, removeDownloadJob, type DownloadJob, type DownloadSettings } from '../api/mediaDownloads';
import { getLocalThumbnailUrl } from '../api/mediaDownloads';
import { useToast } from '../contexts/ToastContext';

export default function DownloadsPage(){
 const qc=useQueryClient();const {showToast}=useToast();const jobs=useQuery({queryKey:['media-downloads','queue'],queryFn:getDownloadJobs,refetchInterval:5000});const settings=useQuery({queryKey:['media-downloads','settings'],queryFn:getDownloadSettings});
 const [form,setForm]=useState<DownloadSettings|null>(null);useEffect(()=>{if(settings.data)setForm(settings.data)},[settings.data]);
 const save=useMutation({mutationFn:()=>saveDownloadSettings(form||{}),onSuccess:d=>{setForm(d);qc.invalidateQueries({queryKey:['media-downloads','settings']});showToast('Download settings saved')},onError:(e:any)=>showToast(e?.message||'Failed to save settings','error')});
 const change=useMutation({mutationFn:({id,status}:{id:string;status:DownloadJob['status']})=>updateDownloadJob(id,status),onSuccess:()=>qc.invalidateQueries({queryKey:['media-downloads','queue']}),onError:(e:any)=>showToast(e?.message||'Failed to update download','error')});
 const remove=useMutation({mutationFn:removeDownloadJob,onSuccess:()=>qc.invalidateQueries({queryKey:['media-downloads','queue']}),onError:(e:any)=>showToast(e?.message||'Failed to remove download','error')});
 const active=(jobs.data||[]).filter(j=>['queued','scheduled','downloading','paused'].includes(j.status));const history=(jobs.data||[]).filter(j=>!active.includes(j));
 const formatBytes=(n?:number)=>n==null?'—':n<1024*1024?`${(n/1024).toFixed(0)} KB`:`${(n/1024/1024).toFixed(1)} MB`;
 if(!form)return <div className="p-6 text-text-secondary">Loading downloads…</div>;
 return <div className="p-6 max-w-[1200px] mx-auto space-y-6"><div><h2 className="text-page-title font-ui font-semibold">Downloads</h2><p className="text-sm text-text-secondary mt-1">Bandwidth-aware video downloads. Queued videos wait for the scheduler instead of starting immediately.</p></div>
 <section className="bg-surface border border-border rounded-md p-4"><div className="flex items-center justify-between mb-4"><div><h3 className="font-semibold">Download schedule</h3><p className="text-xs text-text-secondary">Global defaults can be overridden by individual queued jobs.</p></div><button onClick={()=>save.mutate()} disabled={save.isPending} className="flex items-center gap-2 px-3 py-1.5 bg-accent text-bg rounded-sm text-sm disabled:opacity-50"><Save size={15}/>Save</button></div><div className="grid grid-cols-2 md:grid-cols-5 gap-3"><label className="text-xs text-text-secondary">Mode<select value={form.mode} onChange={e=>setForm({...form,mode:e.target.value as DownloadSettings['mode']})} className="mt-1 w-full bg-surface-raised border border-border rounded-sm px-2 py-2 text-sm"><option value="scheduled">Scheduled</option><option value="manual">Manual</option><option value="always">Always allowed</option></select></label><label className="text-xs text-text-secondary">Start<input type="time" value={form.window_start} onChange={e=>setForm({...form,window_start:e.target.value})} className="mt-1 w-full bg-surface-raised border border-border rounded-sm px-2 py-2 text-sm"/></label><label className="text-xs text-text-secondary">End<input type="time" value={form.window_end} onChange={e=>setForm({...form,window_end:e.target.value})} className="mt-1 w-full bg-surface-raised border border-border rounded-sm px-2 py-2 text-sm"/></label><label className="text-xs text-text-secondary">Quality<select value={form.default_quality} onChange={e=>setForm({...form,default_quality:e.target.value})} className="mt-1 w-full bg-surface-raised border border-border rounded-sm px-2 py-2 text-sm"><option>720p</option><option>1080p</option><option>480p</option><option>best</option></select></label><label className="text-xs text-text-secondary">Concurrent<input type="number" min={1} max={3} value={form.concurrent_downloads} onChange={e=>setForm({...form,concurrent_downloads:Math.max(1,Math.min(3,Number(e.target.value)||1))})} className="mt-1 w-full bg-surface-raised border border-border rounded-sm px-2 py-2 text-sm"/></label></div><label className="flex items-center gap-2 mt-3 text-sm"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>Enable download worker</label></section>
 <section><div className="flex items-center gap-2 mb-3"><Download size={17}/><h3 className="font-semibold">Queue</h3><span className="text-xs text-text-secondary">{active.length}</span></div>{active.length===0?<div className="border border-dashed border-border rounded-md p-8 text-center text-sm text-text-secondary">No downloads waiting.</div>:<div className="space-y-2">{active.map(j=><div key={j.id} className="bg-surface border border-border rounded-md p-3 flex gap-3 items-center"><div className="w-24 h-14 rounded-sm overflow-hidden bg-surface-raised shrink-0">{j.thumbnail_url?<img src={j.thumbnail_url.startsWith('/api/')?getLocalThumbnailUrl(j.resource_id):j.thumbnail_url} className="w-full h-full object-cover"/>:null}</div><div className="min-w-0 flex-1"><div className="text-sm font-medium truncate">{j.resource_name}</div><div className="text-xs text-text-secondary mt-1 flex gap-3"><span>{j.status}</span><span>{j.quality}</span>{j.scheduled_for&&<span><Clock3 size={12} className="inline mr-1"/>{new Date(j.scheduled_for).toLocaleString()}</span>}</div><div className="h-1.5 bg-bg rounded-full overflow-hidden mt-2"><div className="h-full bg-accent" style={{width:`${Number(j.progress)||0}%`}}/></div></div><div className="flex gap-1">{j.status==='paused'?<button title="Resume" onClick={()=>change.mutate({id:j.id,status:'queued'})} className="p-2 border border-border rounded-sm"><Play size={15}/></button>:j.status==='downloading'?<button title="Pause" onClick={()=>change.mutate({id:j.id,status:'paused'})} className="p-2 border border-border rounded-sm"><Pause size={15}/></button>:null}<button title="Cancel" onClick={()=>change.mutate({id:j.id,status:'cancelled'})} className="p-2 border border-border rounded-sm"><X size={15}/></button></div></div>)}</div>}</section>
 <section><h3 className="font-semibold mb-3">History</h3>{history.length===0?<div className="text-sm text-text-secondary">No completed downloads yet.</div>:<div className="space-y-2">{history.map(j=><div key={j.id} className="bg-surface border border-border rounded-md p-3 flex items-center gap-3"><div className="flex-1 min-w-0"><div className="text-sm truncate">{j.resource_name}</div><div className="text-xs text-text-secondary">{j.status} · {formatBytes(j.local_media_size_bytes||j.total_bytes)}{j.error_message?` · ${j.error_message}`:''}</div></div>{j.status==='failed'&&<button onClick={()=>change.mutate({id:j.id,status:'queued'})} className="p-2 border border-border rounded-sm" title="Retry"><Play size={15}/></button>}<button onClick={()=>remove.mutate(j.id)} className="p-2 border border-border rounded-sm" title="Remove"><Trash2 size={15}/></button></div>)}</div>}</section></div>;
}
