import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, Beaker, Boxes, MapPin, Plus, RefreshCw } from 'lucide-react';
import { createStorageContainer, getPhase4Intelligence, getPhase4Items, getStorageContainers, updateItemStorage } from '../api/phase4';
import Pagination from '../components/Pagination';
import { useToast } from '../contexts/ToastContext';

export default function LabIntelligencePage() {
  const qc = useQueryClient(); const { showToast } = useToast();
  const [itemPage, setItemPage] = useState(1), [containerPage, setContainerPage] = useState(1), [pageSize, setPageSize] = useState(6), [search, setSearch] = useState('');
  const [editing, setEditing] = useState<string | null>(null), [storage, setStorage] = useState('');
  const intelligence = useQuery({ queryKey: ['phase4-intelligence'], queryFn: getPhase4Intelligence });
  const items = useQuery({ queryKey: ['phase4-items', itemPage, pageSize, search], queryFn: () => getPhase4Items(itemPage, pageSize, search) });
  const containers = useQuery({ queryKey: ['phase4-containers', containerPage, pageSize], queryFn: () => getStorageContainers(containerPage, pageSize) });
  const saveStorage = useMutation({ mutationFn: ({ id, location }: { id: string; location: string }) => updateItemStorage(id, location, null), onSuccess: () => { qc.invalidateQueries({ queryKey: ['phase4-items'] }); setEditing(null); showToast('Storage label updated'); }, onError: (e: any) => showToast(e.message, 'error') });
  const addContainer = useMutation({ mutationFn: () => createStorageContainer({ name: `Container ${Date.now()}`, container_type: 'box', storage_location: 'Unassigned' }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['phase4-containers'] }); showToast('Storage container created'); } });
  const signalClass = (level: string) => level === 'critical' ? 'text-status-danger' : level === 'warning' ? 'text-status-warning' : 'text-accent';

  return <div className="p-6 max-w-[1500px] mx-auto space-y-6">
    <div className="flex items-center justify-between"><div><h2 className="text-page-title font-ui font-semibold">Lab Intelligence</h2><p className="text-text-secondary text-sm mt-1">Storage containers, paginated inventory and scientific stock signals.</p></div><button onClick={() => { intelligence.refetch(); items.refetch(); containers.refetch(); }} className="p-2 border border-border rounded hover:border-accent" title="Refresh"><RefreshCw size={16}/></button></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
      {[[Beaker,'Items',intelligence.data?.inventory.total_items ?? 0],[AlertTriangle,'Low stock',intelligence.data?.inventory.low_stock ?? 0],[AlertTriangle,'Maintenance due',intelligence.data?.maintenance.due ?? 0],[MapPin,'Storage labeled',`${intelligence.data?.storage.labeled ?? 0}/${intelligence.data?.storage.total ?? 0}`]].map(([Icon,label,value]: any) => <div key={label} className="bg-surface border border-border rounded-md p-4"><Icon size={18} className="text-accent mb-2"/><div className="text-2xl font-mono text-text-primary">{value}</div><div className="text-xs text-text-secondary">{label}</div></div>)}
    </div>
    {intelligence.data?.signals?.length ? <div className="bg-surface border border-border rounded-md p-4"><h3 className="font-semibold mb-3">Scientific signals</h3><div className="space-y-2">{intelligence.data.signals.map((s, i) => <div key={i} className={`text-sm flex gap-2 ${signalClass(s.level)}`}><AlertTriangle size={16}/>{s.message}</div>)}</div></div> : null}

    <section className="bg-surface border border-border rounded-md overflow-hidden"><div className="p-4 border-b border-border flex flex-wrap gap-3 items-center"><h3 className="font-semibold mr-auto">Inventory storage</h3><input value={search} onChange={e => { setSearch(e.target.value); setItemPage(1); }} placeholder="Search item, SKU, or storage label" className="px-3 py-2 bg-bg border border-border rounded text-sm w-72"/></div><div className="divide-y divide-border">{items.data?.items.map(item => <div key={item.id} className="p-4 flex flex-wrap gap-3 items-center"><div className="flex-1 min-w-[220px]"><div className="font-medium">{item.name}</div><div className="text-xs text-text-secondary">{item.type} · {item.current_quantity} {item.unit || ''}</div></div><div className="min-w-[220px] text-sm"><span className="text-text-secondary">Storage: </span><strong>{item.storage_location || 'Unlabeled'}</strong>{item.storage_container_name && <span className="text-text-secondary"> · {item.storage_container_name}</span>}</div>{editing === item.id ? <div className="flex gap-2"><input autoFocus value={storage} onChange={e => setStorage(e.target.value)} className="px-2 py-1.5 bg-bg border border-border rounded text-sm"/><button onClick={() => saveStorage.mutate({id:item.id,location:storage})} className="px-3 py-1.5 bg-accent text-bg rounded text-sm">Save</button></div> : <button onClick={() => {setEditing(item.id);setStorage(item.storage_location || '')}} className="px-3 py-1.5 border border-border rounded text-sm hover:border-accent">Edit label</button>}</div>)}</div><div className="p-4"><Pagination page={items.data?.page ?? 1} pageSize={pageSize} totalPages={items.data?.total_pages ?? 1} total={items.data?.total ?? 0} onPageChange={setItemPage} onPageSizeChange={s => {setPageSize(s);setItemPage(1);setContainerPage(1)}}/></div></section>

    <section className="bg-surface border border-border rounded-md overflow-hidden"><div className="p-4 border-b border-border flex items-center"><h3 className="font-semibold mr-auto flex gap-2 items-center"><Boxes size={18}/> Storage containers</h3><button onClick={() => addContainer.mutate()} className="flex items-center gap-2 px-3 py-2 bg-accent text-bg rounded text-sm"><Plus size={15}/> Add container</button></div><div className="divide-y divide-border">{containers.data?.containers.map(c => <div key={c.id} className="p-4 flex items-center gap-4"><div className="flex-1"><div className="font-medium">{c.name}</div><div className="text-xs text-text-secondary">{c.container_type} · {c.storage_location || 'Unlabeled'}</div></div><span className="text-sm font-mono">{c.item_count} items</span></div>)}</div><div className="p-4"><Pagination page={containers.data?.page ?? 1} pageSize={pageSize} totalPages={containers.data?.total_pages ?? 1} total={containers.data?.total ?? 0} onPageChange={setContainerPage} onPageSizeChange={s => {setPageSize(s);setContainerPage(1)}}/></div></section>
  </div>;
}
