import { useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, Box, Factory, MapPin, PackageSearch, Plus, RefreshCw, Trash2, Wrench, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { createSupplier, deleteSupplier, getOperationsOverview, getSuppliers } from '../api/operations';
import { useToast } from '../contexts/ToastContext';
import Pagination, { usePagination } from '../components/Pagination';

const input = 'w-full px-3 py-2.5 bg-bg border border-border rounded-sm text-sm focus:outline-none focus:border-accent focus:ring-1 focus:ring-accent/30';
const tabs = [['overview','Overview'],['stock','Stock'],['equipment','Equipment'],['suppliers','Suppliers'],['maintenance','Maintenance'],['requirements','Requirements'],['locations','Locations']] as const;
type Tab = typeof tabs[number][0];

function Metric({ icon: Icon, label, value, detail }: { icon: any; label: string; value: ReactNode; detail?: string }) {
  return <div className="p-4 bg-surface border border-border rounded-md min-w-0"><div className="flex items-center gap-2 text-text-secondary text-xs font-medium"><Icon size={15}/>{label}</div><div className="text-2xl font-semibold mt-2 font-mono truncate">{value}</div>{detail && <div className="text-xs text-text-secondary mt-1">{detail}</div>}</div>;
}
function Section({ title, description, action, children }: { title: string; description?: string; action?: ReactNode; children: ReactNode }) {
  return <section className="bg-surface border border-border rounded-md overflow-hidden"><div className="px-4 py-3 border-b border-border flex items-start justify-between gap-3"><div><h3 className="font-medium text-sm">{title}</h3>{description && <p className="text-xs text-text-secondary mt-0.5">{description}</p>}</div>{action}</div><div className="p-4">{children}</div></section>;
}
function ViewAll({ onClick }: { onClick: () => void }) { return <button onClick={onClick} className="text-xs text-accent hover:text-text-primary inline-flex items-center gap-1">View all <ArrowRight size={13}/></button>; }
function Empty({ children }: { children: ReactNode }) { return <div className="py-8 text-center text-sm text-text-secondary">{children}</div>; }

export default function OperationsPage() {
  const [tab, setTab] = useState<Tab>('overview');
  const [supplier, setSupplier] = useState({ name:'', contact_name:'', email:'', phone:'', website:'', notes:'' });
  const qc = useQueryClient(); const { showToast } = useToast();
  const overview = useQuery({ queryKey:['operations-overview'], queryFn:getOperationsOverview });
  const suppliers = useQuery({ queryKey:['operations-suppliers'], queryFn:getSuppliers });
  const addSupplier = useMutation({ mutationFn:() => createSupplier(supplier), onSuccess:() => { setSupplier({name:'',contact_name:'',email:'',phone:'',website:'',notes:''}); qc.invalidateQueries({queryKey:['operations-suppliers']}); showToast('Supplier created'); }, onError:(e:any)=>showToast(e.message||'Failed to create supplier','error') });
  const removeSupplier = useMutation({ mutationFn:deleteSupplier, onSuccess:()=>{qc.invalidateQueries({queryKey:['operations-suppliers']});showToast('Supplier deleted');}, onError:(e:any)=>showToast(e.message||'Failed to delete supplier','error') });
  const o = overview.data;
  const lowStock = useMemo(() => (o?.low_stock || []).slice(0, 5), [o?.low_stock]);
  const calibrationDue = useMemo(() => (o?.calibration_due || []).slice(0, 5), [o?.calibration_due]);
  const missingBom = useMemo(() => (o?.missing_bom || []).slice(0, 5), [o?.missing_bom]);
  const lowStockPage = usePagination(o?.low_stock || [], 10);
  const calibrationPage = usePagination(o?.calibration_due || [], 10);
  const missingBomPage = usePagination(o?.missing_bom || [], 10);
  const equipmentPage = usePagination(o?.equipment || [], 10);
  const maintenancePage = usePagination(o?.maintenance_due || [], 10);
  const requirementsPage = usePagination(o?.requirements || [], 10);
  const supplierPage = usePagination(suppliers.data || [], 10);

  if (overview.isLoading) return <div className="p-6 max-w-[1500px] mx-auto space-y-5"><div className="animate-pulse space-y-3"><div className="h-8 w-72 bg-surface-raised rounded"/><div className="h-4 w-96 max-w-full bg-surface-raised rounded"/><div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mt-6">{[1,2,3,4].map(i=><div key={i} className="h-24 bg-surface border border-border rounded-md"/>)}</div></div></div>;
  if (overview.error || !o) return <div className="p-6 max-w-[1500px] mx-auto"><div className="bg-surface border border-status-danger/40 rounded-md p-6 text-center"><div className="font-medium text-status-danger">Unable to load laboratory operations</div><p className="text-sm text-text-secondary mt-1">The operational summary could not be retrieved.</p><button className="mt-4 px-3 py-2 bg-accent text-bg rounded-sm text-sm" onClick={() => overview.refetch()}>Try again</button></div></div>;

  const refresh = () => { overview.refetch(); suppliers.refetch(); };
  const go = (next: Tab) => setTab(next);

  return <div className="p-4 md:p-6 max-w-[1500px] mx-auto space-y-5">
    <header className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
      <div><h1 className="text-page-title font-semibold">Laboratory Operations</h1><p className="text-sm text-text-secondary mt-1 max-w-3xl">A concise view of stock, assets, suppliers and resource readiness.</p></div>
      <button onClick={refresh} aria-label="Refresh operations" title="Refresh" className="self-start p-2 border border-border rounded-sm hover:bg-surface-raised focus:outline-none focus:ring-2 focus:ring-accent/40"><RefreshCw size={16}/></button>
    </header>

    <nav aria-label="Operations sections" className="overflow-x-auto border-b border-border -mx-4 px-4 md:mx-0 md:px-0">
      <div className="flex min-w-max">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} aria-current={tab===id?'page':undefined} className={`px-3 py-2.5 text-sm border-b-2 whitespace-nowrap focus:outline-none focus:ring-2 focus:ring-inset focus:ring-accent/40 ${tab===id?'border-accent text-text-primary font-medium':'border-transparent text-text-secondary hover:text-text-primary'}`}>{label}</button>)}</div>
    </nav>

    {tab==='overview' && <div className="space-y-4">
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric icon={Box} label="Inventory items" value={o.summary.total_items}/><Metric icon={AlertTriangle} label="Low stock" value={o.summary.low_stock} detail={o.summary.low_stock ? 'Needs attention' : 'All stock healthy'}/><Metric icon={Wrench} label="Equipment / tools" value={Number(o.summary.equipment)+Number(o.summary.tools)}/><Metric icon={PackageSearch} label="Stock value" value={Number(o.summary.stock_value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}/></div>
      <div className="grid lg:grid-cols-2 gap-4">
        <Section title="Low-stock intelligence" description={o.low_stock.length ? `${o.low_stock.length} item${o.low_stock.length===1?'':'s'} need attention` : 'Nothing currently below its threshold'} action={o.low_stock.length>5?<ViewAll onClick={()=>go('stock')}/>:undefined}>
          {lowStock.length ? <div className="space-y-2">{lowStock.map((x:any)=><div key={x.id} className="flex items-center justify-between gap-3 p-2.5 border border-border rounded-sm text-sm"><Link className="min-w-0 truncate hover:text-accent" to={`/inventory/${x.id}`}>{x.name}</Link><span className="font-mono shrink-0">{x.current_quantity} {x.unit||''}</span></div>)}</div> : <Empty>All inventory is currently above its low-stock threshold.</Empty>}
        </Section>
        <Section title="Calibration due soon" description={o.calibration_due.length ? `${o.calibration_due.length} asset${o.calibration_due.length===1?'':'s'} due within 30 days` : 'No upcoming calibration deadlines'} action={o.calibration_due.length>5?<ViewAll onClick={()=>go('maintenance')}/>:undefined}>
          {calibrationDue.length ? <div className="space-y-2">{calibrationDue.map((x:any)=><div key={x.id} className="flex items-center justify-between gap-3 p-2.5 border border-border rounded-sm text-sm"><Link className="min-w-0 truncate hover:text-accent" to={`/inventory/${x.id}`}>{x.name}</Link><span className="font-mono shrink-0">{String(x.next_calibration_date).slice(0,10)}</span></div>)}</div> : <Empty>No calibration is due within the next 30 days.</Empty>}
        </Section>
      </div>
      <Section title="Project readiness" description={o.missing_bom.length ? `${o.missing_bom.length} BOM component${o.missing_bom.length===1?'':'s'} currently missing` : 'No linked BOM shortages detected'} action={o.missing_bom.length>5?<ViewAll onClick={()=>go('requirements')}/>:undefined}>
        {missingBom.length ? <div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="text-text-secondary text-left"><th className="pb-2 pr-4">Project</th><th className="pb-2 pr-4">Component</th><th className="pb-2 pr-4">Required</th><th className="pb-2">Status</th></tr></thead><tbody>{missingBom.map((x:any)=><tr key={x.id} className="border-t border-border"><td className="py-2.5 pr-4">{x.project_name}</td><td className="pr-4">{x.name}</td><td className="pr-4">{x.required_quantity} {x.unit||''}</td><td className="text-status-danger font-medium">Missing</td></tr>)}</tbody></table></div> : <Empty>All currently linked BOM lines have sufficient preferred or alternative stock.</Empty>}
      </Section>
    </div>}

    {tab==='stock' && <div className="space-y-4"><Section title="Stock intelligence" description="Current inventory composition and exceptions"><div className="grid md:grid-cols-3 gap-3"><Metric icon={Box} label="Components" value={o.summary.components}/><Metric icon={Factory} label="Materials" value={o.summary.materials}/><Metric icon={AlertTriangle} label="Low stock" value={o.summary.low_stock}/></div></Section><Section title="Low-stock items" description="Items below their configured threshold">{lowStockPage.pagedItems.length ? <div className="space-y-2">{lowStockPage.pagedItems.map((x:any)=><div key={x.id} className="grid grid-cols-[1fr_auto_auto] gap-4 p-2.5 border border-border rounded-sm text-sm"><Link to={`/inventory/${x.id}`} className="min-w-0 truncate hover:text-accent">{x.name}</Link><span>{String(x.type||'').replace(/_/g,' ')}</span><span className="font-mono">{x.current_quantity} {x.unit||''}</span></div>)}</div> : <Empty>No low-stock items.</Empty>}<Pagination page={lowStockPage.page} pageSize={lowStockPage.pageSize} total={o.low_stock.length} totalPages={lowStockPage.totalPages} onPageChange={lowStockPage.setPage} onPageSizeChange={lowStockPage.changePageSize}/></Section></div>}

    {tab==='equipment' && <Section title="Equipment, instruments and tools" description="Operational assets and assignment status"><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left text-text-secondary"><th className="pb-2 pr-4">Asset</th><th className="pr-4">Status</th><th className="pr-4">Serial / tag</th><th className="pr-4">Assigned</th><th>Calibration</th></tr></thead><tbody>{equipmentPage.pagedItems.map((x:any)=><tr key={x.id} className="border-t border-border"><td className="py-2.5 pr-4"><Link to={`/inventory/${x.id}`} className="hover:text-accent">{x.name}</Link><div className="text-xs text-text-secondary">{[x.manufacturer,x.model_number].filter(Boolean).join(' ')}</div></td><td className="pr-4">{x.status}</td><td className="font-mono text-xs pr-4">{x.serial_number||x.asset_tag||'—'}</td><td className="pr-4">{x.assigned_to||'Unassigned'}</td><td>{x.next_calibration_date||'—'}</td></tr>)}</tbody></table></div>{!o.equipment.length&&<Empty>No equipment or tools are currently recorded.</Empty>}<Pagination page={equipmentPage.page} pageSize={equipmentPage.pageSize} total={o.equipment.length} totalPages={equipmentPage.totalPages} onPageChange={equipmentPage.setPage} onPageSizeChange={equipmentPage.changePageSize}/></Section>}

    {tab==='suppliers' && <div className="grid lg:grid-cols-[340px_1fr] gap-4"><Section title="Add supplier" description="Create a supplier record"><div className="space-y-2"><input aria-label="Supplier name" className={input} placeholder="Name" value={supplier.name} onChange={e=>setSupplier({...supplier,name:e.target.value})}/><input aria-label="Contact name" className={input} placeholder="Contact name" value={supplier.contact_name} onChange={e=>setSupplier({...supplier,contact_name:e.target.value})}/><input aria-label="Email" className={input} placeholder="Email" type="email" value={supplier.email} onChange={e=>setSupplier({...supplier,email:e.target.value})}/><input aria-label="Phone" className={input} placeholder="Phone" value={supplier.phone} onChange={e=>setSupplier({...supplier,phone:e.target.value})}/><input aria-label="Website" className={input} placeholder="Website" value={supplier.website} onChange={e=>setSupplier({...supplier,website:e.target.value})}/><textarea aria-label="Notes" className={input} placeholder="Notes" rows={3} value={supplier.notes} onChange={e=>setSupplier({...supplier,notes:e.target.value})}/><button disabled={!supplier.name.trim()||addSupplier.isPending} onClick={()=>addSupplier.mutate()} className="w-full px-3 py-2.5 bg-accent text-bg rounded-sm text-sm flex justify-center gap-2 disabled:opacity-50"><Plus size={15}/>{addSupplier.isPending?'Adding…':'Add supplier'}</button></div></Section><Section title="Suppliers" description={`${(suppliers.data||[]).length} supplier${(suppliers.data||[]).length===1?'':'s'} recorded`}>{supplierPage.pagedItems.map(s=><div key={s.id} className="p-3 mb-2 border border-border rounded-sm flex justify-between gap-3"><div className="min-w-0"><div className="font-medium truncate">{s.name}</div><div className="text-xs text-text-secondary truncate">{[s.contact_name,s.email].filter(Boolean).join(' · ')}{s.item_count != null ? ` · ${s.item_count} linked item${s.item_count===1?'':'s'}`:''}</div></div><button aria-label={`Delete ${s.name}`} onClick={()=>removeSupplier.mutate(s.id)} className="text-status-danger p-1 rounded hover:bg-status-danger/10 focus:outline-none focus:ring-2 focus:ring-status-danger/40"><Trash2 size={15}/></button></div>)}{!(suppliers.data||[]).length&&<Empty>No suppliers recorded yet.</Empty>}<Pagination page={supplierPage.page} pageSize={supplierPage.pageSize} total={(suppliers.data||[]).length} totalPages={supplierPage.totalPages} onPageChange={supplierPage.setPage} onPageSizeChange={supplierPage.changePageSize}/></Section></div>}

    {tab==='maintenance' && <div className="space-y-4"><Section title="Maintenance due / scheduled" description="Upcoming maintenance work">{maintenancePage.pagedItems.length?maintenancePage.pagedItems.map((x:any)=><div key={x.id} className="p-3 mb-2 border border-border rounded-sm grid md:grid-cols-[1fr_auto_auto] gap-3 text-sm"><Link to={`/inventory/${x.item_id}`} className="hover:text-accent">{x.name}</Link><span>{x.maintenance_type} · {x.status}</span><span className="font-mono">{x.scheduled_date||'—'}</span></div>):<Empty>No maintenance is currently due or scheduled.</Empty>}<Pagination page={maintenancePage.page} pageSize={maintenancePage.pageSize} total={o.maintenance_due.length} totalPages={maintenancePage.totalPages} onPageChange={maintenancePage.setPage} onPageSizeChange={maintenancePage.changePageSize}/></Section><Section title="Calibration" description="Assets with upcoming calibration">{calibrationPage.pagedItems.length?calibrationPage.pagedItems.map((x:any)=><div key={x.id} className="flex justify-between gap-3 p-2.5 mb-2 border border-border rounded-sm text-sm"><span className="truncate">{x.name}</span><span className="font-mono shrink-0">{String(x.next_calibration_date).slice(0,10)}</span></div>):<Empty>No upcoming calibration is recorded.</Empty>}<Pagination page={calibrationPage.page} pageSize={calibrationPage.pageSize} total={o.calibration_due.length} totalPages={calibrationPage.totalPages} onPageChange={calibrationPage.setPage} onPageSizeChange={calibrationPage.changePageSize}/></Section></div>}

    {tab==='requirements' && <Section title="Project resource requirements" description="Open requirements and available quantities">{requirementsPage.pagedItems.length?<div className="space-y-2">{requirementsPage.pagedItems.map((x:any)=><div key={x.id} className="grid md:grid-cols-[1fr_1.2fr_auto_auto] gap-3 p-3 border border-border rounded-sm text-sm"><span className="font-medium">{x.project_name}</span><span>{x.name} · {x.quantity} {x.unit||''}</span><span>{x.status}</span><span>{x.preferred_quantity??'—'} available</span></div>)}</div>:<Empty>No open resource requirements.</Empty>}<Pagination page={requirementsPage.page} pageSize={requirementsPage.pageSize} total={o.requirements.length} totalPages={requirementsPage.totalPages} onPageChange={requirementsPage.setPage} onPageSizeChange={requirementsPage.changePageSize}/></Section>}
    {tab==='locations' && <Section title="Locations" description="Manage inventory locations from the main inventory workflow"><div className="text-sm text-text-secondary mb-3">Locations remain managed from Inventory so location changes stay connected to stock records.</div><Link to="/inventory" className="inline-flex items-center gap-2 px-3 py-2 bg-accent text-bg rounded-sm text-sm"><MapPin size={15}/>Open Inventory</Link></Section>}
  </div>;
}
