import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, Beaker, CheckCircle2, Circle, ClipboardList, FileText, History, MessageSquare, Plus, Save, Trash2, Users, Wrench } from 'lucide-react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import ProjectCanvas from '../components/ProjectCanvas';
import ProjectBomPanel from '../components/ProjectBomPanel';
import { SkeletonCard } from '../components/Skeleton';
import Tabs from '../components/Tabs';
import { getItems, Item } from '../api/items';
import { getStoredUser } from '../api/auth';
import { addProjectMember, createProjectExperiment, createProjectTask, deleteProjectExperiment, deleteProjectTask, getProject, getProjectMemberCandidates, getProjectWorkspace, linkProjectItem, removeProjectMember, repeatProjectExperiment, updateProject, updateProjectExperiment, updateProjectTask, unlinkProjectItem, Project, ProjectExperiment, ProjectTask } from '../api/projects';
import { useToast } from '../contexts/ToastContext';
import { getProjectComments, createProjectComment, deleteProjectComment } from '../api/collaboration';
import { normalizeClientError } from '../api/http';

const input = 'w-full px-3 py-2 bg-bg border border-border rounded-sm text-text-primary text-sm focus:outline-none focus:border-accent';
const button = 'inline-flex items-center gap-2 px-3 py-2 rounded-sm text-sm transition-colors';

const formatProjectDate = (value:any) => {
  if (!value) return '—';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return String(value);
  return new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(d);
};

export default function ProjectDetailPage() {
  const { projectId } = useParams<{projectId:string}>(); const navigate=useNavigate(); const location=useLocation(); const qc=useQueryClient(); const {showToast}=useToast();
  const user=getStoredUser();
  const {data:project,isLoading,error}=useQuery<Project>({queryKey:['project',projectId],queryFn:()=>getProject(projectId!),enabled:!!projectId});
  const workspace=useQuery({queryKey:['project-workspace',projectId],queryFn:()=>getProjectWorkspace(projectId!),enabled:!!projectId});
  const isCanvas=location.pathname.endsWith('/canvas');
  const segment=location.pathname.split('/').filter(Boolean).pop();
  const active = isCanvas ? 'canvas' : (['tasks','experiments','inventory','knowledge','team','activity'].includes(segment||'') ? segment! : 'overview');
  if(isLoading)return <div className="p-6"><SkeletonCard/></div>;
  if(error||!project)return <div className="p-6 text-status-danger">Unable to load project.</div>;
  const budget=Number(project.budget||0), spent=Number(project.total_spent||0), remaining=project.budget!=null?budget-spent:null;
  const tabs=[
    {id:'overview',label:'Overview',path:`/projects/${projectId}`},{id:'tasks',label:'Tasks',path:`/projects/${projectId}/tasks`},
    {id:'experiments',label:'Experiments',path:`/projects/${projectId}/experiments`},{id:'inventory',label:'Inventory',path:`/projects/${projectId}/inventory`},
    {id:'knowledge',label:'Knowledge',path:`/projects/${projectId}/knowledge`},{id:'team',label:'Team',path:`/projects/${projectId}/team`},
    {id:'activity',label:'Activity',path:`/projects/${projectId}/activity`},{id:'canvas',label:'Canvas',path:`/projects/${projectId}/canvas`}
  ];
  const canEdit = workspace.data?.permissions?.can_edit !== false;
  return <div className="flex flex-col h-full">
    <div className={`project-header flex items-center gap-3 px-4 md:px-6 flex-shrink-0 ${isCanvas?'pt-3 pb-2':'pt-4 pb-3'}`}>
      <button onClick={()=>navigate('/projects')} className="p-2 hover:bg-surface-raised rounded-sm border border-transparent hover:border-border"><ArrowLeft size={18}/></button>
      <div className="min-w-0 flex-1"><div className="page-kicker">PROJECT WORKSPACE</div><div className="flex items-center gap-2 mt-1"><h2 className={`${isCanvas?'text-base':'text-xl md:text-2xl'} font-ui font-semibold truncate`}>{project.name}</h2><span className="text-[10px] font-mono uppercase tracking-wider px-2 py-1 rounded-full bg-accent/10 text-accent">{String(project.status).replace('_',' ')}</span></div>{project.description&&<p className="text-xs text-text-secondary truncate hidden md:block mt-1">{project.description}</p>}</div>
      {!isCanvas&&<div className="hidden lg:flex items-center gap-5 text-right"><div><div className="text-[10px] text-text-secondary uppercase">Tasks</div><div className="font-mono text-sm">{workspace.data?.tasks?.filter((t:any)=>t.status==='done').length||0}/{workspace.data?.tasks?.length||0}</div></div><div><div className="text-[10px] text-text-secondary uppercase">Spent</div><div className="font-mono text-sm">${spent.toFixed(2)}</div></div><div><div className="text-[10px] text-text-secondary uppercase">Remaining</div><div className="font-mono text-sm">{remaining==null?'N/A':`$${remaining.toFixed(2)}`}</div></div></div>}
    </div>
    <Tabs tabs={tabs} activePath={location.pathname}/>
    {!canEdit&&!isCanvas&&<div className="mx-4 md:mx-6 mt-2 px-3 py-2 bg-surface-raised border border-border rounded-sm text-xs text-text-secondary">This project is read-only for your current project role.</div>}
    {isCanvas?<div className="flex-1 min-h-0"><ProjectCanvas projectId={projectId!}/></div>:<div className={`flex-1 overflow-auto p-4 md:p-6 max-w-[1500px] mx-auto w-full ${canEdit?'':'[& button]:pointer-events-none [& button]:opacity-40 [& input]:pointer-events-none [& input]:opacity-60 [& textarea]:pointer-events-none [& textarea]:opacity-60 [& select]:pointer-events-none [& select]:opacity-60'}`}><WorkspaceContent active={active} project={project} workspace={workspace.data} projectId={projectId!} user={user} budget={budget} spent={spent} remaining={remaining} qc={qc} showToast={showToast} navigate={navigate} canEdit={canEdit}/></div>}
  </div>;
}

function ProjectInventoryWithBom({projectId,linked,canEdit,qc,showToast}:any){return <ProjectInventory projectId={projectId} linked={linked} canEdit={canEdit} qc={qc} showToast={showToast}/>;}

function WorkspaceContent({active,project,workspace,projectId,user,budget,spent,remaining,qc,showToast,navigate,canEdit}:any){
  const update=useMutation({mutationFn:(d:any)=>updateProject(projectId,d),onSuccess:(saved)=>{qc.setQueryData(['project',projectId],saved);qc.invalidateQueries({queryKey:['project',projectId],refetchType:'active'});qc.invalidateQueries({queryKey:['projects'],refetchType:'active'});showToast('Project updated');},onError:(e)=>showToast(normalizeClientError(e,'Failed to update project').message,'error')});
  if(active==='overview')return <Overview project={project} workspace={workspace} budget={budget} spent={spent} remaining={remaining} canEdit={canEdit} onSave={(d:any)=>update.mutateAsync(d)} />;
  if(active==='tasks')return <Tasks projectId={projectId} tasks={workspace?.tasks||[]} members={workspace?.members||[]} canEdit={canEdit} qc={qc} showToast={showToast}/>;
  if(active==='experiments')return <Experiments projectId={projectId} experiments={workspace?.experiments||[]} canEdit={canEdit} qc={qc} showToast={showToast}/>;
  if(active==='inventory')return <><ProjectInventoryWithBom projectId={projectId} linked={workspace?.items||[]} canEdit={canEdit} qc={qc} showToast={showToast}/><ProjectBomPanel projectId={projectId} canEdit={canEdit}/></>;
  if(active==='knowledge')return <ProjectKnowledge notes={workspace?.notes||[]} resources={workspace?.resources||[]} navigate={navigate}/>;
  if(active==='team')return <Team projectId={projectId} members={workspace?.members||[]} currentUser={user} canEdit={canEdit} qc={qc} showToast={showToast}/>;
  return <Activity activity={workspace?.activity||[]} projectId={projectId} canEdit={canEdit}/>;
}

function Overview({project,workspace,budget,spent,remaining,canEdit,onSave}:any){
 const [editing,setEditing]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [form,setForm]=useState({name:project.name||'',description:project.description||'',status:project.status||'active',budget:project.budget??'',priority:project.priority||'normal',start_date:project.start_date||'',due_date:project.due_date||''});
 useEffect(()=>{if(!editing)setForm({name:project.name||'',description:project.description||'',status:project.status||'active',budget:project.budget??'',priority:project.priority||'normal',start_date:project.start_date||'',due_date:project.due_date||''});},[project,editing]);
 const save=async()=>{setSaving(true);setError('');try{await onSave({...form,budget:form.budget===''?null:Number(form.budget)});setEditing(false);}catch(e:any){setError(e?.message||'Failed to save project');}finally{setSaving(false);}};
 const tasks=workspace?.tasks||[], done=tasks.filter((t:any)=>t.status==='done').length;
 return <div className="space-y-5">
  <div className="grid grid-cols-2 lg:grid-cols-5 gap-3"><Stat label="Status" value={String(project.status).replace('_',' ')} /><Stat label="Tasks" value={`${done}/${tasks.length}`} /><Stat label="Budget" value={project.budget!=null?`$${budget.toFixed(2)}`:'N/A'}/><Stat label="Spent" value={`$${spent.toFixed(2)}`}/><Stat label="Remaining" value={remaining==null?'N/A':`$${remaining.toFixed(2)}`} danger={remaining!=null&&remaining<0}/></div>
  <section className="bg-surface border border-border rounded-md p-4 md:p-6"><div className="flex items-center justify-between mb-4"><h3 className="font-semibold">Project details</h3>{canEdit&&<button className={`${button} text-text-secondary hover:text-text-primary`} onClick={()=>{setError('');setEditing(!editing)}} disabled={saving}>{editing?<><Save size={15}/>Save</>:<>Edit</>}</button>}</div>
   {error&&<div className="mb-4 rounded-sm border border-status-danger/40 bg-status-danger/10 px-3 py-2 text-sm text-status-danger">{error}</div>}
   {editing?<div className="grid md:grid-cols-2 gap-4"><label className="text-sm">Project name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className={`${input} mt-1`}/></label><label className="text-sm">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Project['status']})} className={`${input} mt-1`}><option value="active">Active</option><option value="completed">Completed</option><option value="on_hold">On Hold</option><option value="cancelled">Cancelled</option></select></label><label className="md:col-span-2 text-sm">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className={`${input} mt-1 min-h-24`}/></label><label className="text-sm">Budget<input type="number" min="0" step="0.01" value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})} className={`${input} mt-1`}/></label><label className="text-sm">Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Project['priority']})} className={`${input} mt-1`}>{['low','normal','high','critical'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm">Start date<input type="date" value={form.start_date||''} onChange={e=>setForm({...form,start_date:e.target.value})} className={`${input} mt-1`}/></label><label className="text-sm">Due date<input type="date" value={form.due_date||''} onChange={e=>setForm({...form,due_date:e.target.value})} className={`${input} mt-1`}/></label><div className="md:col-span-2"><button disabled={saving||!form.name.trim()} className={`${button} bg-accent text-bg disabled:opacity-50`} onClick={save}>{saving?<><Save size={15}/>Saving…</>:<><Save size={15}/>Save changes</>}</button></div></div>:<div className="grid md:grid-cols-4 gap-5"><div><div className="text-xs text-text-secondary">Name</div><p className="mt-1 font-medium">{project.name}</p></div><div><div className="text-xs text-text-secondary">Status</div><p className="mt-1 capitalize">{String(project.status).replace('_',' ')}</p></div><div><div className="text-xs text-text-secondary">Priority</div><p className="mt-1 capitalize">{project.priority||'normal'}</p></div><div><div className="text-xs text-text-secondary">Timeline</div><p className="mt-1">{formatProjectDate(project.start_date)} → {formatProjectDate(project.due_date)}</p></div><div className="md:col-span-4"><div className="text-xs text-text-secondary">Description</div><p className="mt-1 whitespace-pre-wrap">{project.description||'No project brief yet.'}</p></div></div>}
  </section>
  <div className="grid lg:grid-cols-2 gap-4"><section className="bg-surface border border-border rounded-md p-4"><h3 className="font-semibold mb-3 flex items-center gap-2"><ClipboardList size={17}/> Next tasks</h3>{tasks.filter((t:any)=>t.status!=='done'&&t.status!=='cancelled').slice(0,5).map((t:any)=><div key={t.id} className="py-2 border-b border-border last:border-0"><div className="font-medium text-sm">{t.title}</div><div className="text-xs text-text-secondary mt-1">{t.assignee_username||'Unassigned'} · {t.due_date||'No due date'}</div></div>)}{!tasks.length&&<p className="text-sm text-text-secondary">No tasks yet.</p>}</section><section className="bg-surface border border-border rounded-md p-4"><h3 className="font-semibold mb-3 flex items-center gap-2"><Beaker size={17}/> Experiments</h3>{(workspace?.experiments||[]).slice(0,5).map((e:any)=><div key={e.id} className="py-2 border-b border-border last:border-0"><div className="font-medium text-sm">{e.title}</div><div className="text-xs text-text-secondary mt-1 capitalize">{e.status}</div></div>)}{!workspace?.experiments?.length&&<p className="text-sm text-text-secondary">No experiments yet.</p>}</section></div>
 </div>
}
function Stat({label,value,danger=false}:any){return <div className="bg-surface border border-border rounded-md p-3"><div className="text-xs text-text-secondary">{label}</div><div className={`mt-1 text-lg font-semibold capitalize ${danger?'text-status-danger':''}`}>{value}</div></div>}

function Tasks({projectId,tasks,members,qc,showToast}:any){
 const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [priority,setPriority]=useState<'low'|'normal'|'high'|'critical'>('normal'); const [assignee,setAssignee]=useState(''); const [dueDate,setDueDate]=useState('');
 const create=useMutation({mutationFn:()=>createProjectTask(projectId,{title,description,priority,assignee_id:assignee||null,due_date:dueDate||null}),onSuccess:()=>{setTitle('');setDescription('');setAssignee('');setDueDate('');setPriority('normal');qc.invalidateQueries({queryKey:['project-workspace',projectId]});showToast('Task added');},onError:(e)=>showToast(normalizeClientError(e,'Failed to create task').message,'error')});
 const edit=useMutation({mutationFn:({id,d}:any)=>updateProjectTask(projectId,id,d),onSuccess:()=>{qc.invalidateQueries({queryKey:['project-workspace',projectId]});showToast('Task updated');},onError:(e)=>showToast(normalizeClientError(e,'Failed to update task').message,'error')});
 const del=useMutation({mutationFn:(id:string)=>deleteProjectTask(projectId,id),onSuccess:()=>{qc.invalidateQueries({queryKey:['project-workspace',projectId]});showToast('Task deleted');},onError:(e)=>showToast(normalizeClientError(e,'Failed to delete task').message,'error')});
 return <section className="space-y-4"><div className="bg-surface border border-border rounded-md p-4"><div className="grid md:grid-cols-2 lg:grid-cols-6 gap-2"><input className={input} placeholder="Task title…" value={title} onChange={e=>setTitle(e.target.value)}/><input className={input} placeholder="Description (optional)…" value={description} onChange={e=>setDescription(e.target.value)}/><select className={input} value={priority} onChange={e=>setPriority(e.target.value as 'low'|'normal'|'high'|'critical')}>{['low','normal','high','critical'].map(x=><option key={x}>{x}</option>)}</select><select className={input} value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Unassigned</option>{members.map((m:any)=><option key={m.user_id} value={m.user_id}>{m.username}</option>)}</select><input type="date" className={input} value={dueDate} onChange={e=>setDueDate(e.target.value)}/><button disabled={!title.trim()||create.isPending} onClick={()=>create.mutate()} className={`${button} bg-accent text-bg justify-center`}><Plus size={16}/>Add task</button></div></div>
 <div className="space-y-2">{tasks.map((t:ProjectTask)=><TaskCard key={t.id} task={t} members={members} onUpdate={(d:any)=>edit.mutate({id:t.id,d})} onDelete={()=>del.mutate(t.id)}/>) }{!tasks.length&&<Empty text="No tasks yet."/>}</div></section>}

function TaskCard({task,members,onUpdate,onDelete}:any){const [editing,setEditing]=useState(false);const [form,setForm]=useState({title:task.title||'',description:task.description||'',priority:task.priority||'normal',assignee_id:task.assignee_id||'',due_date:task.due_date||''});useEffect(()=>{if(!editing)setForm({title:task.title||'',description:task.description||'',priority:task.priority||'normal',assignee_id:task.assignee_id||'',due_date:task.due_date||''})},[task,editing]);const save=()=>{if(!form.title.trim())return;onUpdate({...form,assignee_id:form.assignee_id||null,due_date:form.due_date||null});setEditing(false)};return <div className="bg-surface border border-border rounded-md p-4">{editing?<div className="grid md:grid-cols-2 gap-2"><input className={input} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input className={input} value={form.description} placeholder="Description" onChange={e=>setForm({...form,description:e.target.value})}/><select className={input} value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['low','normal','high','critical'].map(x=><option key={x}>{x}</option>)}</select><select className={input} value={form.assignee_id} onChange={e=>setForm({...form,assignee_id:e.target.value})}><option value="">Unassigned</option>{members.map((m:any)=><option key={m.user_id} value={m.user_id}>{m.username}</option>)}</select><input type="date" className={input} value={form.due_date||''} onChange={e=>setForm({...form,due_date:e.target.value})}/><div className="flex gap-2"><button onClick={save} className={`${button} bg-accent text-bg`}><Save size={15}/>Save</button><button onClick={()=>setEditing(false)} className={button}>Cancel</button></div></div>:<div className="flex gap-3"><button onClick={()=>onUpdate({status:task.status==='done'?'todo':'done'})} className="mt-0.5 text-text-secondary hover:text-accent">{task.status==='done'?<CheckCircle2 size={19}/>:<Circle size={19}/>}</button><div className="min-w-0 flex-1"><div className={`font-medium ${task.status==='done'?'line-through text-text-secondary':''}`}>{task.title}</div><div className="text-xs text-text-secondary mt-1">{task.assignee_username||'Unassigned'} · {task.due_date||'No due date'} · <span className="capitalize">{task.priority}</span></div>{task.description&&<div className="text-sm text-text-secondary mt-2 whitespace-pre-wrap">{task.description}</div>}</div><select value={task.status} onChange={e=>onUpdate({status:e.target.value})} className="bg-bg border border-border rounded-sm px-2 text-xs h-8"><option>todo</option><option>in_progress</option><option>blocked</option><option>done</option><option>cancelled</option></select><button onClick={()=>setEditing(true)} className="text-xs text-accent">Edit</button><button onClick={onDelete} className="text-text-secondary hover:text-status-danger"><Trash2 size={16}/></button></div>}</div>}
function Experiments({projectId,experiments,qc,showToast}:any){const [title,setTitle]=useState('');const [hyp,setHyp]=useState('');const [repeatId,setRepeatId]=useState('');const create=useMutation({mutationFn:()=>createProjectExperiment(projectId,{title,hypothesis:hyp}),onSuccess:()=>{setTitle('');setHyp('');qc.invalidateQueries({queryKey:['project-workspace',projectId]});showToast('Experiment created')},onError:(e)=>showToast(normalizeClientError(e,'Failed to create experiment').message,'error')});const repeat=useMutation({mutationFn:()=>repeatProjectExperiment(projectId,repeatId),onSuccess:()=>{setRepeatId('');qc.invalidateQueries({queryKey:['project-workspace',projectId]});showToast('Experiment repeated')},onError:(e)=>showToast(normalizeClientError(e,'Failed to repeat experiment').message,'error')});const edit=useMutation({mutationFn:({id,...data}:any)=>updateProjectExperiment(projectId,id,data),onSuccess:()=>{qc.invalidateQueries({queryKey:['project-workspace',projectId]});showToast('Experiment updated')},onError:(e)=>showToast(normalizeClientError(e,'Failed to update experiment').message,'error')});const del=useMutation({mutationFn:(id:string)=>deleteProjectExperiment(projectId,id),onSuccess:()=>{qc.invalidateQueries({queryKey:['project-workspace',projectId]});showToast('Experiment deleted')},onError:(e)=>showToast(normalizeClientError(e,'Failed to delete experiment').message,'error')});return <section className="space-y-4"><div className="bg-surface border border-border rounded-md p-4 grid md:grid-cols-2 lg:grid-cols-5 gap-2"><input className={input} placeholder="Experiment title…" value={title} onChange={e=>setTitle(e.target.value)}/><input className={input} placeholder="Hypothesis (optional)…" value={hyp} onChange={e=>setHyp(e.target.value)}/><button disabled={!title.trim()} onClick={()=>create.mutate()} className={`${button} bg-accent text-bg justify-center`}><Plus size={16}/>New experiment</button><select value={repeatId} onChange={e=>setRepeatId(e.target.value)} className={input}><option value="">Repeat an experiment…</option>{experiments.map((e:ProjectExperiment)=><option key={e.id} value={e.id}>{e.title}</option>)}</select><button disabled={!repeatId||repeat.isPending} onClick={()=>repeat.mutate()} className={`${button} border border-border text-text-secondary justify-center`}>{repeat.isPending?'Repeating…':'Repeat selected'}</button></div><div className="grid lg:grid-cols-2 gap-4">{experiments.map((e:ProjectExperiment)=><ExperimentCard key={e.id} e={e} onStatus={(data:any)=>edit.mutate(data)} onDelete={()=>del.mutate(e.id)}/>)}</div>{!experiments.length&&<Empty text="No experiments yet."/>}</section>}
function ExperimentCard({e,onStatus,onDelete}:any){const [editing,setEditing]=useState(false);const [form,setForm]=useState({hypothesis:e.hypothesis||'',procedure:e.procedure||'',observations:e.observations||'',result:e.result||'',conclusion:e.conclusion||''});const save=()=>{onStatus({id:e.id,...form});setEditing(false)};return <article className="bg-surface border border-border rounded-md p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{e.title}</h3><p className="text-xs text-text-secondary mt-1">{e.performer_username||'No performer'} · {new Date(e.updated_at).toLocaleString()}</p></div><div className="flex items-center gap-2"><button onClick={()=>editing?save():setEditing(true)} className="text-xs text-accent">{editing?'Save':'Edit'}</button><button onClick={onDelete} className="text-text-secondary hover:text-status-danger"><Trash2 size={16}/></button></div></div><div className="mt-3 grid gap-3 text-sm">{editing?<>{(['hypothesis','procedure','observations','result','conclusion'] as const).map(k=><label key={k} className="text-xs text-text-secondary capitalize">{k}<textarea value={form[k]} onChange={x=>setForm({...form,[k]:x.target.value})} className={`${input} mt-1 min-h-20 text-text-primary`} /></label>)}</>:<><Field label="Hypothesis" value={e.hypothesis}/><Field label="Procedure" value={e.procedure}/><Field label="Observations" value={e.observations}/><Field label="Result" value={e.result}/><Field label="Conclusion" value={e.conclusion}/></>}</div><select value={e.status} onChange={x=>onStatus({id:e.id,status:x.target.value})} className={`${input} mt-3`}><option>planned</option><option>running</option><option>completed</option><option>failed</option><option>cancelled</option></select></article>}
function Field({label,value}:any){return <div><div className="text-xs text-text-secondary">{label}</div><div className="mt-1 whitespace-pre-wrap">{value||'—'}</div></div>}

function ProjectInventory({projectId,linked,qc,showToast}:any){const items=useQuery<Item[]>({queryKey:['items'],queryFn:()=>getItems()});const [itemId,setItemId]=useState('');const [qty,setQty]=useState('1');const link=useMutation({mutationFn:()=>linkProjectItem(projectId,itemId,Number(qty)),onSuccess:()=>{qc.invalidateQueries({queryKey:['project-workspace',projectId]});setItemId('');showToast('Inventory item linked')},onError:(e)=>showToast(normalizeClientError(e,'Failed to link inventory item').message,'error')});const unlink=useMutation({mutationFn:(id:string)=>unlinkProjectItem(projectId,id),onSuccess:()=>{qc.invalidateQueries({queryKey:['project-workspace',projectId]});showToast('Inventory item unlinked')},onError:(e)=>showToast(normalizeClientError(e,'Failed to unlink inventory item').message,'error')});
 return <section className="space-y-4"><div className="bg-surface border border-border rounded-md p-4 flex flex-col md:flex-row gap-2"><select value={itemId} onChange={e=>setItemId(e.target.value)} className={input}><option value="">Select inventory item…</option>{(items.data||[]).filter(i=>!linked.some((x:any)=>x.item_id===i.id)).map(i=><option key={i.id} value={i.id}>{i.name} · {i.current_quantity} {i.unit||''}</option>)}</select><input type="number" min="0" step="0.001" className="md:w-36 px-3 py-2 bg-bg border border-border rounded-sm" value={qty} onChange={e=>setQty(e.target.value)}/><button disabled={!itemId||link.isPending} onClick={()=>link.mutate()} className={`${button} bg-accent text-bg justify-center`}><Plus size={16}/>Link item</button></div><div className="grid lg:grid-cols-2 gap-3">{linked.map((i:any)=><div key={i.item_id} className="bg-surface border border-border rounded-md p-4"><div className="flex items-start justify-between"><div><div className="font-medium">{i.name}</div><div className="text-xs text-text-secondary mt-1">{i.type} · {i.location_name||'No location'}</div></div><button onClick={()=>unlink.mutate(i.item_id)} className="text-text-secondary hover:text-status-danger"><Trash2 size={16}/></button></div><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><span className="text-text-secondary">Allocated</span><div className="font-mono">{i.allocated_quantity} {i.unit||''}</div></div><div><span className="text-text-secondary">Available now</span><div className="font-mono">{i.current_quantity} {i.unit||''}</div></div></div></div>)}{!linked.length&&<Empty text="No inventory linked to this project."/>}</div></section>}

function ProjectKnowledge({notes,resources,navigate}:any){return <div className="grid lg:grid-cols-2 gap-4"><section className="bg-surface border border-border rounded-md p-4"><div className="flex justify-between mb-3"><h3 className="font-semibold flex gap-2"><FileText size={17}/> Notes</h3><button onClick={()=>navigate('/notebook')} className="text-xs text-accent">Open notebook</button></div>{notes.map((n:any)=><div key={n.id} className="py-2 border-b border-border last:border-0"><div className="font-medium text-sm">{n.title}</div><div className="text-xs text-text-secondary mt-1 line-clamp-2">{n.body||'Empty note'}</div></div>)}{!notes.length&&<Empty text="No project notes."/>}</section><section className="bg-surface border border-border rounded-md p-4"><div className="flex justify-between mb-3"><h3 className="font-semibold flex gap-2"><Wrench size={17}/> Resources</h3><button onClick={()=>navigate('/resources')} className="text-xs text-accent">Open library</button></div>{resources.map((r:any)=><div key={r.id} className="py-2 border-b border-border last:border-0"><div className="font-medium text-sm truncate">{r.name}</div><div className="text-xs text-text-secondary mt-1">{r.category||r.kind}</div></div>)}{!resources.length&&<Empty text="No project resources."/>}</section></div>}

function Team({projectId,members,currentUser,qc,showToast}:any){const [uid,setUid]=useState('');const [role,setRole]=useState('member');const candidates=useQuery({queryKey:['project-candidates',projectId],queryFn:()=>getProjectMemberCandidates(projectId),enabled:currentUser?.role==='admin'});const add=useMutation({mutationFn:async()=>{const member=await addProjectMember(projectId,uid,role);const fresh=await getProjectWorkspace(projectId);const persisted=(fresh?.members||[]).some((m:any)=>m.user_id===member.user_id);if(!persisted)throw new Error('Member was accepted by the API but was not found in the refreshed project workspace.');return {member,fresh};},onSuccess:({member,fresh})=>{qc.setQueryData(['project-workspace',projectId],fresh);qc.invalidateQueries({queryKey:['project-candidates',projectId],refetchType:'active'});setUid('');showToast(`${member.username||'Member'} added to project`);},onError:(e)=>showToast(normalizeClientError(e,'Failed to add member').message,'error')});const rem=useMutation({mutationFn:async(id:string)=>{await removeProjectMember(projectId,id);return getProjectWorkspace(projectId);},onSuccess:(fresh)=>{qc.setQueryData(['project-workspace',projectId],fresh);showToast('Project member removed')},onError:(e)=>showToast(normalizeClientError(e,'Failed to remove member').message,'error')});const available=(candidates.data||[]).filter((u:any)=>!members.some((m:any)=>m.user_id===u.id));
 return <section className="space-y-4"><div className="bg-surface border border-border rounded-md p-4"><div className="flex items-center gap-2 mb-3"><Users size={18}/><h3 className="font-semibold">Project team</h3></div>{currentUser?.role==='admin'?<div className="flex flex-col md:flex-row gap-2"><select value={uid} onChange={e=>setUid(e.target.value)} className={input}><option value="">Add active user…</option>{available.map((u:any)=><option key={u.id} value={u.id}>{u.username}</option>)}</select><select value={role} onChange={e=>setRole(e.target.value)} className="md:w-40 px-3 py-2 bg-bg border border-border rounded-sm"><option>member</option><option>lead</option><option>observer</option></select><button disabled={!uid} onClick={()=>add.mutate()} className={`${button} bg-accent text-bg justify-center`}><Plus size={16}/>Add</button></div>:<p className="text-sm text-text-secondary">Only administrators can change project membership.</p>}</div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{members.map((m:any)=><div key={m.user_id} className="bg-surface border border-border rounded-md p-4"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-full bg-accent/15 text-accent flex items-center justify-center"><Users size={16}/></div><div className="min-w-0 flex-1"><div className="font-medium truncate">{m.username}</div><div className="text-xs text-text-secondary capitalize">{m.member_role}</div></div>{currentUser?.role==='admin'&&<button onClick={()=>rem.mutate(m.user_id)} className="text-text-secondary hover:text-status-danger"><Trash2 size={15}/></button>}</div></div>)}{!members.length&&<Empty text="No project members yet."/>}</div></section>}

function Activity({activity,projectId}:any){const qc=useQueryClient();const {showToast}=useToast();const {data:comments=[]}=useQuery({queryKey:['project-comments',projectId],queryFn:()=>getProjectComments(projectId),enabled:!!projectId});const [body,setBody]=useState('');const create=useMutation({mutationFn:()=>createProjectComment(projectId,body),onSuccess:()=>{setBody('');qc.invalidateQueries({queryKey:['project-comments',projectId]});qc.invalidateQueries({queryKey:['collaboration-activity']});showToast('Comment posted')},onError:(e)=>showToast(normalizeClientError(e,'Failed to post comment').message,'error')});const del=useMutation({mutationFn:(id:string)=>deleteProjectComment(projectId,id),onSuccess:()=>{qc.invalidateQueries({queryKey:['project-comments',projectId]});showToast('Comment deleted')},onError:(e)=>showToast(normalizeClientError(e,'Failed to delete comment').message,'error')});return <div className="space-y-4"><section className="bg-surface border border-border rounded-md divide-y divide-border">{activity.map((a:any)=><div key={a.id} className="p-4 flex gap-3"><History size={17} className="text-text-secondary mt-0.5"/><div><div className="text-sm"><strong>{a.actor_username||'System'}</strong> {a.action.toLowerCase()} {a.entity_type.replace('project_','')}</div><div className="text-xs text-text-secondary mt-1">{new Date(a.created_at).toLocaleString()}</div></div></div>)}{!activity.length&&<Empty text="No project activity has been recorded yet."/>}</section><section className="bg-surface border border-border rounded-md overflow-hidden"><div className="p-4 border-b border-border"><h3 className="font-semibold flex items-center gap-2"><MessageSquare size={17}/>Discussion</h3></div><div className="p-4 space-y-3">{comments.map((c:any)=><div key={c.id} className="flex gap-3"><div className="w-8 h-8 rounded-full bg-accent/10 text-accent flex items-center justify-center flex-shrink-0"><Users size={15}/></div><div className="min-w-0 flex-1"><div className="text-sm"><strong>{c.author_username||'Unknown'}</strong><span className="text-xs text-text-secondary ml-2">{new Date(c.created_at).toLocaleString()}</span></div><div className="mt-1 text-sm whitespace-pre-wrap">{c.body}</div><button onClick={()=>del.mutate(c.id)} className="text-xs text-text-secondary hover:text-status-danger mt-1">Delete</button></div></div>)}{!comments.length&&<div className="text-sm text-text-secondary">No discussion yet.</div>}<div className="pt-3 border-t border-border flex flex-col md:flex-row gap-2"><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Write a project update or question…" className="flex-1 px-3 py-2 bg-bg border border-border rounded-sm text-sm min-h-20"/><button disabled={!body.trim()||create.isPending} onClick={()=>create.mutate()} className="px-4 py-2 bg-accent text-bg rounded-sm text-sm self-start">Post comment</button></div></div></section></div>}
function Empty({text}:{text:string}){return <div className="py-12 text-center text-sm text-text-secondary">{text}</div>}
