import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { getAllResources, uploadFile, createLink, deleteResource, Resource, getResourceDownloadUrl } from '../api/resources';
import { getItems } from '../api/items'; import { getProjects } from '../api/projects'; import { getNotes } from '../api/notes';
import { queueVideoDownload, downloadYouTubeThumbnail, getLocalThumbnailUrl, DownloadQuality } from '../api/mediaDownloads';
import { useState, useRef } from 'react';
import { Upload, Link as LinkIcon, File, Folder, Trash2, Play, CheckCircle2, Youtube } from 'lucide-react';
import ResourceViewerModal from '../components/ResourceViewerModal'; import ResourceEditorModal from '../components/ResourceEditorModal';
import { useToast } from '../contexts/ToastContext';
type ParentType='none'|'item'|'project'|'note';
const isYouTube=(url:string)=>/(?:youtube\.com|youtu\.be)/i.test(url);
function youtubeId(url:string){try{const u=new URL(url);if(u.hostname.replace(/^www\./,'').toLowerCase()==='youtu.be')return u.pathname.slice(1).split('/')[0];return u.searchParams.get('v')||u.pathname.match(/\/(?:shorts|embed|live)\/([^/?]+)/)?.[1]||'';}catch{return '';}}
function youtubePreviewThumbnail(url:string){const id=youtubeId(url);return id?`https://img.youtube.com/vi/${encodeURIComponent(id)}/hqdefault.jpg`:'';}
export default function ResourcesPage(){
 const qc=useQueryClient();const {showToast}=useToast();const [uploadProgress,setUploadProgress]=useState<number|null>(null);const [isDragOver,setIsDragOver]=useState(false);
 const [showAttachModal,setShowAttachModal]=useState<{mode:'upload'|'link';file?:File}|null>(null);const [selectedResource,setSelectedResource]=useState<Resource|null>(null);const [editingResource,setEditingResource]=useState<Resource|null>(null);
 const [linkUrl,setLinkUrl]=useState('');const [linkName,setLinkName]=useState('');const [category,setCategory]=useState('general');const [description,setDescription]=useState('');const [tagsInput,setTagsInput]=useState('');const [parentType,setParentType]=useState<ParentType>('none');const [parentId,setParentId]=useState('');const [queueVideo,setQueueVideo]=useState(true);const [quality,setQuality]=useState<DownloadQuality>('720p');
 const fileInputRef=useRef<HTMLInputElement>(null);const resourcesQuery=useQuery<Resource[]>({queryKey:['resources','all'],queryFn:getAllResources});const resources=resourcesQuery.data||[];
 const {data:items=[]}=useQuery({queryKey:['items','picker'],queryFn:()=>getItems()});const {data:projects=[]}=useQuery({queryKey:['projects','picker'],queryFn:getProjects});const {data:notes=[]}=useQuery({queryKey:['notes','picker'],queryFn:()=>getNotes()});
 const invalidate=()=>qc.invalidateQueries({queryKey:['resources','all']});const parentPayload=()=>({item_id:parentType==='item'?parentId:undefined,project_id:parentType==='project'?parentId:undefined,note_id:parentType==='note'?parentId:undefined});const metadata=()=>({category,description,tags:tagsInput.split(',').map(t=>t.trim()).filter(Boolean)});
 const resetLinkForm=()=>{setLinkUrl('');setLinkName('');setCategory('general');setDescription('');setTagsInput('');setParentType('none');setParentId('');setQueueVideo(true);setQuality('720p');};
 const uploadMutation=useMutation({mutationFn:(file:File)=>uploadFile(file,parentPayload(),undefined,setUploadProgress,metadata()),onSuccess:()=>{invalidate();setUploadProgress(null);setShowAttachModal(null);showToast('File uploaded');},onError:(e:any)=>{setUploadProgress(null);showToast(e?.message||'Upload failed','error')}});
 const linkMutation=useMutation({mutationFn:()=>createLink(linkUrl,parentPayload(),linkName||undefined,metadata()),onSuccess:async(r:Resource)=>{invalidate();setShowAttachModal(null);const youtube=isYouTube(r.url||'');try{if(youtube){await downloadYouTubeThumbnail(r.id);invalidate();}if(youtube&&queueVideo){await queueVideoDownload(r.id,quality);showToast('Resource added; thumbnail downloaded and video queued');}else showToast(youtube?'Resource added; thumbnail downloaded':'Link added');}catch(e:any){showToast(e?.message||'Resource added, but media preparation failed','error');invalidate();}resetLinkForm();},onError:(e:any)=>showToast(e?.message||'Failed to add link','error')});
 const deleteMutation=useMutation({mutationFn:deleteResource,onSuccess:()=>{invalidate();showToast('Resource deleted')},onError:(e:any)=>showToast(e?.message||'Failed to delete resource','error')});
 const attachedToLabel=(r:Resource)=>r.item_name?`Item: ${r.item_name}`:r.project_name?`Project: ${r.project_name}`:r.note_title?`Note: ${r.note_title}`:'Unattached';
 const renderThumbnail=(r:Resource)=>{const url=getResourceDownloadUrl(r.id);if(r.kind==='folder')return <div className="w-full h-full flex items-center justify-center bg-surface-raised"><Folder size={48} className="text-accent"/></div>;if(r.kind==='link'){const thumb=isYouTube(r.url||'')?getLocalThumbnailUrl(r.id):r.thumbnail_url;return thumb?<img src={thumb} alt={r.name} className="w-full h-full object-cover"/>:<div className="w-full h-full flex items-center justify-center bg-surface-raised"><LinkIcon size={48} className="text-accent"/></div>};if(r.file_type==='image')return <img src={url} alt={r.name} className="w-full h-full object-cover"/>;if(r.file_type==='video')return <div className="w-full h-full flex items-center justify-center bg-surface-raised relative"><Play size={32} className="text-accent"/><video src={url} className="absolute inset-0 w-full h-full object-cover opacity-40" preload="metadata"/></div>;return <div className="w-full h-full flex items-center justify-center bg-surface-raised"><File size={48} className={r.file_type==='pdf'?'text-status-warn':'text-text-secondary'}/></div>};
 const parentOptions:any[]=parentType==='item'?items:parentType==='project'?projects:parentType==='note'?notes:[];const confirmAttach=()=>{if(parentType!=='none'&&!parentId)return;if(showAttachModal?.mode==='upload'&&showAttachModal.file)uploadMutation.mutate(showAttachModal.file);else if(showAttachModal?.mode==='link'&&linkUrl.trim())linkMutation.mutate()};const closeAttach=()=>{setShowAttachModal(null);if(showAttachModal?.mode==='link')resetLinkForm();};const handleSaved=(updated:Resource)=>{setEditingResource(null);invalidate();setSelectedResource(updated)};const youtube=isYouTube(linkUrl);const previewThumb=youtubePreviewThumbnail(linkUrl);
 return <div className="p-6 max-w-[1400px] mx-auto"><div className="flex items-center justify-between mb-6"><h2 className="text-page-title font-ui font-semibold">Resources</h2><div className="flex gap-2"><button onClick={()=>fileInputRef.current?.click()} className="flex items-center gap-2 px-3 py-1.5 bg-surface-raised border border-border rounded-sm hover:border-accent text-sm"><Upload size={16}/>Upload</button><button onClick={()=>setShowAttachModal({mode:'link'})} className="flex items-center gap-2 px-3 py-1.5 bg-accent text-bg rounded-sm hover:opacity-90 text-sm"><LinkIcon size={16}/>Add Link</button></div></div>
 <input ref={fileInputRef} type="file" onChange={e=>{const f=e.target.files?.[0];if(f)setShowAttachModal({mode:'upload',file:f})}} className="hidden"/><div onDragOver={e=>{e.preventDefault();setIsDragOver(true)}} onDragLeave={e=>{e.preventDefault();setIsDragOver(false)}} onDrop={e=>{e.preventDefault();setIsDragOver(false);const f=e.dataTransfer.files[0];if(f)setShowAttachModal({mode:'upload',file:f})}} className={`border-2 border-dashed rounded-md p-8 mb-6 text-center ${isDragOver?'border-accent bg-accent/5':'border-border'}`}><Upload size={32} className="mx-auto mb-2 text-text-secondary"/><p className="text-text-secondary text-sm">Drag and drop files here, or use the upload button</p></div>
 {resourcesQuery.isLoading?<div className="py-8 text-center text-text-secondary">Loading…</div>:resourcesQuery.error?<div className="py-8 text-center text-status-danger">Error loading resources</div>:resources.length===0?<div className="py-8 text-center text-text-secondary">No resources yet across the lab.</div>:<div className="grid grid-cols-[repeat(auto-fill,minmax(220px,1fr))] gap-4">{resources.map(r=><div key={r.id} onClick={()=>setSelectedResource(r)} className="group relative bg-surface border border-border rounded-md overflow-hidden hover:border-accent cursor-pointer"><div className="aspect-video">{renderThumbnail(r)}</div><div className="p-3"><div className="text-sm truncate" title={r.name}>{r.name}</div><div className="text-xs text-text-secondary mt-1 truncate">{attachedToLabel(r)}</div></div><button onClick={e=>{e.stopPropagation();deleteMutation.mutate(r.id)}} className="absolute top-2 right-2 p-1.5 bg-surface-raised border border-border rounded-sm opacity-0 group-hover:opacity-100 hover:bg-status-danger hover:border-status-danger"><Trash2 size={14}/></button></div>)}</div>}
 {showAttachModal&&<div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4" onMouseDown={e=>{if(e.target===e.currentTarget)closeAttach()}}><div className="w-full max-w-5xl max-h-[92vh] bg-surface border border-border rounded-lg shadow-2xl overflow-hidden flex flex-col">
 <div className="px-6 py-4 border-b border-border flex items-start justify-between shrink-0"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-md bg-accent/15 flex items-center justify-center text-accent">{showAttachModal.mode==='link'?<LinkIcon size={20}/>:<Upload size={20}/>}</div><div><h3 className="text-lg font-ui font-semibold">{showAttachModal.mode==='link'?(youtube?'Add YouTube Resource':'Add Link Resource'):'Upload Resource'}</h3><p className="text-xs text-text-secondary mt-0.5">{showAttachModal.mode==='link'?'Add a web link to your laboratory resources.':`Attach “${showAttachModal.file?.name||'file'}” to a lab context.`}</p></div></div><button onClick={closeAttach} className="p-2 rounded-sm hover:bg-surface-raised text-text-secondary text-xl" aria-label="Close">×</button></div>
 <div className="flex-1 min-h-0 overflow-y-auto">{showAttachModal.mode==='link'?<div className="grid grid-cols-1 lg:grid-cols-[1.05fr_.95fr]">
 <div className="p-6 space-y-5 lg:border-r border-border"><div><label className="text-xs font-medium text-text-secondary">Link <span className="text-status-danger">*</span></label><div className="relative mt-1"><LinkIcon size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-text-secondary"/><input autoFocus value={linkUrl} onChange={e=>setLinkUrl(e.target.value)} placeholder="https://…" className="w-full bg-surface-raised border border-border rounded-md pl-10 pr-10 py-3 text-sm focus:outline-none focus:border-accent"/>{youtube&&<CheckCircle2 size={17} className="absolute right-3 top-1/2 -translate-y-1/2 text-status-success"/>}</div>{youtube&&<div className="flex items-center gap-2 mt-2 text-xs text-status-success"><CheckCircle2 size={14}/>Valid YouTube URL</div>}</div>
 {youtube&&<div className="rounded-md border border-border bg-surface-raised p-4 space-y-4"><div className="flex items-center gap-2 text-sm font-medium"><Youtube size={18} className="text-accent"/>Download options</div><label className="flex items-start gap-3 cursor-pointer"><input type="checkbox" checked={queueVideo} onChange={e=>setQueueVideo(e.target.checked)} className="mt-0.5"/><span><span className="block text-sm">Download video <span className="text-xs text-accent">(adds to queue)</span></span><span className="block text-xs text-text-secondary mt-0.5">The video never downloads from this form. It is handled by Downloads.</span></span></label><div className="flex items-start gap-3"><CheckCircle2 size={18} className="mt-0.5 text-status-success shrink-0"/><span><span className="block text-sm">Download thumbnail <span className="text-xs text-text-secondary">(always enabled)</span></span><span className="block text-xs text-text-secondary mt-0.5">Downloaded immediately and stored with this resource.</span></span></div>{queueVideo&&<label className="text-xs text-text-secondary block">Initial quality<select value={quality} onChange={e=>setQuality(e.target.value as DownloadQuality)} className="mt-1 w-full px-3 py-2.5 bg-surface border border-border rounded-md text-sm"><option>720p</option><option>1080p</option><option>480p</option><option>best</option></select></label>}</div>}
 <label className="text-xs text-text-secondary block">Knowledge category<select value={category} onChange={e=>setCategory(e.target.value)} className="mt-1 w-full bg-surface-raised border border-border rounded-md text-sm">{['general','datasheet','manual','schematic','research','tutorial','reference','specification','image','cad','report','video','other'].map(c=><option key={c}>{c}</option>)}</select></label><label className="text-xs text-text-secondary block">Title <span className="text-text-tertiary">(optional)</span><input value={linkName} onChange={e=>setLinkName(e.target.value)} placeholder="Add a title for this resource…" maxLength={200} className="mt-1 w-full bg-surface-raised border border-border rounded-md px-3 py-2.5 text-sm"/><span className="block text-right mt-1 text-[11px]">{linkName.length}/200</span></label><label className="text-xs text-text-secondary block">Description <span className="text-text-tertiary">(optional)</span><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4} maxLength={500} placeholder="Add a description for this resource…" className="mt-1 w-full bg-surface-raised border border-border rounded-md px-3 py-2.5 text-sm resize-y"/><span className="block text-right mt-1 text-[11px]">{description.length}/500</span></label><label className="text-xs text-text-secondary block">Tags <span className="text-text-tertiary">(optional)</span><input value={tagsInput} onChange={e=>setTagsInput(e.target.value)} placeholder="esp32, power, reference" className="mt-1 w-full bg-surface-raised border border-border rounded-md px-3 py-2.5 text-sm"/></label><div><span className="text-xs text-text-secondary">Attach to</span><div className="flex gap-2 mt-1">{(['none','item','project','note'] as ParentType[]).map(t=><button key={t} onClick={()=>{setParentType(t);setParentId('')}} className={`flex-1 px-3 py-2 rounded-md text-sm border capitalize ${parentType===t?'bg-accent/10 border-accent text-accent':'bg-surface-raised border-border text-text-secondary'}`}>{t}</button>)}</div>{parentType!=='none'&&<select value={parentId} onChange={e=>setParentId(e.target.value)} className="mt-2 w-full bg-surface-raised border border-border rounded-md text-sm px-3 py-2.5"><option value="">Select {parentType}…</option>{parentOptions.map(o=><option key={o.id} value={o.id}>{o.name||o.title}</option>)}</select>}</div></div>
 <div className="p-6 bg-bg/20 lg:sticky lg:top-0 lg:self-start"><div className="flex items-center justify-between mb-3"><div><h4 className="font-semibold">Resource preview</h4><p className="text-xs text-text-secondary mt-0.5">How this resource will appear in Resources.</p></div>{youtube&&<span className="text-xs px-2 py-1 rounded-full bg-accent/10 text-accent">YouTube</span>}</div><div className="rounded-lg overflow-hidden border border-border bg-surface-raised">{previewThumb?<div className="aspect-video relative"><img src={previewThumb} alt="YouTube preview" className="w-full h-full object-cover"/><div className="absolute inset-0 flex items-center justify-center"><div className="w-14 h-14 rounded-full bg-black/65 flex items-center justify-center"><Play size={26} className="text-white ml-1" fill="currentColor"/></div></div></div>:<div className="aspect-video flex items-center justify-center"><LinkIcon size={42} className="text-text-secondary"/></div>}<div className="p-4"><div className="text-sm font-semibold truncate">{linkName||(youtube?'YouTube video':'Untitled link')}</div><div className="text-xs text-text-secondary mt-1 break-all line-clamp-2">{linkUrl||'Paste a link to preview it'}</div></div></div>{youtube&&<><div className="mt-4 rounded-md border border-status-success/40 bg-status-success/5 p-4"><div className="flex items-start gap-2"><CheckCircle2 size={18} className="text-status-success shrink-0"/><div><div className="text-sm font-medium text-status-success">Thumbnail downloads immediately</div><p className="text-xs text-text-secondary mt-1">It will be saved with the resource and shown on the resource card.</p></div></div></div><div className="mt-3 rounded-md border border-border bg-surface-raised p-4 space-y-3"><h4 className="text-sm font-semibold">Resource details</h4><div className="flex justify-between text-xs"><span className="text-text-secondary">Video download</span><span>{queueVideo?'Added to queue':'Link only'}</span></div><div className="flex justify-between text-xs"><span className="text-text-secondary">Thumbnail</span><span className="text-status-success">Downloaded immediately</span></div><div className="flex justify-between text-xs"><span className="text-text-secondary">Storage</span><span>LabOS media library</span></div></div><div className="mt-3 rounded-md border border-accent/30 bg-accent/5 p-3 text-xs text-text-secondary">Downloaded media will be attached to this resource and played from the Resource Viewer when ready.</div></>}</div>
 </div>:<div className="p-6 space-y-5"><div className="rounded-md border border-border bg-surface-raised p-4 text-sm">{showAttachModal.file?.name}</div><label className="text-xs text-text-secondary block">Knowledge category<select value={category} onChange={e=>setCategory(e.target.value)} className="mt-1 w-full bg-surface-raised border border-border rounded-md text-sm px-3 py-2.5">{['general','datasheet','manual','schematic','research','tutorial','reference','specification','image','cad','report','video','other'].map(c=><option key={c}>{c}</option>)}</select></label><label className="text-xs text-text-secondary block">Description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3} className="mt-1 w-full bg-surface-raised border border-border rounded-md px-3 py-2.5"/></label><label className="text-xs text-text-secondary block">Tags<input value={tagsInput} onChange={e=>setTagsInput(e.target.value)} placeholder="esp32, power, reference" className="mt-1 w-full bg-surface-raised border border-border rounded-md px-3 py-2.5"/></label><div className="flex gap-2">{(['none','item','project','note'] as ParentType[]).map(t=><button key={t} onClick={()=>{setParentType(t);setParentId('')}} className={`flex-1 px-3 py-2 rounded-md text-sm border capitalize ${parentType===t?'bg-accent/10 border-accent text-accent':'bg-surface-raised border-border text-text-secondary'}`}>{t}</button>)}</div>{parentType!=='none'&&<select value={parentId} onChange={e=>setParentId(e.target.value)} className="w-full bg-surface-raised border border-border rounded-md text-sm px-3 py-2.5"><option value="">Select {parentType}…</option>{parentOptions.map(o=><option key={o.id} value={o.id}>{o.name||o.title}</option>)}</select>}</div>}</div>
 <div className="px-6 py-4 border-t border-border flex items-center justify-between shrink-0"><div>{uploadProgress!==null&&<div className="w-48"><div className="flex justify-between text-[11px] text-text-secondary mb-1"><span>Uploading</span><span>{Math.round(uploadProgress)}%</span></div><div className="h-1.5 bg-bg rounded-full overflow-hidden"><div className="h-full bg-accent transition-[width] duration-150" style={{width:`${uploadProgress}%`}}/></div></div>}</div><div className="flex gap-2"><button onClick={closeAttach} className="px-4 py-2 border border-border rounded-md text-sm">Cancel</button><button onClick={confirmAttach} disabled={(parentType!=='none'&&!parentId)||(showAttachModal.mode==='link'&&!linkUrl.trim())||uploadMutation.isPending||linkMutation.isPending} className="px-5 py-2 bg-accent text-bg rounded-md text-sm font-medium disabled:opacity-40">{showAttachModal.mode==='link'&&youtube&&queueVideo?'Add Resource & Queue':showAttachModal.mode==='upload'?'Upload Resource':'Add Resource'}</button></div></div>
 </div></div>}
 {selectedResource&&<ResourceViewerModal resource={selectedResource} resources={resources} onClose={()=>setSelectedResource(null)} onEdit={r=>setEditingResource(r)}/>} {editingResource&&<ResourceEditorModal resource={editingResource} onClose={()=>setEditingResource(null)} onSaved={handleSaved}/>}</div>;
}
