import { useState, useEffect, useMemo, useRef } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { globalSearch, SearchResult, SearchType } from '../api/search';
import { Search as SearchIcon, Box, FileText, DollarSign, Folder, Filter, X, Layers, Clock3, Users, ClipboardList, Beaker, SquareStack, MapPin } from 'lucide-react';
import { formatQuantity } from '../lib/utils';
import { getStoredUser } from '../api/auth';
import Pagination, { usePagination } from '../components/Pagination';

interface SearchPageProps { initialQuery?: string; onSearchChange?: (query: string) => void; }
const ALL_TYPES: SearchType[] = ['items','projects','notes','resources','transactions','users','tasks','experiments','blocks'];
const TYPE_LABELS: Record<SearchType,string> = { items:'Items', projects:'Projects', notes:'Notes', resources:'Resources', transactions:'Transactions', users:'Users', tasks:'Tasks', experiments:'Experiments', blocks:'Canvas' };
const iconFor = (type: SearchResult['type']) => ({item:Box,project:Layers,note:FileText,transaction:DollarSign,resource:Folder,user:Users,task:ClipboardList,experiment:Beaker,block:SquareStack}[type]);
function ResultCard({ result, onOpen }: { result: SearchResult; onOpen: (r: SearchResult) => void }) { const Icon=iconFor(result.type); return <button onClick={()=>onOpen(result)} className="w-full text-left bg-surface border border-border rounded-md p-4 hover:border-accent hover:bg-surface-raised transition-colors"><div className="flex items-start gap-3"><div className="text-accent mt-1">{Icon&&<Icon size={20}/>}</div><div className="flex-1 min-w-0"><div className="flex items-start justify-between gap-3"><h4 className="text-text-primary font-medium truncate">{result.title}</h4><span className="text-[10px] uppercase tracking-wider text-text-secondary shrink-0">{result.type}</span></div><p className="text-text-secondary text-sm mt-1 truncate">{result.subtitle}</p>{result.type==='item'&&<><div className="text-text-secondary text-sm mt-2">{formatQuantity(result.current_quantity)} {result.unit||''} {result.sku&&`• SKU: ${result.sku}`}</div><div className="flex items-center gap-1.5 mt-2 text-sm"><MapPin size={14} className="text-accent"/><strong className="text-text-primary">{result.storage_location||'Storage location not labeled'}</strong>{result.storage_container_name&&<span className="text-text-secondary">· {result.storage_container_name}</span>}</div></>}{result.type==='note'&&result.body&&<p className="text-text-secondary text-sm line-clamp-2 mt-2">{result.body}</p>}{result.type==='resource'&&result.description&&<p className="text-text-secondary text-sm line-clamp-2 mt-2">{result.description}</p>}{result.tags?.length>0&&<div className="flex gap-1 mt-2 flex-wrap">{result.tags.slice(0,5).map((tag:string)=><span key={tag} className="px-2 py-0.5 bg-surface-raised border border-border rounded text-xs text-text-secondary">{tag}</span>)}</div>}</div></div></button>; }
function SearchSection({ type, values, count, onOpen }: { type: SearchType; values: SearchResult[]; count: number; onOpen: (r: SearchResult) => void }) { const page=usePagination(values,6); return <section className="mb-7"><div className="flex items-center gap-2 mb-3"><h3 className="text-section-header font-ui font-semibold">{TYPE_LABELS[type]}</h3><span className="text-xs text-text-secondary">{count}</span></div><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3">{page.pagedItems.map(r=><ResultCard key={`${r.type}-${r.id}`} result={r} onOpen={onOpen}/>)}</div><Pagination page={page.page} pageSize={page.pageSize} total={values.length} totalPages={page.totalPages} onPageChange={page.setPage} onPageSizeChange={page.changePageSize}/></section>; }
export default function SearchPage({ initialQuery='', onSearchChange }: SearchPageProps) {
 const navigate=useNavigate(); const currentUser=getStoredUser(); const availableTypes=currentUser?.role==='admin'?ALL_TYPES:ALL_TYPES.filter(t=>t!=='users'); const inputRef=useRef<HTMLInputElement>(null); const [query,setQuery]=useState(initialQuery); const [selectedTypes,setSelectedTypes]=useState<Set<SearchType>>(new Set(availableTypes)); const [debouncedQuery,setDebouncedQuery]=useState(initialQuery.trim()); const [recentSearches,setRecentSearches]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem('labos_recent_searches')||'[]');}catch{return[];}});
 // Keep a tiny debounce only to coalesce keystrokes; every typed character still starts a new search.
 useEffect(()=>{const t=setTimeout(()=>setDebouncedQuery(query.trim()),75);return()=>clearTimeout(t);},[query]); useEffect(()=>{if(initialQuery)setQuery(initialQuery);},[initialQuery]); useEffect(()=>{onSearchChange?.(query);},[query,onSearchChange]); useEffect(()=>{if(!debouncedQuery)return;const next=[debouncedQuery,...recentSearches.filter(v=>v!==debouncedQuery)].slice(0,6);setRecentSearches(next);localStorage.setItem('labos_recent_searches',JSON.stringify(next));},[debouncedQuery]); useEffect(()=>{const onKeyDown=(e:KeyboardEvent)=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes((e.target as HTMLElement)?.tagName)){e.preventDefault();inputRef.current?.focus();}};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown);},[]);
 const {data:results,isLoading,error}=useQuery({queryKey:['search',debouncedQuery,Array.from(selectedTypes).sort()],queryFn:()=>globalSearch(debouncedQuery,Array.from(selectedTypes)),enabled:debouncedQuery.length>0&&selectedTypes.size>0,staleTime:15000});
 const toggleType=(type:SearchType)=>setSelectedTypes(current=>{const next=new Set(current);next.has(type)?next.delete(type):next.add(type):next.add(type);return next;}); const handleResultClick=(r:SearchResult)=>{switch(r.type){case'item':navigate(`/inventory/${r.id}`);break;case'project':navigate(`/projects/${r.id}`);break;case'transaction':r.item_id?navigate(`/inventory/${r.item_id}/transactions`):r.project_id?navigate(`/projects/${r.project_id}`):navigate('/financials');break;case'resource':r.item_id?navigate(`/inventory/${r.item_id}`):r.project_id?navigate(`/projects/${r.project_id}/canvas`):navigate('/resources');break;case'note':navigate('/notebook');break;case'user':navigate('/collaboration');break;case'task':navigate(`/projects/${r.project_id}/tasks`);break;case'experiment':navigate(`/projects/${r.project_id}/experiments`);break;case'block':navigate(`/projects/${r.project_id}/canvas`);break;}};
 const sections=useMemo(()=>availableTypes.map(type=>({type,values:results?.[type]||[]})).filter(s=>s.values.length),[results]); const topResults=results?.all||[]; const topPage=usePagination(topResults,6);
 return <div className="p-4 sm:p-6 max-w-[1500px] mx-auto"><div className="flex items-start justify-between gap-4 mb-6"><div><h2 className="text-page-title font-ui font-semibold">Global Search</h2><p className="text-text-secondary text-sm mt-1">Search the laboratory's inventory, projects, notes, resources and financial records.</p></div></div><div className="flex flex-col sm:flex-row gap-3 mb-4"><div className="relative flex-1"><SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 text-text-secondary" size={20}/><input ref={inputRef} autoFocus type="search" placeholder="Search the entire lab..." value={query} onChange={e=>setQuery(e.target.value)} className="w-full pl-10 pr-4 py-3 bg-surface border border-border rounded-sm text-text-primary focus:outline-none focus:border-accent text-base sm:text-lg"/></div><button onClick={()=>setSelectedTypes(new Set(availableTypes))} className="flex items-center justify-center gap-2 px-4 py-3 bg-surface border border-border rounded-sm hover:border-accent"><Filter size={18}/><span className="text-sm">All types</span></button></div><div className="flex gap-2 mb-6 flex-wrap">{availableTypes.map(type=><button key={type} onClick={()=>toggleType(type)} className={`flex items-center gap-2 px-3 py-1.5 rounded-sm text-sm ${selectedTypes.has(type)?'bg-accent text-bg':'bg-surface-raised border border-border text-text-secondary'}`}>{TYPE_LABELS[type]}{selectedTypes.has(type)&&<X size={14}/>}</button>)}</div>
 {!debouncedQuery?<div className="text-center py-14 text-text-secondary"><SearchIcon size={48} className="mx-auto mb-4 opacity-50"/><p className="text-lg">Search across the entire laboratory</p></div>:selectedTypes.size===0?<div className="text-center py-12 text-text-secondary">Select at least one search type.</div>:isLoading?<div className="text-center py-12 text-text-secondary"><Clock3 size={32} className="mx-auto mb-3 animate-pulse"/>Searching the lab...</div>:error?<div className="text-center py-12 text-status-danger">Search failed</div>:!results?.total?<div className="text-center py-12 text-text-secondary">No results for “{debouncedQuery}”</div>:<div><div className="flex items-center justify-between mb-5"><p className="text-text-secondary text-sm">{results.total} matching result{results.total!==1?'s':''}</p></div>{topResults.length>0&&<section className="mb-8"><h3 className="text-section-header font-ui font-semibold mb-3">Best matches</h3><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3">{topPage.pagedItems.map(r=><ResultCard key={`${r.type}-${r.id}`} result={r} onOpen={handleResultClick}/>)}</div><Pagination page={topPage.page} pageSize={topPage.pageSize} total={topResults.length} totalPages={topPage.totalPages} onPageChange={topPage.setPage} onPageSizeChange={topPage.changePageSize}/></section>}{sections.map(s=><SearchSection key={s.type} type={s.type} values={s.values} count={results.counts?.[s.type]??s.values.length} onOpen={handleResultClick}/>)}</div>}
 </div>;
}
