import { useState, useEffect, useRef } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { globalSearch, SearchResult, SearchType } from '../api/search';
import { Search as SearchIcon, Box, FileText, DollarSign, Folder, Filter, X, Layers, Clock3, Users, ClipboardList, Beaker, SquareStack, BookOpen, MapPin, RotateCcw } from 'lucide-react';
import { formatQuantity } from '../lib/utils';
import { getStoredUser } from '../api/auth';
import SearchItemActionModal from '../components/SearchItemActionModal';

interface SearchPageProps { initialQuery?: string; onSearchChange?: (query: string) => void; }
const ALL_TYPES: SearchType[] = ['items','projects','notes','resources','transactions','users','tasks','experiments','findings','blocks'];
const TYPE_LABELS: Record<SearchType,string> = { items:'Items', projects:'Projects', notes:'Notes', resources:'Resources', transactions:'Transactions', users:'Users', tasks:'Tasks', experiments:'Experiments', findings:'Findings', blocks:'Canvas' };
const iconFor = (type: SearchResult['type']) => ({item:Box,project:Layers,note:FileText,transaction:DollarSign,resource:Folder,user:Users,task:ClipboardList,experiment:Beaker,finding:BookOpen,block:SquareStack}[type]);
function ResultCard({ result, onOpen, onAction }: { result: SearchResult; onOpen: (r: SearchResult) => void; onAction:(r:SearchResult,mode:'specs'|'use')=>void }) { const Icon=iconFor(result.type); return <div className="w-full min-h-[150px] text-left bg-surface border border-border rounded-md p-5 hover:border-accent hover:bg-surface-raised transition-colors"><button type="button" onClick={()=>onOpen(result)} className="w-full text-left"><div className="flex items-start gap-3"><div className="text-accent mt-1">{Icon&&<Icon size={20}/>}</div><div className="flex-1 min-w-0"><div className="flex items-start justify-between gap-3"><h4 className="text-text-primary font-medium truncate">{result.title}</h4><span className="text-[10px] uppercase tracking-wider text-text-secondary shrink-0">{result.type}</span></div><p className="text-text-secondary text-sm mt-1 truncate">{result.subtitle}</p>{result.type==='item'&&<><div className="text-text-secondary text-sm mt-2">{formatQuantity(result.current_quantity)} {result.unit||''} {result.sku&&`• SKU: ${result.sku}`}</div><div className="flex items-center gap-1.5 mt-2 text-sm"><MapPin size={14} className="text-accent"/><strong className="text-text-primary">{result.storage_location||'Storage location not labeled'}</strong>{result.storage_container_name&&<span className="text-text-secondary">· {result.storage_container_name}</span>}</div></>}{result.type==='note'&&result.body&&<p className="text-text-secondary text-sm line-clamp-2 mt-2">{result.body}</p>}{result.type==='resource'&&result.description&&<p className="text-text-secondary text-sm line-clamp-2 mt-2">{result.description}</p>}{result.tags?.length>0&&<div className="flex gap-1 mt-2 flex-wrap">{result.tags.slice(0,5).map((tag:string)=><span key={tag} className="px-2 py-0.5 bg-surface-raised border border-border rounded text-xs text-text-secondary">{tag}</span>)}</div>}</div></div></button>{result.type==='item'&&<div className="flex gap-2 mt-3"><button type="button" onClick={()=>onAction(result,'specs')} className="text-xs px-3 py-2 rounded-md border border-border hover:border-accent">Datasheet & Specs</button><button type="button" onClick={()=>onAction(result,'use')} className="text-xs px-3 py-2 rounded-md bg-accent text-bg">Use item</button></div>}</div>; }
export default function SearchPage({ initialQuery='', onSearchChange }: SearchPageProps) {
 const navigate=useNavigate(); const [action,setAction]=useState<{itemId:string;mode:'specs'|'use'}|null>(null); const currentUser=getStoredUser(); const availableTypes=currentUser?.role==='admin'?ALL_TYPES:ALL_TYPES.filter(t=>t!=='users'); const inputRef=useRef<HTMLInputElement>(null); const [query,setQuery]=useState(initialQuery); const [selectedTypes,setSelectedTypes]=useState<Set<SearchType>>(new Set(availableTypes)); const [debouncedQuery,setDebouncedQuery]=useState(initialQuery.trim()); const [recentSearches,setRecentSearches]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem('labos_recent_searches')||'[]');}catch{return[];}});
 useEffect(()=>{const t=setTimeout(()=>setDebouncedQuery(query.trim()),75);return()=>clearTimeout(t);},[query]); useEffect(()=>{if(initialQuery)setQuery(initialQuery);},[initialQuery]); useEffect(()=>{onSearchChange?.(query);},[query,onSearchChange]); useEffect(()=>{if(!debouncedQuery)return;const next=[debouncedQuery,...recentSearches.filter(v=>v!==debouncedQuery)].slice(0,6);setRecentSearches(next);localStorage.setItem('labos_recent_searches',JSON.stringify(next));},[debouncedQuery]); useEffect(()=>{const onKeyDown=(e:KeyboardEvent)=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes((e.target as HTMLElement)?.tagName)){e.preventDefault();inputRef.current?.focus();}};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown);},[]);
 const {data:results,isLoading,error,refetch}=useQuery({queryKey:['search',debouncedQuery,Array.from(selectedTypes).sort()],queryFn:()=>globalSearch(debouncedQuery,Array.from(selectedTypes)),enabled:debouncedQuery.length>0&&selectedTypes.size>0,staleTime:15000});
 const toggleType=(type:SearchType)=>setSelectedTypes(current=>{const next=new Set(current);if(next.has(type))next.delete(type);else next.add(type);return next;}); const clearSearch=()=>{setQuery('');setDebouncedQuery('');inputRef.current?.focus();}; const selectRecent=(value:string)=>{setQuery(value);inputRef.current?.focus();}; const handleResultClick=(r:SearchResult)=>{switch(r.type){case'item':navigate(`/inventory/${r.id}`);break;case'project':navigate(`/projects/${r.id}`);break;case'transaction':r.item_id?navigate(`/inventory/${r.item_id}/transactions`):r.project_id?navigate(`/projects/${r.project_id}`):navigate('/financials');break;case'resource':r.item_id?navigate(`/inventory/${r.item_id}`):r.project_id?navigate(`/projects/${r.project_id}/canvas`):navigate('/resources');break;case'note':navigate('/notebook');break;case'user':navigate('/collaboration');break;case'task':navigate(`/projects/${r.project_id}/tasks`);break;case'experiment':navigate(`/projects/${r.project_id}/experiments`);break;case'finding':navigate('/knowledge');break;case'block':navigate(`/projects/${r.project_id}/canvas`);break;}};
 const topResults=results?.all||[];
 return <div className="p-4 sm:p-6 max-w-[1500px] mx-auto"><div className="flex items-start justify-between gap-4 mb-6"><div><p className="page-kicker">DISCOVERY</p><h2 className="text-page-title font-ui font-semibold">Global Search</h2><p className="text-text-secondary text-sm mt-1">Search the laboratory's inventory, projects, notes, resources, findings and financial records.</p></div></div><div className="flex flex-col sm:flex-row gap-3 mb-3"><div className="relative flex-1"><SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 text-text-secondary" size={20}/><input ref={inputRef} autoFocus type="search" aria-label="Search the entire laboratory" placeholder="Search the entire lab..." value={query} onChange={e=>setQuery(e.target.value)} className="w-full pl-10 pr-20 py-3 bg-surface border border-border rounded-sm text-text-primary focus:outline-none focus:border-accent focus:ring-1 focus:ring-accent/20 text-base sm:text-lg"/>{query&&<button type="button" onClick={clearSearch} className="absolute right-10 top-1/2 -translate-y-1/2 p-1.5 rounded-sm text-text-secondary hover:text-text-primary hover:bg-surface-raised transition-colors" aria-label="Clear search" title="Clear search"><X size={16}/></button>}<kbd className="absolute right-3 top-1/2 -translate-y-1/2 hidden sm:inline-flex items-center rounded border border-border bg-surface-raised px-1.5 py-0.5 text-[10px] text-text-tertiary">/</kbd></div><button type="button" onClick={()=>setSelectedTypes(new Set(availableTypes))} className="flex items-center justify-center gap-2 px-4 py-3 bg-surface border border-border rounded-sm hover:border-accent hover:bg-surface-raised transition-colors focus:outline-none focus:ring-1 focus:ring-accent/30"><Filter size={18}/><span className="text-sm">All types</span></button></div><div className="flex items-center justify-between gap-3 mb-3"><p className="text-xs text-text-secondary">{selectedTypes.size} of {availableTypes.length} types selected</p>{selectedTypes.size<availableTypes.length&&<button type="button" onClick={()=>setSelectedTypes(new Set(availableTypes))} className="inline-flex items-center gap-1.5 text-xs text-text-secondary hover:text-text-primary transition-colors"><RotateCcw size={13}/>Select all</button>}</div><div className="flex gap-2 mb-6 flex-wrap">{availableTypes.map(type=><button type="button" key={type} onClick={()=>toggleType(type)} aria-pressed={selectedTypes.has(type)} className={`flex items-center gap-2 px-3 py-1.5 rounded-sm text-sm transition-colors focus:outline-none focus:ring-1 focus:ring-accent/30 ${selectedTypes.has(type)?'bg-accent text-bg':'bg-surface-raised border border-border text-text-secondary hover:border-accent hover:text-text-primary'}`}>{TYPE_LABELS[type]}{selectedTypes.has(type)&&<X size={14}/>}</button>)}</div>
 {!debouncedQuery?<div className="text-center py-14 text-text-secondary"><SearchIcon size={48} className="mx-auto mb-4 opacity-50"/><p className="text-lg text-text-primary">Search across the entire laboratory</p><p className="text-sm mt-1">{recentSearches.length?'Your recent searches are ready below.':'Enter a term to search across your lab records.'}</p>{recentSearches.length>0&&<div className="flex flex-wrap justify-center gap-2 mt-5">{recentSearches.map(value=><button type="button" key={value} onClick={()=>selectRecent(value)} className="px-3 py-1.5 rounded-full border border-border bg-surface-raised text-xs text-text-secondary hover:text-text-primary hover:border-accent transition-colors">{value}</button>)}</div>}</div>:selectedTypes.size===0?<div className="text-center py-12 text-text-secondary">Select at least one search type.</div>:isLoading?<div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3" aria-live="polite" aria-busy="true">{Array.from({length:6}).map((_,i)=><div key={i} className="min-h-[150px] rounded-md border border-border bg-surface p-5 animate-pulse"><div className="h-5 w-2/3 rounded bg-surface-raised"/><div className="h-4 w-1/2 rounded bg-surface-raised mt-3"/><div className="h-4 w-full rounded bg-surface-raised mt-5"/><div className="h-4 w-3/4 rounded bg-surface-raised mt-2"/></div>)}</div>:error?<div className="text-center py-12"><p className="text-status-danger font-medium">Search failed</p><p className="text-text-secondary text-sm mt-1">We couldn't complete that search.</p><button type="button" onClick={()=>refetch()} className="inline-flex items-center gap-2 mt-4 px-3.5 py-2 bg-surface-raised border border-border rounded-sm hover:border-accent transition-colors text-sm font-medium"><RotateCcw size={15}/>Try again</button></div>:!results?.total?<div className="text-center py-12"><SearchIcon size={32} className="mx-auto mb-3 text-text-secondary"/><p className="text-text-primary font-medium">No results for “{debouncedQuery}”</p><p className="text-text-secondary text-sm mt-1">Try a broader term or enable more search types.</p></div>:<div><div className="flex items-center justify-between mb-5"><div><p className="text-text-primary text-sm font-medium">{results.total} matching result{results.total!==1?'s':''}</p><p className="text-text-secondary text-xs mt-0.5">Showing the best matches first</p></div></div><section><h3 className="text-section-header font-ui font-semibold mb-3">Best matches</h3><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3">{topResults.map(r=><ResultCard key={`${r.type}-${r.id}`} result={r} onOpen={handleResultClick} onAction={(result,mode)=>setAction({itemId:result.id,mode})}/>)}</div></section></div>}
 {action&&<SearchItemActionModal itemId={action.itemId} mode={action.mode} onClose={()=>setAction(null)}/>}
 </div>;
}
