import { deflateRawSync, inflateRawSync } from 'node:zlib';
import { Buffer } from 'node:buffer';

const CRC_TABLE = (() => { const table = new Uint32Array(256); for (let n = 0; n < 256; n += 1) { let c = n; for (let k = 0; k < 8; k += 1) c = (c & 1) ? 0xedb88320 ^ (c >>> 1) : c >>> 1; table[n] = c >>> 0; } return table; })();
function crc32(input) { const bytes = Buffer.isBuffer(input) ? input : Buffer.from(input); let crc = 0xffffffff; for (const byte of bytes) crc = CRC_TABLE[(crc ^ byte) & 0xff] ^ (crc >>> 8); return (crc ^ 0xffffffff) >>> 0; }
function u16(n) { const b = Buffer.alloc(2); b.writeUInt16LE(n, 0); return b; }
function u32(n) { const b = Buffer.alloc(4); b.writeUInt32LE(n >>> 0, 0); return b; }
function sanitizeXmlText(value) { return String(value ?? '').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\uD800-\uDFFF\uFFFE\uFFFF]/g, ''); }
function xmlEscape(value) { return sanitizeXmlText(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;'); }
function columnName(index) { let n = index + 1, out = ''; while (n) { const r = (n - 1) % 26; out = String.fromCharCode(65 + r) + out; n = Math.floor((n - 1) / 26); } return out; }
function makeSheetXml(rows, widths = []) {
  const maxCol = Math.max(1, ...rows.map((row) => row.length)); const maxRow = Math.max(1, rows.length);
  const cols = widths.length ? `<cols>${widths.map((w, i) => `<col min="${i + 1}" max="${i + 1}" width="${Math.max(0.5, Math.min(255, Number(w) || 14))}" customWidth="1"/>`).join('')}</cols>` : '';
  const sheetRows = rows.map((row, r) => { const cells = row.map((value, c) => { if (value === null || value === undefined || value === '') return ''; const ref = `${columnName(c)}${r + 1}`; if (typeof value === 'number' && Number.isFinite(value)) return `<c r="${ref}"><v>${value}</v></c>`; return `<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${xmlEscape(value)}</t></is></c>`; }).join(''); return `<row r="${r + 1}">${cells}</row>`; }).join('');
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:${columnName(maxCol - 1)}${maxRow}"/><sheetViews><sheetView workbookViewId="0"><selection activeCell="A1" sqref="A1"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="15"/><cols>${widths.length ? widths.map((w, i) => `<col min="${i + 1}" max="${i + 1}" width="${Math.max(0.5, Math.min(255, Number(w) || 14))}" customWidth="1"/>`).join('') : ''}</cols><sheetData>${sheetRows}</sheetData><pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/></worksheet>`;
}
function zipEntries(entries) { const local = [], central = []; let offset = 0; for (const entry of entries) { const name = Buffer.from(entry.name); const raw = Buffer.from(entry.data); const compressed = deflateRawSync(raw, { level: 6 }); const crc = crc32(raw); const header = Buffer.concat([Buffer.from([0x50,0x4b,0x03,0x04]),u16(20),u16(0),u16(8),u16(0),u16(0),u32(crc),u32(compressed.length),u32(raw.length),u16(name.length),u16(0),name]); local.push(header, compressed); const cdir = Buffer.concat([Buffer.from([0x50,0x4b,0x01,0x02]),u16(20),u16(20),u16(0),u16(8),u16(0),u16(0),u32(crc),u32(compressed.length),u32(raw.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]); central.push(cdir); offset += header.length + compressed.length; } const centralData = Buffer.concat(central); const localData = Buffer.concat(local); const end = Buffer.concat([Buffer.from([0x50,0x4b,0x05,0x06]),u16(0),u16(0),u16(entries.length),u16(entries.length),u32(centralData.length),u32(localData.length),u16(0)]); return Buffer.concat([localData,centralData,end]); }
export function buildXlsx({ sheets }) { const sheetNames = Object.keys(sheets); const workbookSheets = sheetNames.map((name,i)=>`<sheet name="${xmlEscape(name.slice(0,31))}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join(''); const relationships = sheetNames.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join(''); const overrides = sheetNames.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join(''); const entries=[{name:'[Content_Types].xml',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${overrides}</Types>`},{name:'_rels/.rels',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`},{name:'xl/workbook.xml',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${workbookSheets}</sheets><calcPr calcMode="auto"/></workbook>`},{name:'xl/_rels/workbook.xml.rels',data:`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${relationships}</Relationships>`}]; sheetNames.forEach((name,i)=>entries.push({name:`xl/worksheets/sheet${i+1}.xml`,data:makeSheetXml(sheets[name].rows,sheets[name].widths)})); return zipEntries(entries); }
function findEndOfCentralDirectory(buffer) { for(let i=buffer.length-22;i>=Math.max(0,buffer.length-65557);i-=1) if(buffer.readUInt32LE(i)===0x06054b50)return i; return -1; }
function readZipEntries(buffer) { const eocd=findEndOfCentralDirectory(buffer); if(eocd<0)throw new Error('Invalid XLSX archive'); const count=buffer.readUInt16LE(eocd+10); const centralOffset=buffer.readUInt32LE(eocd+16); let cursor=centralOffset; const entries=new Map(); for(let i=0;i<count;i+=1){if(buffer.readUInt32LE(cursor)!==0x02014b50)throw new Error('Invalid XLSX central directory'); const method=buffer.readUInt16LE(cursor+10),compressedSize=buffer.readUInt32LE(cursor+20),nameLen=buffer.readUInt16LE(cursor+28),extraLen=buffer.readUInt16LE(cursor+30),commentLen=buffer.readUInt16LE(cursor+32),localOffset=buffer.readUInt32LE(cursor+42); const name=buffer.subarray(cursor+46,cursor+46+nameLen).toString('utf8'); const localNameLen=buffer.readUInt16LE(localOffset+26),localExtraLen=buffer.readUInt16LE(localOffset+28); const start=localOffset+30+localNameLen+localExtraLen; const compressed=buffer.subarray(start,start+compressedSize); if(method!==8&&method!==0)throw new Error(`Unsupported XLSX compression method: ${method}`); entries.set(name,method===8?inflateRawSync(compressed).toString('utf8'):compressed.toString('utf8')); cursor+=46+nameLen+extraLen+commentLen;} return entries; }
function decodeXmlText(text) { return String(text??'').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&'); }
function parseSharedStrings(xml) { if(!xml)return []; return [...xml.matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g)].map(match=>[...match[1].matchAll(/<t(?:\s[^>]*)?>([\s\S]*?)<\/t>/g)].map(m=>decodeXmlText(m[1])).join('')); }
function parseSheetXml(xml,sharedStrings=[]) { const rows=[]; const rowMatches=xml.match(/<row\b[^>]*>([\s\S]*?)<\/row>/g)||[]; for(const rowXml of rowMatches){const row=[]; const cells=rowXml.match(/<c\b[^>]*(?:\/>|>[\s\S]*?<\/c>)/g)||[]; for(const cell of cells){const ref=/\br="([A-Z]+)\d+"/.exec(cell)?.[1]; if(!ref)continue; let col=0; for(const ch of ref)col=col*26+ch.charCodeAt(0)-64; col-=1; if(/\/\s*>$/.test(cell)){row[col]='';continue;} const type=/\bt="([^"]+)"/.exec(cell)?.[1]||''; const value=cell.match(/<v>([\s\S]*?)<\/v>/)?.[1]||''; if(type==='inlineStr'){row[col]=[...cell.matchAll(/<t(?:\s[^>]*)?>([\s\S]*?)<\/t>/g)].map(m=>decodeXmlText(m[1])).join('');} else if(type==='s'){const index=Number(value);row[col]=Number.isInteger(index)&&index>=0?sharedStrings[index]??'':'';} else if(type==='b'){row[col]=value==='1';} else if(value===''){row[col]='';} else {const number=Number(value);row[col]=Number.isNaN(number)?decodeXmlText(value):number;}} rows.push(row);} return rows; }
export function parseXlsx(buffer) { const entries=readZipEntries(buffer); const workbook=entries.get('xl/workbook.xml'),rels=entries.get('xl/_rels/workbook.xml.rels'); if(!workbook||!rels)throw new Error('Workbook metadata is missing'); const sharedStrings=parseSharedStrings(entries.get('xl/sharedStrings.xml')); const relMap=new Map([...rels.matchAll(/<Relationship\b[^>]*Id="([^"]+)"[^>]*Target="([^"]+)"/g)].map(m=>[m[1],m[2].replace(/^\//,'').startsWith('xl/')?m[2].replace(/^\//,''):`xl/${m[2].replace(/^\//,'')}`])); const sheets=[]; for(const match of workbook.matchAll(/<sheet\b[^>]*name="([^"]+)"[^>]*r:id="([^"]+)"/g)){const target=relMap.get(match[2]);if(!target||!entries.has(target))continue;sheets.push({name:decodeXmlText(match[1]),rows:parseSheetXml(entries.get(target),sharedStrings)});} if(!sheets.length)throw new Error('No worksheets found'); return {sheets}; }
