import { useMutation, useQueryClient } from '@tanstack/react-query';
import { createItem, Item } from '../api/items';
import { generateItemSku } from '../api/item-sku';
import { useToast } from '../contexts/ToastContext';
import { useState } from 'react';
interface AddItemModalProps { onClose: () => void; }
export default function AddItemModal({ onClose }: AddItemModalProps) {
  const queryClient = useQueryClient(); const { showToast } = useToast();
  const [formData, setFormData] = useState({ name:'', type:'tool' as Item['type'], category:'', sku:'', initial_quantity:1, unit:'', dimensions:'', status:'available' as Item['status'], storage_location:'', unit_cost:'', replacement_cost:'', supplier:'', part_number:'', acquisition_method:'unspecified' as NonNullable<Item['acquisition_method']>, acquisition_source:'', acquisition_notes:'' });
  const createMutation = useMutation({
    mutationFn: createItem,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey:['items'] });
      showToast('Item created');
      onClose();
    },
    onError: (err: unknown) => {
      const message = typeof err === 'string'
        ? err
        : err && typeof err === 'object' && 'message' in err
          ? String((err as { message?: unknown }).message || '')
          : '';
      showToast(message || 'Failed to create item', 'error');
    },
  });
  const handleSubmit=(e:React.FormEvent)=>{e.preventDefault();const sku=formData.sku.trim()||generateItemSku(formData.name,formData.type);createMutation.mutate({...formData,sku,initial_quantity:Number(formData.initial_quantity),unit_cost:formData.unit_cost?Number(formData.unit_cost):undefined,replacement_cost:formData.replacement_cost?Number(formData.replacement_cost):undefined,storage_location:formData.storage_location.trim()||undefined,current_quantity:Number(formData.initial_quantity)} as Omit<Item,'id'|'created_at'|'updated_at'>);};
  const field='w-full px-3 py-2 bg-bg border border-border rounded-sm text-text-primary focus:outline-none focus:border-accent';
  return <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-3"><div role="dialog" aria-modal="true" aria-labelledby="add-item-title" className="bg-surface border border-border rounded-md w-[600px] max-w-full max-h-[90vh] flex flex-col overflow-hidden"><form onSubmit={handleSubmit} className="flex flex-col min-h-0"><header className="flex items-center justify-between gap-3 px-4 py-2.5 border-b border-border bg-surface shrink-0"><h3 id="add-item-title" className="text-section-header font-ui font-semibold">Add Item</h3><div className="flex items-center gap-2"><button type="button" onClick={onClose} className="px-3 py-1.5 border border-border rounded-sm text-sm">Cancel</button><button type="submit" disabled={createMutation.isPending} className="px-3 py-1.5 bg-accent text-bg rounded-sm text-sm disabled:opacity-50">{createMutation.isPending?'Creating…':'Save'}</button></div></header><div className="overflow-y-auto min-h-0 p-4 space-y-4">
    <div className="grid grid-cols-2 gap-4"><div><label className="block text-sm text-text-secondary mb-1">Name *</label><input value={formData.name} onChange={e=>setFormData({...formData,name:e.target.value})} className={field} required/></div><div><label className="block text-sm text-text-secondary mb-1">Type *</label><select value={formData.type} onChange={e=>setFormData({...formData,type:e.target.value as Item['type']})} className={field} required><option value="tool">Tool</option><option value="component">Component</option><option value="equipment">Equipment</option><option value="material">Material</option><option value="chemical">Chemical</option><option value="consumable">Consumable</option><option value="instrument">Instrument</option><option value="spare_part">Spare Part</option></select></div></div>
    <div className="grid grid-cols-2 gap-4"><div><label className="block text-sm text-text-secondary mb-1">Category</label><input value={formData.category} onChange={e=>setFormData({...formData,category:e.target.value})} className={field}/></div><div><label className="block text-sm text-text-secondary mb-1">SKU</label><input value={formData.sku} onChange={e=>setFormData({...formData,sku:e.target.value})} className={field}/><p className="text-xs text-text-secondary mt-1">Leave blank to generate a SKU automatically when the item is saved. Edit it only if your lab already has its own SKU.</p></div></div>
    <div className="grid grid-cols-2 gap-4"><div><label className="block text-sm text-text-secondary mb-1">Supplier</label><input value={formData.supplier} onChange={e=>setFormData({...formData,supplier:e.target.value})} className={field}/></div><div><label className="block text-sm text-text-secondary mb-1">Part Number</label><input value={formData.part_number} onChange={e=>setFormData({...formData,part_number:e.target.value})} className={field}/></div></div>
    <fieldset className="border border-border rounded-md p-3 space-y-3"><legend className="text-sm font-medium px-1">How was this item obtained?</legend><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><label htmlFor="acquisition-method" className="block text-sm text-text-secondary mb-1">Acquisition method</label><select id="acquisition-method" value={formData.acquisition_method} onChange={e=>setFormData({...formData,acquisition_method:e.target.value as NonNullable<Item['acquisition_method']>})} className={field}><option value="unspecified">Not specified</option><option value="purchased">Purchased</option><option value="salvaged">Salvaged</option><option value="donated">Donated</option><option value="transferred">Transferred</option><option value="fabricated">Made in lab</option><option value="other">Other</option></select></div><div><label htmlFor="acquisition-source" className="block text-sm text-text-secondary mb-1">{formData.acquisition_method==='donated'?'Donor':formData.acquisition_method==='salvaged'?'Salvaged from':'Source (optional)'}</label><input id="acquisition-source" value={formData.acquisition_source} onChange={e=>setFormData({...formData,acquisition_source:e.target.value})} placeholder={formData.acquisition_method==='salvaged'?'Old printer, discarded equipment…':formData.acquisition_method==='donated'?'Donor or organization':'Where it came from'} className={field}/></div></div><div><label htmlFor="acquisition-notes" className="block text-sm text-text-secondary mb-1">Acquisition notes (optional)</label><input id="acquisition-notes" value={formData.acquisition_notes} onChange={e=>setFormData({...formData,acquisition_notes:e.target.value})} placeholder="Condition, recovery details or donation reference" className={field}/></div><p className="text-xs text-text-secondary">Purchase cost is optional; replacement value can be recorded separately for salvaged or donated items.</p></fieldset>
    <div className="grid grid-cols-3 gap-4"><div><label className="block text-sm text-text-secondary mb-1">Initial Qty *</label><input type="number" min="1" value={formData.initial_quantity} onChange={e=>setFormData({...formData,initial_quantity:parseInt(e.target.value)||1})} className={field} required/></div><div><label className="block text-sm text-text-secondary mb-1">Unit</label><input value={formData.unit} onChange={e=>setFormData({...formData,unit:e.target.value})} placeholder="pcs, kg, mL" className={field}/></div><div><label className="block text-sm text-text-secondary mb-1">Status *</label><select value={formData.status} onChange={e=>setFormData({...formData,status:e.target.value as Item['status']})} className={field} required><option value="available">Available</option><option value="in_use">In Use</option><option value="damaged">Damaged</option><option value="needs_repair">Needs Repair</option><option value="needs_replacement">Needs Replacement</option><option value="low_stock">Low Stock</option><option value="retired">Retired</option></select></div></div>
    <div><label className="block text-sm text-text-secondary mb-1">Dimensions</label><input value={formData.dimensions} onChange={e=>setFormData({...formData,dimensions:e.target.value})} placeholder="e.g., 10x5x2 cm" className={field}/></div>
    <div><label className="block text-sm text-text-secondary mb-1">Location</label><input value={formData.storage_location} onChange={e=>setFormData({...formData,storage_location:e.target.value})} placeholder="e.g., Toolbox A, Components Cabinet, Drawer 3" className={field}/><p className="text-xs text-text-secondary mt-1">Use the name you actually use for the storage container. No bins, racks, or predefined locations required.</p></div>
    <div className="grid grid-cols-2 gap-4"><div><label className="block text-text-secondary text-sm mb-1">Unit Cost</label><input type="number" step="0.01" value={formData.unit_cost} onChange={e=>setFormData({...formData,unit_cost:e.target.value})} className={field}/></div><div><label className="block text-text-secondary text-sm mb-1">Replacement Cost</label><input type="number" step="0.01" value={formData.replacement_cost} onChange={e=>setFormData({...formData,replacement_cost:e.target.value})} className={field}/></div></div>
    </div></form></div></div>;
}
