import { useRef, useState } from 'react';
import { Download, FileSpreadsheet, Loader2, Upload, X, CheckCircle2, AlertTriangle } from 'lucide-react';
import { downloadPurchaseTemplate, previewPurchaseExcel, importPurchaseExcel, PurchasePreview } from '../api/purchases';
import { useToast } from '../contexts/ToastContext';

function saveBlob(blob: Blob) { const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'LabOS-Bulk-Purchase-Template.xlsx'; a.click(); URL.revokeObjectURL(url); }

export default function ExcelPurchaseModal({ onClose, onImported }: { onClose: () => void; onImported: () => void }) {
  const input = useRef<HTMLInputElement>(null); const { showToast } = useToast();
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<PurchasePreview | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const choose = (next: File | null) => { setFile(next); setPreview(null); setError(''); };
  const previewFile = async () => { if (!file) return; setBusy(true); setError(''); try { setPreview(await previewPurchaseExcel(file)); } catch (e: any) { setError(e?.message || 'Unable to preview workbook'); } finally { setBusy(false); } };
  const importFile = async () => { if (!file || !preview || preview.error_rows) return; setBusy(true); setError(''); try { const result = await importPurchaseExcel(file); onImported(); showToast(`${result.imported} purchase line${result.imported === 1 ? '' : 's'} imported • ${result.created_items} new item${result.created_items === 1 ? '' : 's'}`); onClose(); } catch (e: any) { setError(e?.message || 'Bulk purchase import failed'); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-labelledby="bulk-purchase-title">
    <div className="w-full max-w-3xl max-h-[90vh] overflow-auto bg-surface border border-border rounded-lg shadow-2xl">
      <div className="flex items-start justify-between gap-4 px-5 py-4 border-b border-border"><div><h2 id="bulk-purchase-title" className="text-lg font-semibold text-text-primary">Bulk purchase via Excel</h2><p className="mt-1 text-sm text-text-secondary">Upload one workbook to receive stock and record the purchase expense together.</p></div><button onClick={onClose} className="p-2 text-text-secondary hover:text-text-primary hover:bg-surface-raised rounded-sm" aria-label="Close"><X size={18}/></button></div>
      <div className="p-5 space-y-5">
        <div className="grid gap-3 sm:grid-cols-2"><button onClick={async () => { try { saveBlob(await downloadPurchaseTemplate()); } catch (e: any) { showToast(e?.message || 'Unable to download template', 'error'); } }} className="flex items-center gap-3 p-4 border border-border rounded-md hover:border-accent hover:bg-surface-raised text-left"><span className="p-2 rounded-sm bg-accent/10 text-accent"><Download size={18}/></span><span><strong className="block text-sm text-text-primary">1. Download template</strong><span className="text-xs text-text-secondary">Open it in Excel and fill your purchase lines.</span></span></button><button onClick={() => input.current?.click()} className="flex items-center gap-3 p-4 border border-border rounded-md hover:border-accent hover:bg-surface-raised text-left"><span className="p-2 rounded-sm bg-accent/10 text-accent"><Upload size={18}/></span><span><strong className="block text-sm text-text-primary">2. Choose workbook</strong><span className="text-xs text-text-secondary">Use the LabOS Bulk Purchase .xlsx template.</span></span></button></div>
        <input ref={input} type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" className="hidden" onChange={(e) => choose(e.target.files?.[0] || null)} />
        {file && <div className="flex items-center justify-between gap-3 p-3 border border-border bg-surface-raised rounded-md"><div className="flex items-center gap-3 min-w-0"><FileSpreadsheet size={20} className="text-accent shrink-0"/><div className="min-w-0"><p className="text-sm font-medium text-text-primary truncate">{file.name}</p><p className="text-xs text-text-secondary">Ready for validation</p></div></div><button onClick={() => choose(null)} className="p-1.5 text-text-secondary hover:text-text-primary" aria-label="Remove file"><X size={16}/></button></div>}
        {error && <div className="flex gap-2 p-3 border border-status-danger/30 bg-status-danger/5 rounded-md text-sm text-status-danger"><AlertTriangle size={17} className="shrink-0"/>{error}</div>}
        {preview && <div className="space-y-3"><div className="grid grid-cols-2 sm:grid-cols-4 gap-2">{[['Rows',preview.total_rows],['Ready',preview.ready_rows],['Batches',preview.batches],['New items',preview.new_items]].map(([label,value])=><div key={String(label)} className="p-3 border border-border rounded-md"><div className="text-xs text-text-secondary">{label}</div><div className="mt-1 text-lg font-semibold font-mono text-text-primary">{value}</div></div>)}</div>{preview.error_rows > 0 ? <div className="flex gap-2 p-3 border border-status-warning/30 bg-status-warning/5 rounded-md text-sm text-text-primary"><AlertTriangle size={17} className="text-status-warning shrink-0"/><div><strong>{preview.error_rows} row{preview.error_rows === 1 ? '' : 's'} need attention.</strong><ul className="mt-1 text-text-secondary">{preview.errors.slice(0,5).map(e=><li key={e.row}>Row {e.row}: {e.errors.join(', ')}</li>)}</ul></div></div> : <div className="flex gap-2 p-3 border border-status-success/30 bg-status-success/5 rounded-md text-sm text-text-primary"><CheckCircle2 size={17} className="text-status-success shrink-0"/>All rows passed validation. Import will update inventory and create the matching purchase expense transaction.</div>}</div>}
      </div>
      <div className="flex justify-end gap-2 px-5 py-4 border-t border-border bg-surface-raised"><button onClick={onClose} className="px-3.5 py-2 border border-border rounded-sm text-sm font-medium hover:bg-surface">Cancel</button><button onClick={previewFile} disabled={!file || busy} className="px-3.5 py-2 border border-accent text-accent rounded-sm text-sm font-medium hover:bg-accent/10 disabled:opacity-50">{busy && !preview ? <Loader2 size={15} className="inline mr-2 animate-spin"/> : null}Validate workbook</button><button onClick={importFile} disabled={!preview || preview.error_rows > 0 || busy} className="px-3.5 py-2 bg-accent text-bg rounded-sm text-sm font-medium hover:bg-accent-dim disabled:opacity-50">{busy && preview ? <Loader2 size={15} className="inline mr-2 animate-spin"/> : null}Import purchase</button></div>
    </div>
  </div>;
}
