import { useRef, useState } from 'react';
import { AlertTriangle, CheckCircle2, Download, FileSpreadsheet, Loader2, Upload, X } from 'lucide-react';
import { downloadFinanceTemplate, importFinanceExcel, previewFinanceExcel, type FinancePreview } from '../api/excel-finance';
import { useToast } from '../contexts/ToastContext';

function saveBlob(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); }

export default function ExcelFinanceModal({ onClose, onImported }: { onClose: () => void; onImported: () => void }) {
  const input = useRef<HTMLInputElement>(null); const { showToast } = useToast();
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<FinancePreview | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const choose = (next: File | null) => { setFile(next); setPreview(null); setError(''); };
  const validate = async () => { if (!file) return; setBusy(true); setError(''); try { setPreview(await previewFinanceExcel(file)); } catch (e: any) { setError(e?.message || 'Unable to validate workbook'); } finally { setBusy(false); } };
  const importFile = async () => { if (!file || !preview || preview.error_rows) return; setBusy(true); setError(''); try { const result = await importFinanceExcel(file); onImported(); showToast(`${result.imported} transaction${result.imported === 1 ? '' : 's'} imported`); onClose(); } catch (e: any) { setError(e?.message || 'Financial Excel import failed'); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-[70] bg-black/60 flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-labelledby="excel-finance-title">
    <div className="w-full max-w-3xl max-h-[90vh] overflow-auto bg-surface border border-border rounded-lg shadow-2xl">
      <div className="flex items-start justify-between gap-4 px-5 py-4 border-b border-border"><div><div className="text-[11px] uppercase tracking-[0.16em] text-accent">Excel workflow</div><h2 id="excel-finance-title" className="text-lg font-semibold mt-1">Financial transactions via Excel</h2><p className="mt-1 text-sm text-text-secondary">Work in Excel, validate the whole workbook, then import the transactions safely.</p></div><button type="button" onClick={onClose} className="p-2 text-text-secondary hover:text-text-primary hover:bg-surface-raised rounded-sm" aria-label="Close"><X size={18}/></button></div>
      <div className="p-5 space-y-5">
        <div className="grid grid-cols-2 gap-3"><button type="button" onClick={async () => { try { saveBlob(await downloadFinanceTemplate(), 'LabOS-Financial-Transactions-Template.xlsx'); } catch (e: any) { showToast(e?.message || 'Unable to download template', 'error'); } }} className="flex items-center gap-3 p-4 border border-border rounded-md hover:border-accent hover:bg-surface-raised text-left"><span className="p-2 rounded-sm bg-accent/10 text-accent"><Download size={18}/></span><span><strong className="block text-sm">Download template</strong><span className="text-xs text-text-secondary">Fill the Transactions sheet in Excel.</span></span></button><button type="button" onClick={() => input.current?.click()} className="flex items-center gap-3 p-4 border border-border rounded-md hover:border-accent hover:bg-surface-raised text-left"><span className="p-2 rounded-sm bg-accent/10 text-accent"><Upload size={18}/></span><span><strong className="block text-sm">Choose workbook</strong><span className="text-xs text-text-secondary">Upload a LabOS .xlsx workbook.</span></span></button></div>
        <input ref={input} type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" className="hidden" onChange={e => choose(e.target.files?.[0] || null)} />
        {file && <div className="flex items-center justify-between gap-3 p-3 border border-border bg-surface-raised rounded-md"><div className="flex items-center gap-3 min-w-0"><FileSpreadsheet size={20} className="text-accent shrink-0"/><div className="min-w-0"><div className="text-sm font-medium truncate">{file.name}</div><div className="text-xs text-text-secondary">Ready for validation</div></div></div><button type="button" onClick={() => choose(null)} className="p-1.5 text-text-secondary hover:text-text-primary" aria-label="Remove file"><X size={16}/></button></div>}
        {error && <div className="flex gap-2 p-3 border border-status-danger/30 bg-status-danger/5 rounded-md text-sm text-status-danger"><AlertTriangle size={17} className="shrink-0"/>{error}</div>}
        {preview && <div className="space-y-3"><div className="grid grid-cols-4 gap-2">{[['Rows',preview.total_rows],['Ready',preview.ready_rows],['Create',preview.creates],['Update',preview.updates]].map(([label,value]) => <div key={String(label)} className="p-3 border border-border rounded-md"><div className="text-xs text-text-secondary">{label}</div><div className="mt-1 text-lg font-semibold font-mono">{value}</div></div>)}</div>{preview.error_rows ? <div className="flex gap-2 p-3 border border-status-warning/30 bg-status-warning/5 rounded-md text-sm"><AlertTriangle size={17} className="text-status-warning shrink-0"/><div><strong>{preview.error_rows} row{preview.error_rows === 1 ? '' : 's'} need attention.</strong><ul className="mt-1 text-text-secondary">{preview.errors.slice(0, 6).map(e => <li key={e.row}>Row {e.row}: {e.errors.join(', ')}</li>)}</ul></div></div> : <div className="flex gap-2 p-3 border border-status-success/30 bg-status-success/5 rounded-md text-sm"><CheckCircle2 size={17} className="text-status-success shrink-0"/>All rows passed validation. No changes are made until you import.</div>}</div>}
      </div>
      <div className="flex justify-end gap-2 px-5 py-4 border-t border-border bg-surface-raised"><button type="button" onClick={onClose} className="px-3.5 py-2 border border-border rounded-sm text-sm">Cancel</button><button type="button" onClick={validate} disabled={!file || busy} className="px-3.5 py-2 border border-accent text-accent rounded-sm text-sm disabled:opacity-50">{busy && !preview && <Loader2 size={15} className="inline mr-2 animate-spin"/>}Validate workbook</button><button type="button" onClick={importFile} disabled={!preview || preview.error_rows > 0 || busy} className="px-3.5 py-2 bg-accent text-bg rounded-sm text-sm disabled:opacity-50">{busy && preview && <Loader2 size={15} className="inline mr-2 animate-spin"/>}Import transactions</button></div>
    </div>
  </div>;
}
