import { useEffect, useRef, useState } from 'react';
import { ListMusic, Pause, Play, SkipBack, SkipForward, Trash2, Upload, Volume2, X, Minimize2 } from 'lucide-react';
import { useToast } from '../contexts/ToastContext';

type Track={id:string;name:string;blob:Blob};
const DB='labos-local-media'; const STORE='tracks';
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function allTracks():Promise<Track[]>{const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function putTrack(t:Track){const db=await openDb();return new Promise<void>((resolve,reject)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(t);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);});}
async function removeTrack(id:string){const db=await openDb();return new Promise<void>((resolve,reject)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);});}
interface Props{open:boolean;onClose:()=>void;minimized:boolean;onMinimize:()=>void;onRestore:()=>void;autoPause:boolean;}
export default function MusicPlayer({open,onClose,minimized,onMinimize,onRestore,autoPause}:Props){const {showToast}=useToast();const audio=useRef<HTMLAudioElement|null>(null);const urls=useRef<Map<string,string>>(new Map());const [tracks,setTracks]=useState<Track[]>([]);const [index,setIndex]=useState(0);const [playing,setPlaying]=useState(false);const [volume,setVolume]=useState(.65);const resumeAfterPause=useRef(false);
const current=tracks[index]; const src=current? (urls.current.get(current.id)||(urls.current.set(current.id,URL.createObjectURL(current.blob)),urls.current.get(current.id)!)) : '';
useEffect(()=>{allTracks().then(setTracks).catch(()=>showToast('Local media storage is unavailable','error'));},[]);
useEffect(()=>{const pause=()=>{if(autoPause&&audio.current&&!audio.current.paused){resumeAfterPause.current=true;audio.current.pause();setPlaying(false);}};const resume=()=>{if(resumeAfterPause.current&&audio.current&&current){resumeAfterPause.current=false;audio.current.play().then(()=>setPlaying(true)).catch(()=>undefined);}};window.addEventListener('labos:pause-music',pause);window.addEventListener('labos:resume-music',resume);return()=>{window.removeEventListener('labos:pause-music',pause);window.removeEventListener('labos:resume-music',resume);};},[autoPause,current]);
useEffect(()=>()=>{urls.current.forEach(URL.revokeObjectURL);},[]);
useEffect(()=>{if(!audio.current)return;audio.current.volume=volume; if(src){audio.current.src=src; if(playing)audio.current.play().catch(()=>setPlaying(false));}},[src,volume]);
if(!open)return null;
if(minimized)return <button onClick={onRestore} className="fixed bottom-5 right-5 z-[75] bg-surface border border-border shadow-xl rounded-full px-4 py-3 flex items-center gap-2 text-sm" title="Restore music player"><ListMusic size={17}/>Music{playing?' · Playing':''}</button>;
const addFiles=async(e:React.ChangeEvent<HTMLInputElement>)=>{for(const file of Array.from(e.target.files||[])){const t={id:crypto.randomUUID(),name:file.name,blob:file};await putTrack(t);}setTracks(await allTracks());e.target.value='';};
const toggle=async()=>{if(!audio.current||!current)return;if(playing){audio.current.pause();setPlaying(false);}else{await audio.current.play().catch(()=>showToast('Unable to play this track','error'));setPlaying(true);}};
const remove=async(id:string)=>{await removeTrack(id);urls.current.delete(id);setTracks(await allTracks());setIndex(Math.min(index,Math.max(0,tracks.length-2)));};
return <div className="fixed z-[75] right-6 bottom-6 w-[min(440px,calc(100vw-2rem))] bg-surface border border-border rounded-md shadow-2xl overflow-hidden"><div className="flex items-center justify-between px-4 py-3 border-b border-border"><div><div className="text-xs text-text-secondary">LOCAL MEDIA</div><div className="font-semibold text-sm">Music Player</div></div><div className="flex gap-1"><button onClick={onMinimize} className="p-1.5 hover:bg-surface-raised rounded" title="Minimize"><Minimize2 size={15}/></button><button onClick={onClose} className="p-1.5 hover:bg-surface-raised rounded" title="Close"><X size={15}/></button></div></div><div className="p-4 space-y-4"><div className="text-sm truncate">{current?.name||'No local tracks loaded'}</div><audio ref={audio} onEnded={()=>{if(index<tracks.length-1)setIndex(i=>i+1);else setPlaying(false);}}/><div className="flex items-center justify-center gap-4"><button disabled={!tracks.length} onClick={()=>setIndex(i=>Math.max(0,i-1))}><SkipBack size={18}/></button><button disabled={!current} onClick={toggle} className="w-10 h-10 rounded-full bg-accent text-bg flex items-center justify-center">{playing?<Pause size={18}/>:<Play size={18}/>}</button><button disabled={!tracks.length} onClick={()=>setIndex(i=>Math.min(tracks.length-1,i+1))}><SkipForward size={18}/></button></div><div className="flex items-center gap-2"><Volume2 size={15}/><input className="flex-1" type="range" min="0" max="1" step=".01" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></div><label className="inline-flex items-center gap-2 text-xs text-text-secondary cursor-pointer"><Upload size={14}/>Add local audio<input type="file" accept="audio/*" multiple className="hidden" onChange={addFiles}/></label><div className="max-h-36 overflow-auto space-y-1">{tracks.map((t,i)=><div key={t.id} className={`flex items-center gap-2 px-2 py-1.5 rounded ${i===index?'bg-accent/10':''}`}><button onClick={()=>{setIndex(i);setPlaying(false)}} className="flex-1 text-left text-xs truncate">{t.name}</button><button onClick={()=>remove(t.id)} title="Remove local track"><Trash2 size={13}/></button></div>)}</div><div className="text-[10px] text-text-secondary">Music files stay in this device's local browser storage and are never sent to LabOS.</div></div></div>;
}
