import { Router } from 'express';
import { pool } from '../db.js';
import { writeAuditLog } from '../middleware/audit.js';
const router=Router();
async function canProject(projectId, req){if(!projectId)return true;const r=await pool.query(`SELECT 1 FROM projects p LEFT JOIN project_members pm ON pm.project_id=p.id WHERE p.id=$1 AND ($2='admin' OR p.owner_id=$3 OR pm.user_id=$3)`,[projectId,req.user.role,req.user.userId]);return r.rowCount>0;}
router.get('/formulas',async(req,res)=>{try{const r=await pool.query('SELECT * FROM engineering_formulas ORDER BY category,name');res.json(r.rows);}catch(e){res.status(500).json({error:'Failed to load formulas'});}});
router.post('/calculate',async(req,res)=>{const {formula,inputs={}}=req.body||{};const n=k=>Number(inputs[k]);let result=null,unit='';if(formula==='ohms_law'&&Number.isFinite(n('current_A'))&&Number.isFinite(n('resistance_ohm'))) {result=n('current_A')*n('resistance_ohm');unit='V';}else if(formula==='power_vi'&&Number.isFinite(n('voltage_V'))&&Number.isFinite(n('current_A'))){result=n('voltage_V')*n('current_A');unit='W';}else if(formula==='voltage_divider'&&Number.isFinite(n('vin_V'))&&Number.isFinite(n('r1_ohm'))&&Number.isFinite(n('r2_ohm'))&&n('r1_ohm')+n('r2_ohm')!==0){result=n('vin_V')*n('r2_ohm')/(n('r1_ohm')+n('r2_ohm'));unit='V';}else if(formula==='led_resistor'&&Number.isFinite(n('supply_V'))&&Number.isFinite(n('forward_V'))&&Number.isFinite(n('current_A'))&&n('current_A')>0){result=(n('supply_V')-n('forward_V'))/n('current_A');unit='ohm';}else return res.status(400).json({error:'Unsupported formula or incomplete inputs'});res.json({formula,inputs,result_numeric:result,result_unit:unit});});
router.get('/calculations',async(req,res)=>{try{const r=await pool.query(`SELECT c.*,u.username AS creator_username FROM engineering_calculations c LEFT JOIN users u ON u.id=c.created_by WHERE ($1='admin' OR c.project_id IS NULL OR c.project_id IN (SELECT p.id FROM projects p LEFT JOIN project_members pm ON pm.project_id=p.id WHERE p.owner_id=$2 OR pm.user_id=$2)) ORDER BY c.created_at DESC LIMIT 300`,[req.user.role,req.user.userId]);res.json(r.rows);}catch(e){res.status(500).json({error:'Failed to fetch calculations'});}});
router.post('/calculations',async(req,res)=>{const {project_id=null,experiment_id=null,title,category='general',formula,inputs={},result_numeric=null,result_text=null,result_unit=''}=req.body||{};if(!String(title||'').trim()||!String(formula||'').trim())return res.status(400).json({error:'title and formula are required'});try{if(!(await canProject(project_id,req)))return res.status(403).json({error:'Project access denied'});const r=await pool.query(`INSERT INTO engineering_calculations(project_id,experiment_id,title,category,formula,inputs,result_numeric,result_text,result_unit,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[project_id,experiment_id,String(title).trim(),category,formula,inputs,result_numeric,result_text,result_unit,req.user.userId]);await writeAuditLog({req,action:'CREATE',entityType:'engineering_calculation',entityId:r.rows[0].id,newValue:r.rows[0],metadata:{project_id}});res.status(201).json(r.rows[0]);}catch(e){console.error(e);res.status(500).json({error:'Failed to save calculation'});}});
router.delete('/calculations/:id',async(req,res)=>{try{const b=await pool.query('SELECT * FROM engineering_calculations WHERE id=$1',[req.params.id]);if(!b.rowCount)return res.status(404).json({error:'Calculation not found'});if(!(await canProject(b.rows[0].project_id,req)))return res.status(403).json({error:'Project access denied'});await pool.query('DELETE FROM engineering_calculations WHERE id=$1',[req.params.id]);res.status(204).send();}catch(e){res.status(500).json({error:'Failed to delete calculation'});}});
router.get('/tests',async(req,res)=>{try{const r=await pool.query(`SELECT t.*,u.username AS performer_username FROM engineering_tests t LEFT JOIN users u ON u.id=t.performed_by WHERE ($1='admin' OR t.project_id IS NULL OR t.project_id IN (SELECT p.id FROM projects p LEFT JOIN project_members pm ON pm.project_id=p.id WHERE p.owner_id=$2 OR pm.user_id=$2)) ORDER BY t.updated_at DESC LIMIT 300`,[req.user.role,req.user.userId]);res.json(r.rows);}catch(e){res.status(500).json({error:'Failed to fetch engineering tests'});}});
router.post('/tests',async(req,res)=>{const {project_id=null,title,test_type='engineering',description='',status='planned',inputs={},results={},conclusion='',performed_by=null}=req.body||{};if(!String(title||'').trim())return res.status(400).json({error:'title is required'});try{if(!(await canProject(project_id,req)))return res.status(403).json({error:'Project access denied'});const r=await pool.query(`INSERT INTO engineering_tests(project_id,title,test_type,description,status,inputs,results,conclusion,performed_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[project_id,String(title).trim(),test_type,description,status,inputs,results,conclusion,performed_by||req.user.userId]);res.status(201).json(r.rows[0]);}catch(e){res.status(500).json({error:'Failed to create engineering test'});}});
router.patch('/tests/:id',async(req,res)=>{const allowed=['title','test_type','description','status','inputs','results','conclusion','performed_by'];const keys=allowed.filter(k=>k in (req.body||{}));if(!keys.length)return res.status(400).json({error:'No valid fields to update'});try{const b=await pool.query('SELECT * FROM engineering_tests WHERE id=$1',[req.params.id]);if(!b.rowCount)return res.status(404).json({error:'Engineering test not found'});if(!(await canProject(b.rows[0].project_id,req)))return res.status(403).json({error:'Project access denied'});const vals=keys.map(k=>req.body[k]);vals.push(req.params.id);const r=await pool.query(`UPDATE engineering_tests SET ${keys.map((k,i)=>`${k}=$${i+1}`).join(',')} WHERE id=$${keys.length+1} RETURNING *`,vals);res.json(r.rows[0]);}catch(e){res.status(500).json({error:'Failed to update engineering test'});}});
router.delete('/tests/:id',async(req,res)=>{try{const b=await pool.query('SELECT * FROM engineering_tests WHERE id=$1',[req.params.id]);if(!b.rowCount)return res.status(404).json({error:'Engineering test not found'});if(!(await canProject(b.rows[0].project_id,req)))return res.status(403).json({error:'Project access denied'});await pool.query('DELETE FROM engineering_tests WHERE id=$1',[req.params.id]);res.status(204).send();}catch(e){res.status(500).json({error:'Failed to delete engineering test'});}});
router.get('/compare',async(req,res)=>{try{const ids=String(req.query.ids||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,20);if(!ids.length)return res.json([]);const r=await pool.query(`SELECT id,title,category,formula,inputs,result_numeric,result_text,result_unit,project_id,experiment_id,created_at FROM engineering_calculations WHERE id=ANY($1::uuid[]) ORDER BY created_at`,[ids]);res.json(r.rows);}catch(e){res.status(500).json({error:'Failed to compare calculations'});}});
export default router;
