import { Router } from 'express';
import multer from 'multer';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import jwt from 'jsonwebtoken';
import { config } from '../config.js';
import { pool } from '../db.js';
import { writeAuditLog } from '../middleware/audit.js';
import { getProjectAccess } from '../middleware/project-access.js';
import { getUserPermissions } from '../middleware/permissions.js';
import { getResourceAccess, getResourceContext, requireResourceRead, requireResourceEditor, validateResourceParent } from '../middleware/resource-access.js';
import { canManageEntityGrants, isVisibility } from '../middleware/visibility.js';
import { STORAGE_DIR, inferFileType, resolveStoragePath, sanitizeRelativePath } from '../storage.js';

const router = Router();
const TMP_DIR = path.join(STORAGE_DIR, '_incoming');
if (!fs.existsSync(TMP_DIR)) fs.mkdirSync(TMP_DIR, { recursive: true });
const upload = multer({ storage: multer.diskStorage({ destination: TMP_DIR, filename: (req, file, cb) => cb(null, `${Date.now()}-${randomUUID()}-${path.basename(file.originalname)}`) }), limits: { fileSize: config.maxUploadMb * 1024 * 1024, files: 100 } });
function parentFields(body) { return { item_id: body.item_id || null, project_id: body.project_id || null, note_id: body.note_id || null, parent_resource_id: body.parent_resource_id || null }; }
function resourceLinkLockKey(url,{item_id=null,project_id=null,note_id=null,parent_resource_id=null}={}) { return ['link',String(url||'').trim().replace(/\/+$/,'').toLowerCase(),item_id||'',project_id||'',note_id||'',parent_resource_id||''].join('|'); }
async function lockResourceLink(client,url,scope={}) { await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[resourceLinkLockKey(url,scope)]); }
function validateAtMostOneParent({ item_id, project_id, note_id, parent_resource_id }) { return [item_id, project_id, note_id, parent_resource_id].filter(Boolean).length <= 1; }
const KNOWLEDGE_CATEGORIES = new Set(['general','datasheet','manual','schematic','research','tutorial','reference','specification','image','cad','report','video','other']);
function knowledgeMetadata(body) { const category = typeof body.category === 'string' && KNOWLEDGE_CATEGORIES.has(body.category) ? body.category : 'general'; const rawTags = Array.isArray(body.tags) ? body.tags : (typeof body.tags === 'string' ? (() => { try { return JSON.parse(body.tags); } catch { return body.tags.split(','); } })() : []); const tags = Array.isArray(rawTags) ? rawTags.map(v => String(v).trim()).filter(Boolean).slice(0, 30) : []; return { category, description: typeof body.description === 'string' ? body.description.trim().slice(0, 5000) : '', tags }; }
router.get('/', async (req, res) => { const { item_id, project_id, note_id, parent_resource_id } = req.query; const conditions = []; const values = []; if (item_id) { values.push(item_id); conditions.push(`r.item_id = $${values.length}`); conditions.push(`r.id IS DISTINCT FROM (SELECT image_resource_id FROM items WHERE id = $${values.length})`); } if (project_id) { values.push(project_id); conditions.push(`r.project_id = $${values.length}`); } if (note_id) { values.push(note_id); conditions.push(`r.note_id = $${values.length}`); } if (parent_resource_id) { values.push(parent_resource_id); conditions.push(`r.parent_resource_id = $${values.length}`); } const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : `WHERE r.parent_resource_id IS NULL`; try { if (project_id) { const access = await getProjectAccess(project_id, req.user); if (access.access === 'none') return res.status(403).json({ error: { code: 'PROJECT_ACCESS_REQUIRED', message: 'You do not have access to this project' } }); } if (note_id) { const parentCheck = await validateResourceParent({ noteId: note_id, user: req.user, requireEdit: false }); if (!parentCheck.ok) return res.status(parentCheck.status).json({ error: parentCheck.error }); } if (item_id) { const parentCheck = await validateResourceParent({ itemId: item_id, user: req.user, requireEdit: false }); if (!parentCheck.ok) return res.status(parentCheck.status).json({ error: parentCheck.error }); } if (parent_resource_id) { const parentCheck = await validateResourceParent({ parentResourceId: parent_resource_id, user: req.user, requireEdit: false }); if (!parentCheck.ok) return res.status(parentCheck.status).json({ error: parentCheck.error }); } const result = await pool.query(`SELECT r.id, r.name, r.kind, r.file_type, r.original_filename, r.mime_type, r.size_bytes, r.parent_resource_id, r.relative_path, r.url, r.thumbnail_url, r.category, r.description, r.tags, r.visibility, r.updated_at, r.created_at, r.item_id, r.project_id, r.note_id, i.name AS item_name, p.name AS project_name, n.title AS note_title FROM resources r LEFT JOIN items i ON r.item_id = i.id LEFT JOIN projects p ON r.project_id = p.id LEFT JOIN notes n ON r.note_id = n.id ${where} ORDER BY r.created_at DESC`, values); const visible = []; for (const row of result.rows) { const access = await getResourceAccess(row.id, req.user); if (access.access !== 'none' && !access.context?.invalid) visible.push(row); } res.json(visible); } catch (err) { console.error(err); res.status(500).json({ error: err.message || 'Failed to fetch resources' }); } });
router.get('/:id/access-url', async (req, res) => { try { const result = await pool.query('SELECT id, kind FROM resources WHERE id = $1', [req.params.id]); if (!result.rowCount) return res.status(404).json({ error: 'Resource not found' }); const access = await requireResourceRead(req.params.id, req.user); if (!access.ok) return res.status(access.status).json({ error: access.error }); if (result.rows[0].kind !== 'file') return res.status(400).json({ error: 'Only file resources have access URLs' }); const accessToken = jwt.sign({ purpose: 'resource-download', resourceId: req.params.id, userId: req.user.userId }, config.jwtSecret, { expiresIn: '5m' }); res.json({ url: `${req.protocol}://${req.get('host')}/api/resources/${req.params.id}/download?access_token=${encodeURIComponent(accessToken)}` }); } catch (err) { console.error(err); res.status(500).json({ error: 'Failed to create resource access URL' }); } });
router.get('/:id', async (req, res) => { try { const result = await pool.query('SELECT id, name, kind, file_type, original_filename, mime_type, size_bytes, parent_resource_id, relative_path, url, thumbnail_url, category, description, tags, visibility, updated_at, item_id, project_id, note_id, created_at FROM resources WHERE id = $1', [req.params.id]); if (!result.rowCount) return res.status(404).json({ error: 'Resource not found' }); const access = await requireResourceRead(req.params.id, req.user); if (!access.ok) return res.status(access.status).json({ error: access.error }); res.json(result.rows[0]); } catch (err) { console.error(err); res.status(500).json({ error: err.message || 'Failed to fetch resource' }); } });
router.get('/:id/manifest', async (req, res) => { try { const folder = await pool.query(`SELECT * FROM resources WHERE id = $1 AND kind = 'folder'`, [req.params.id]); if (folder.rows.length === 0) return res.status(404).json({ error: 'Folder resource not found' }); const access = await requireResourceRead(req.params.id, req.user); if (!access.ok) return res.status(access.status).json({ error: access.error }); const children = await pool.query(`SELECT id, relative_path, original_filename, size_bytes, mime_type FROM resources WHERE parent_resource_id = $1 ORDER BY relative_path ASC`, [req.params.id]); res.json({ folder: folder.rows[0].name, files: children.rows }); } catch (err) { console.error(err); res.status(500).json({ error: err.message || 'Failed to build manifest' }); } });
router.get('/:id/download', async (req, res) => { try { const result = await pool.query(`SELECT * FROM resources WHERE id = $1`, [req.params.id]); if (result.rows.length === 0) return res.status(404).json({ error: 'Resource not found' }); const resource = result.rows[0]; const access = await requireResourceRead(req.params.id, req.user); if (!access.ok) return res.status(access.status).json({ error: access.error }); if (req.user?.purpose === 'resource-download' && req.user.resourceId !== resource.id) return res.status(403).json({ error: 'Resource access token does not match this resource' }); if (resource.kind !== 'file') return res.status(400).json({ error: 'Only file resources can be downloaded directly — use /manifest for folders' }); const filePath = resolveStoragePath(resource.storage_path); const stat = await fsp.stat(filePath); const range = req.headers.range; const viewableInline = ['image', 'video', 'audio', 'pdf', 'text'].includes(resource.file_type); const forceDownload = req.query.download === 'true'; const disposition = viewableInline && !forceDownload ? 'inline' : 'attachment'; res.setHeader('Content-Type', resource.mime_type || 'application/octet-stream'); res.setHeader('Content-Disposition', `${disposition}; filename="${encodeURIComponent(resource.original_filename || resource.name)}"`); if (range) { const [startStr, endStr] = range.replace(/bytes=/, '').split('-'); const start = parseInt(startStr, 10); const end = endStr ? parseInt(endStr, 10) : stat.size - 1; res.writeHead(206, { 'Content-Range': `bytes ${start}-${end}/${stat.size}`, 'Accept-Ranges': 'bytes', 'Content-Length': end - start + 1 }); fs.createReadStream(filePath, { start, end }).pipe(res); } else { res.setHeader('Content-Length', stat.size); fs.createReadStream(filePath).pipe(res); } } catch (err) { console.error(err); res.status(500).json({ error: err.message || 'Failed to download resource' }); } });
router.post('/', upload.single('file'), async (req, res) => { if (!req.file) return res.status(400).json({ error: 'No file uploaded (expected multipart field "file")' }); const parents = parentFields(req.body); if (!validateAtMostOneParent(parents)) { await fsp.unlink(req.file.path).catch(() => {}); return res.status(400).json({ error: 'A resource can be attached to at most one of item_id, project_id, note_id' }); } const parentCheck = await validateResourceParent({ itemId: parents.item_id, projectId: parents.project_id, noteId: parents.note_id, user: req.user }); if (!parentCheck.ok) { await fsp.unlink(req.file.path).catch(() => {}); return res.status(parentCheck.status).json({ error: parentCheck.error }); } const client = await pool.connect(); let resourceId = null; let finalPath = null; try { const fileType = inferFileType(req.file.mimetype, req.file.originalname); const metadata = knowledgeMetadata(req.body); await client.query('BEGIN'); const inserted = await client.query(`INSERT INTO resources (name, kind, file_type, original_filename, mime_type, size_bytes, item_id, project_id, note_id, category, description, tags, uploaded_by) VALUES ($1,'file',$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`, [req.body.name || req.file.originalname, fileType, req.file.originalname, req.file.mimetype, req.file.size, parents.item_id, parents.project_id, parents.note_id, metadata.category, metadata.description, metadata.tags, req.user?.userId || null]); const resource = inserted.rows[0]; resourceId = resource.id; const safeFilename = sanitizeRelativePath(path.basename(req.file.originalname)); const finalDir = resolveStoragePath(resource.id); await fsp.mkdir(finalDir, { recursive: true }); finalPath = resolveStoragePath(`${resource.id}/${safeFilename}`); await fsp.rename(req.file.path, finalPath); const relativeStoragePath = `${resource.id}/${safeFilename}`; const updated = await client.query(`UPDATE resources SET storage_path = $1 WHERE id = $2 RETURNING *`, [relativeStoragePath, resource.id]); await client.query('COMMIT'); client.release(); await writeAuditLog({ req, action: 'CREATE', entityType: 'resource', entityId: updated.rows[0].id, newValue: updated.rows[0] }); res.status(201).json(updated.rows[0]); } catch (err) { console.error(err); await client.query('ROLLBACK').catch(() => {}); client.release(); await fsp.unlink(req.file.path).catch(() => {}); if (finalPath) await fsp.unlink(finalPath).catch(() => {}); if (resourceId) await fsp.rm(resolveStoragePath(resourceId), { recursive: true, force: true }).catch(() => {}); res.status(500).json({ error: err.message || 'Failed to upload file' }); } });
router.post('/folder', async (req, res) => { const parents = parentFields(req.body); if (!req.body.name || !validateAtMostOneParent(parents)) return res.status(400).json({ error: 'name is required, and a resource can be attached to at most one of item_id/project_id/note_id' }); const parentCheck = await validateResourceParent({ itemId: parents.item_id, projectId: parents.project_id, noteId: parents.note_id, user: req.user }); if (!parentCheck.ok) return res.status(parentCheck.status).json({ error: parentCheck.error }); try { const metadata = knowledgeMetadata(req.body); const result = await pool.query(`INSERT INTO resources (name, kind, file_type, item_id, project_id, note_id, category, description, tags, uploaded_by) VALUES ($1,'folder','schematic_folder',$2,$3,$4,$5,$6,$7,$8) RETURNING *`, [req.body.name, parents.item_id, parents.project_id, parents.note_id, metadata.category, metadata.description, metadata.tags, req.user?.userId || null]); await writeAuditLog({ req, action: 'CREATE', entityType: 'resource', entityId: result.rows[0].id, newValue: result.rows[0] }); res.status(201).json(result.rows[0]); } catch (err) { console.error(err); res.status(500).json({ error: err.message || 'Failed to create folder' }); } });
router.post('/:folderId/files', upload.array('files'), async (req, res) => { const { folderId } = req.params; try { const folder = await pool.query(`SELECT * FROM resources WHERE id = $1 AND kind = 'folder'`, [folderId]); if (!folder.rowCount) return res.status(404).json({ error: 'Folder resource not found' }); const folderAccess = await requireResourceEditor(folderId, req.user); if (!folderAccess.ok) { for (const file of req.files || []) await fsp.unlink(file.path).catch(() => {}); return res.status(folderAccess.status).json({ error: folderAccess.error }); } let relativePaths; try { relativePaths = JSON.parse(req.body.relative_paths || '[]'); } catch { relativePaths = []; } const created=[]; const finalPaths=[]; const seenPaths=new Set(); const client=await pool.connect(); try { await client.query('BEGIN'); for (let i=0;i<req.files.length;i++){const file=req.files[i];const relPath=sanitizeRelativePath(relativePaths[i]||file.originalname);const normalizedRelPath=relPath.replaceAll('\\\\','/');if(seenPaths.has(normalizedRelPath))throw new Error(`Duplicate relative path in upload: ${relPath}`);seenPaths.add(normalizedRelPath);const fileType=inferFileType(file.mimetype,file.originalname);const inserted=await client.query(`INSERT INTO resources (name, kind, file_type, original_filename, mime_type, size_bytes, parent_resource_id, relative_path, uploaded_by) VALUES ($1,'file',$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[path.basename(relPath),fileType,file.originalname,file.mimetype,file.size,folderId,relPath,req.user?.userId||null]);const resource=inserted.rows[0];const finalPath=resolveStoragePath(`${folderId}/${relPath}`);await fsp.mkdir(path.dirname(finalPath),{recursive:true});await fsp.rename(file.path,finalPath);finalPaths.push(finalPath);const updated=await client.query(`UPDATE resources SET storage_path=$1 WHERE id=$2 RETURNING *`,[`${folderId}/${relPath}`,resource.id]);created.push(updated.rows[0]);} await client.query('COMMIT');client.release();for(const row of created)await writeAuditLog({req,action:'CREATE',entityType:'resource',entityId:row.id,newValue:row});res.status(201).json(created);}catch(err){await client.query('ROLLBACK').catch(()=>{});client.release();for(const file of req.files||[])await fsp.unlink(file.path).catch(()=>{});for(const finalPath of finalPaths)await fsp.unlink(finalPath).catch(()=>{});throw err;}}catch(err){console.error(err);res.status(500).json({error:err.message||'Failed to upload folder contents'});} });
router.post('/link', async (req, res) => { const parents=parentFields(req.body); const {url,name}=req.body; if(!url||!validateAtMostOneParent(parents))return res.status(400).json({error:'url is required, and a resource can be attached to at most one of item_id, project_id, note_id, or parent_resource_id'}); const normalizedUrl=String(url).trim().replace(/\/+$/,''); const parentCheck=await validateResourceParent({itemId:parents.item_id,projectId:parents.project_id,noteId:parents.note_id,parentResourceId:parents.parent_resource_id,user:req.user});if(!parentCheck.ok)return res.status(parentCheck.status).json({error:parentCheck.error}); const isYouTube=/(?:youtube\\.com|youtu\\.be)/.test(normalizedUrl);let thumbnailUrl=null;let resolvedName=name;if(isYouTube){try{const oembedRes=await fetch(`https://www.youtube.com/oembed?url=${encodeURIComponent(normalizedUrl)}&format=json`);if(oembedRes.ok){const data=await oembedRes.json();thumbnailUrl=data.thumbnail_url||null;resolvedName=resolvedName||data.title;}}catch(err){console.warn('Could not fetch YouTube oEmbed data:',err.message);}} const client=await pool.connect(); try{await client.query('BEGIN'); await lockResourceLink(client,normalizedUrl,parents); const duplicate=await client.query('SELECT * FROM resources WHERE kind=\'link\' AND lower(btrim(url))=lower($1) AND item_id IS NOT DISTINCT FROM $2 AND project_id IS NOT DISTINCT FROM $3 AND note_id IS NOT DISTINCT FROM $4 AND parent_resource_id IS NOT DISTINCT FROM $5 ORDER BY (local_media_path IS NOT NULL) DESC, created_at ASC LIMIT 1',[normalizedUrl,parents.item_id||null,parents.project_id||null,parents.note_id||null,parents.parent_resource_id||null]); if(duplicate.rowCount){await client.query('COMMIT');client.release();return res.status(200).json(duplicate.rows[0]);} const metadata=knowledgeMetadata(req.body); const result=await client.query(`INSERT INTO resources (name, kind, file_type, url, thumbnail_url, item_id, project_id, note_id, parent_resource_id, category, description, tags, uploaded_by) VALUES ($1,'link',$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[resolvedName||normalizedUrl,isYouTube?'youtube':'other',normalizedUrl,thumbnailUrl,parents.item_id,parents.project_id,parents.note_id,parents.parent_resource_id,metadata.category,metadata.description,metadata.tags,req.user?.userId||null]); await client.query('COMMIT'); client.release(); await writeAuditLog({req,action:'CREATE',entityType:'resource',entityId:result.rows[0].id,newValue:result.rows[0]}); res.status(201).json(result.rows[0]); }catch(err){await client.query('ROLLBACK').catch(()=>{});client.release();console.error(err);res.status(500).json({error:err.message||'Failed to create link resource'});} });
router.put('/:id', async (req,res)=>{const metadata=knowledgeMetadata(req.body);try{const access=await requireResourceEditor(req.params.id,req.user);if(!access.ok)return res.status(access.status).json({error:access.error});const result=await pool.query(`UPDATE resources SET category=$1,description=$2,tags=$3 WHERE id=$4 RETURNING *`,[metadata.category,metadata.description,metadata.tags,req.params.id]);if(!result.rowCount)return res.status(404).json({error:'Resource not found'});await writeAuditLog({req,action:'UPDATE',entityType:'resource',entityId:req.params.id,newValue:result.rows[0]});res.json(result.rows[0]);}catch(err){console.error(err);res.status(500).json({error:'Failed to update resource metadata'});} });
router.put('/:id/visibility', async (req,res)=>{
 const visibility=req.body?.visibility;
 if(!isVisibility(visibility))return res.status(400).json({error:'visibility must be lab, project, or restricted'});
 const access=await requireResourceEditor(req.params.id,req.user);
 if(!access.ok)return res.status(access.status).json({error:access.error});
 if(visibility==='project'&&!access.context?.projectId)return res.status(400).json({error:'project visibility requires a project-owned parent'});
 const client=await pool.connect();
 try{
  await client.query('BEGIN');
  const current=await client.query('SELECT * FROM resources WHERE id=$1 FOR UPDATE',[req.params.id]);
  if(!current.rowCount){await client.query('ROLLBACK');return res.status(404).json({error:'Resource not found'});}
  const updated=await client.query('UPDATE resources SET visibility=$1,updated_at=now() WHERE id=$2 RETURNING *',[visibility,req.params.id]);
  if(current.rows[0].visibility!==visibility&&visibility==='restricted')await client.query("INSERT INTO record_access_grants(entity_type,entity_id,user_id,access_level,created_by) VALUES('resource',$1,$2,'edit',$2) ON CONFLICT(entity_type,entity_id,user_id) DO UPDATE SET access_level='edit'",[req.params.id,req.user.userId]);
  if(current.rows[0].visibility==='restricted'&&visibility!=='restricted')await client.query("DELETE FROM record_access_grants WHERE entity_type='resource' AND entity_id=$1",[req.params.id]);
  await client.query('COMMIT');
  await writeAuditLog({req,action:'UPDATE',entityType:'resource',entityId:req.params.id,oldValue:current.rows[0],newValue:updated.rows[0],metadata:{visibility_change:true}});
  res.json(updated.rows[0]);
 }catch(err){await client.query('ROLLBACK').catch(()=>{});console.error(err);res.status(500).json({error:'Failed to update resource visibility'});}finally{client.release();}
});

async function requireResourceGrantManager(resourceId,user){
 const permissions=await getUserPermissions(user.userId,user.role);
 if(!permissions.has('resources.edit'))return {ok:false,status:403,error:'Permission required: resources.edit'};
 const context=await getResourceContext(resourceId);
 if(!context)return {ok:false,status:404,error:'Resource not found'};
 if(context.invalid)return {ok:false,status:409,error:'Resource has conflicting project ownership'};
 if(context.resource.visibility!=='restricted')return {ok:false,status:409,error:'Access grants apply only to restricted resources'};
 if(!(await canManageEntityGrants({projectId:context.projectId,user})))return {ok:false,status:403,error:'Only an administrator or project lead can manage other users’ grants'};
 return {ok:true,context};
}

router.get('/:id/access-grants',async(req,res)=>{try{const access=await requireResourceGrantManager(req.params.id,req.user);if(!access.ok)return res.status(access.status).json({error:access.error});const result=await pool.query("SELECT g.user_id,g.access_level,g.created_at,g.created_by,u.username FROM record_access_grants g JOIN users u ON u.id=g.user_id WHERE g.entity_type='resource' AND g.entity_id=$1 ORDER BY u.username",[req.params.id]);res.json(result.rows);}catch(err){console.error(err);res.status(500).json({error:'Failed to load resource access grants'});}});
router.put('/:id/access-grants/:userId',async(req,res)=>{const accessLevel=req.body?.access_level;if(!['view','edit'].includes(accessLevel))return res.status(400).json({error:'access_level must be view or edit'});try{const access=await requireResourceGrantManager(req.params.id,req.user);if(!access.ok)return res.status(access.status).json({error:access.error});const target=await pool.query('SELECT id FROM users WHERE id=$1 AND is_active=TRUE',[req.params.userId]);if(!target.rowCount)return res.status(400).json({error:'userId must reference an active user'});const result=await pool.query("INSERT INTO record_access_grants(entity_type,entity_id,user_id,access_level,created_by) VALUES('resource',$1,$2,$3,$4) ON CONFLICT(entity_type,entity_id,user_id) DO UPDATE SET access_level=EXCLUDED.access_level,created_by=EXCLUDED.created_by RETURNING entity_type,entity_id,user_id,access_level,created_at,created_by",[req.params.id,req.params.userId,accessLevel,req.user.userId]);await writeAuditLog({req,action:'UPDATE',entityType:'resource_access_grant',entityId:req.params.id,newValue:result.rows[0],metadata:{resource_id:req.params.id,project_id:access.context.projectId}});res.json(result.rows[0]);}catch(err){console.error(err);res.status(500).json({error:'Failed to save resource access grant'});}});
router.delete('/:id/access-grants/:userId',async(req,res)=>{try{const access=await requireResourceGrantManager(req.params.id,req.user);if(!access.ok)return res.status(access.status).json({error:access.error});const removed=await pool.query("DELETE FROM record_access_grants WHERE entity_type='resource' AND entity_id=$1 AND user_id=$2 RETURNING user_id,access_level",[req.params.id,req.params.userId]);if(!removed.rowCount)return res.status(404).json({error:'Access grant not found'});await writeAuditLog({req,action:'DELETE',entityType:'resource_access_grant',entityId:req.params.id,oldValue:removed.rows[0],metadata:{resource_id:req.params.id,project_id:access.context.projectId}});res.status(204).send();}catch(err){console.error(err);res.status(500).json({error:'Failed to delete resource access grant'});}});
// Reassign an existing resource without re-uploading it. A resource has one direct parent.
router.put('/:id/attachment', async (req,res)=>{
 const permissions=await getUserPermissions(req.user.userId,req.user.role);
 if(!permissions.has('resources.edit'))return res.status(403).json({error:{code:'PERMISSION_DENIED',message:'Permission required: resources.edit'}});
 const parents=parentFields(req.body);
 if(!validateAtMostOneParent(parents))return res.status(400).json({error:'Choose only one attachment destination'});
 try{
  const existing=await pool.query('SELECT * FROM resources WHERE id=$1',[req.params.id]);
  if(!existing.rowCount)return res.status(404).json({error:'Resource not found'});
  const resource=existing.rows[0];
  if(resource.parent_resource_id)return res.status(409).json({error:'Nested resources must be moved using folder management'});
  const source=await requireResourceEditor(req.params.id,req.user);
  if(!source.ok)return res.status(source.status).json({error:source.error});
  const destination=await validateResourceParent({itemId:parents.item_id,projectId:parents.project_id,noteId:parents.note_id,user:req.user});
  if(!destination.ok)return res.status(destination.status).json({error:destination.error});
  const result=await pool.query('UPDATE resources SET item_id=$1,project_id=$2,note_id=$3,updated_at=now() WHERE id=$4 RETURNING *',[parents.item_id,parents.project_id,parents.note_id,req.params.id]);
  await writeAuditLog({req,action:'UPDATE',entityType:'resource',entityId:req.params.id,oldValue:resource,newValue:result.rows[0]});
  res.json(result.rows[0]);
 }catch(err){console.error(err);res.status(500).json({error:'Failed to update resource attachment'});}
});
async function visibleResourceFacetRows(user) {
  const result = await pool.query('SELECT id,category,tags FROM resources');
  const visible = [];
  // Facets must obey the same ancestor, attached-Note, and project rules as
  // the resource list. Keep concurrency bounded for large libraries.
  for (let offset = 0; offset < result.rows.length; offset += 16) {
    const batch = result.rows.slice(offset, offset + 16);
    const access = await Promise.all(batch.map(row => getResourceAccess(row.id, user)));
    for (let i = 0; i < batch.length; i++) {
      if (access[i].access !== 'none' && !access[i].context?.invalid) visible.push(batch[i]);
    }
  }
  return visible;
}
router.get('/meta/tags', async (req,res)=>{
  try {
    const rows = await visibleResourceFacetRows(req.user);
    res.json([...new Set(rows.flatMap(row => row.tags || []))].sort());
  } catch(err) {
    console.error(err);
    res.status(500).json({error:'Failed to fetch resource tags'});
  }
});
router.get('/meta/categories', async (req,res)=>{
  try {
    const rows = await visibleResourceFacetRows(req.user);
    const counts = new Map();
    for (const row of rows) counts.set(row.category, (counts.get(row.category) || 0) + 1);
    res.json([...counts].map(([category,count]) => ({category,count})).sort((a,b) =>
      a.category === null ? 1 : b.category === null ? -1 : String(a.category).localeCompare(String(b.category))));
  } catch(err) {
    console.error(err);
    res.status(500).json({error:'Failed to fetch resource categories'});
  }
});
router.delete('/:id', async (req,res)=>{const client=await pool.connect();try{const result=await client.query('SELECT * FROM resources WHERE id=$1',[req.params.id]);if(!result.rowCount)return res.status(404).json({error:'Resource not found'});const resource=result.rows[0];const access=await requireResourceEditor(req.params.id,req.user);if(!access.ok)return res.status(access.status).json({error:access.error});const descendants=await client.query(`WITH RECURSIVE tree AS (SELECT id,project_id,item_id,note_id FROM resources WHERE id=$1 UNION ALL SELECT r.id,r.project_id,r.item_id,r.note_id FROM resources r JOIN tree t ON r.parent_resource_id=t.id) SELECT id,project_id,item_id,note_id FROM tree`,[req.params.id]);await client.query('BEGIN');await client.query("DELETE FROM record_access_grants WHERE entity_type='resource' AND entity_id=ANY($1::uuid[])",[descendants.rows.map(row=>row.id)]);await client.query('DELETE FROM resources WHERE id=$1',[req.params.id]);for(const row of descendants.rows){await client.query("INSERT INTO sync_tombstones(entity_type,entity_id,project_id,item_id,note_id) VALUES('resource',$1,$2,$3,$4) ON CONFLICT(entity_type,entity_id) DO UPDATE SET deleted_at=now(),project_id=EXCLUDED.project_id,item_id=EXCLUDED.item_id,note_id=EXCLUDED.note_id",[row.id,access.context?.projectId||row.project_id||null,row.item_id||null,row.note_id||null]);}await client.query('COMMIT');await writeAuditLog({req,action:'DELETE',entityType:'resource',entityId:req.params.id,oldValue:resource});const dirToRemove=path.join(STORAGE_DIR,resource.parent_resource_id?resource.parent_resource_id:resource.id);if(!resource.parent_resource_id)await fsp.rm(dirToRemove,{recursive:true,force:true});else if(resource.storage_path)await fsp.rm(resolveStoragePath(resource.storage_path),{force:true});res.status(204).send();}catch(err){await client.query('ROLLBACK').catch(()=>{});console.error(err);res.status(500).json({error:err.message||'Failed to delete resource'});}finally{client.release();}});
export default router;
