import { Router } from 'express';
import { hasPermission, getUserPermissions } from '../middleware/permissions.js';
import { writeAuditLog } from '../middleware/audit.js';
import { requireProjectEditForTransaction, requireExistingTransactionProjectEdit, requireExistingTransactionProjectDelete } from '../middleware/project-transaction-boundary.js';
import { pool } from '../db.js';

const router = Router();

router.get('/', hasPermission('finance.view'), async (req, res) => {
  const permissions = await getUserPermissions(req.user.userId, req.user.role);
  const sensitive = permissions.has('finance.view_sensitive');
  const { type, direction, item_id, project_id, budget_period_id, from, to } = req.query;
  const conditions = sensitive ? [] : ["t.direction = 'expense'"], values = [];
  if (type) { values.push(type); conditions.push(`t.type = $${values.length}`); }
  if (direction) { values.push(direction); conditions.push(`t.direction = $${values.length}`); }
  if (item_id) { values.push(item_id); conditions.push(`t.item_id = $${values.length}`); }
  if (project_id) { values.push(project_id); conditions.push(`t.project_id = $${values.length}`); }
  if (budget_period_id) { values.push(budget_period_id); conditions.push(`t.budget_period_id = $${values.length}`); }
  if (from) { values.push(from); conditions.push(`t.date >= $${values.length}`); }
  if (to) { values.push(to); conditions.push(`t.date <= $${values.length}`); }
  const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : '';
  const fundingName = sensitive ? 'fs.name' : 'NULL';
  const budgetLabel = sensitive ? 'bp.label' : 'NULL';
  try { const result = await pool.query(`SELECT t.*, i.name AS item_name, p.name AS project_name, ${fundingName} AS funding_source_name, ${budgetLabel} AS budget_period_label FROM transactions t LEFT JOIN items i ON t.item_id = i.id LEFT JOIN projects p ON t.project_id = p.id LEFT JOIN funding_sources fs ON t.funding_source_id = fs.id LEFT JOIN budget_periods bp ON t.budget_period_id = bp.id ${where} ORDER BY date DESC, created_at DESC`, values); res.setHeader('Cache-Control','no-store'); res.json(sensitive ? result.rows : result.rows.map(({ funding_source_id, budget_period_id, funding_source_name, budget_period_label, ...expense }) => expense)); }
  catch (err) { console.error(err); res.status(500).json({ error: err.message || 'Failed to fetch transactions' }); }
});

router.get('/summary', hasPermission('finance.view'), async (req, res) => {
  const permissions = await getUserPermissions(req.user.userId, req.user.role);
  const sensitive = permissions.has('finance.view_sensitive');
  const { from, to, budget_period_id } = req.query; const conditions = sensitive ? [] : ["direction = 'expense'"], values = [];
  if (from) { values.push(from); conditions.push(`date >= $${values.length}`); } if (to) { values.push(to); conditions.push(`date <= $${values.length}`); } if (budget_period_id) { values.push(budget_period_id); conditions.push(`budget_period_id = $${values.length}`); }
  const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : '';
  try { const totals = await pool.query(`SELECT direction, SUM(amount)::float AS total FROM transactions ${where} GROUP BY direction`, values); const incomeTotal = totals.rows.find(r => r.direction === 'income')?.total || 0; const expenseTotal = totals.rows.find(r => r.direction === 'expense')?.total || 0; const byCategory = await pool.query(`SELECT direction, type, SUM(amount)::float AS total FROM transactions ${where} GROUP BY direction, type ORDER BY direction, total DESC`, values); const response = { totals: { income: sensitive ? incomeTotal : null, expense: expenseTotal, net: sensitive ? incomeTotal - expenseTotal : null }, by_category: { expense: byCategory.rows.filter(r => r.direction === 'expense').map(r => ({ type: r.type, total: r.total })), income: byCategory.rows.filter(r => r.direction === 'income').map(r => ({ type: r.type, total: r.total })) } }; response.by_month = (await pool.query(`SELECT to_char(date_trunc('month', date), 'YYYY-MM') AS month, direction, type, SUM(amount)::float AS total FROM transactions ${where} GROUP BY 1, direction, type ORDER BY 1 ASC`, values)).rows; if (sensitive && budget_period_id) { const budgetPeriod = await pool.query('SELECT id, label, total_budget, start_date, end_date FROM budget_periods WHERE id = $1', [budget_period_id]); if (budgetPeriod.rowCount) { const period = budgetPeriod.rows[0]; const spent = Number((await pool.query(`SELECT COALESCE(SUM(amount), 0)::float AS total FROM transactions WHERE budget_period_id = $1 AND direction = 'expense'`, [budget_period_id])).rows[0].total || 0); const totalBudget = Number(period.total_budget || 0); response.budget = { period_id: period.id, label: period.label, total_budget: totalBudget, spent, remaining: totalBudget - spent, start_date: period.start_date, end_date: period.end_date }; } } res.json(response); }
  catch (err) { console.error(err); res.status(500).json({ error: err.message || 'Failed to compute summary' }); }
});

const expenseTypes = ['purchase', 'repair', 'replacement', 'project_expense', 'other']; const incomeTypes = ['donation', 'investment', 'grant', 'lab_allocation', 'other_income']; const requiresFundingSource = ['donation', 'investment', 'grant'];

router.post('/', async (req, res, next) => { const { direction } = req.body; const requiredPermission = direction === 'income' ? 'finance.create_income' : direction === 'expense' ? 'finance.create_expense' : null; if (!requiredPermission) return res.status(400).json({ error: 'direction must be income or expense' }); return hasPermission(requiredPermission)(req, res, next); }, requireProjectEditForTransaction, async (req, res) => {
  const { type, direction, amount, date, vendor, notes, item_id, project_id, funding_source_id, budget_period_id } = req.body;
  if (!type || !direction || amount === undefined) return res.status(400).json({ error: 'type, direction, and amount are required' }); if (amount <= 0) return res.status(400).json({ error: 'amount must be greater than 0' });
  if (direction === 'expense' && !expenseTypes.includes(type)) return res.status(400).json({ error: `'${type}' is not a valid type for an expense transaction` }); if (direction === 'income' && !incomeTypes.includes(type)) return res.status(400).json({ error: `'${type}' is not a valid type for an income transaction` }); if (direction === 'income' && requiresFundingSource.includes(type) && !funding_source_id) return res.status(400).json({ error: `funding_source_id is required for type '${type}'` }); if (funding_source_id && !(await pool.query('SELECT id FROM funding_sources WHERE id = $1', [funding_source_id])).rowCount) return res.status(400).json({ error: 'funding_source_id references a non-existent funding source' }); if (direction === 'expense' && type === 'project_expense' && !project_id) return res.status(400).json({ error: 'project_id is required for project_expense transactions' });
  if (budget_period_id) { const period = await pool.query('SELECT id, start_date, end_date FROM budget_periods WHERE id = $1', [budget_period_id]); if (!period.rowCount) return res.status(400).json({ error: 'budget_period_id references a non-existent budget period' }); const txDate = date || new Date().toISOString().slice(0, 10), { start_date, end_date } = period.rows[0]; if (start_date && txDate < String(start_date).slice(0, 10)) return res.status(400).json({ error: 'transaction date is before the selected budget period' }); if (end_date && txDate > String(end_date).slice(0, 10)) return res.status(400).json({ error: 'transaction date is after the selected budget period' }); } else if (date) { const matching = await pool.query(`SELECT id FROM budget_periods WHERE (start_date IS NULL OR start_date <= $1::date) AND (end_date IS NULL OR end_date >= $1::date) ORDER BY start_date DESC NULLS LAST`, [date]); if (matching.rowCount === 1) req.body.budget_period_id = matching.rows[0].id; }
  try { const result = await pool.query(`INSERT INTO transactions (type, direction, amount, date, vendor, notes, item_id, project_id, logged_by, funding_source_id, budget_period_id) VALUES ($1,$2,$3,COALESCE($4, CURRENT_DATE),$5,$6,$7,$8,$9,$10,$11) RETURNING *`, [type, direction, amount, date ?? null, vendor ?? null, notes ?? null, item_id ?? null, project_id ?? null, req.user?.userId || null, funding_source_id ?? null, budget_period_id ?? req.body.budget_period_id ?? null]); await writeAuditLog({ req, action: 'CREATE', entityType: 'transaction', entityId: result.rows[0].id, newValue: result.rows[0] }); res.status(201).json(result.rows[0]); } catch (err) { console.error(err); res.status(500).json({ error: err.message || 'Failed to create transaction' }); }
});

router.put('/:id', hasPermission('finance.edit'), requireExistingTransactionProjectEdit, async (req, res) => {
  const fields = ['type', 'direction', 'amount', 'date', 'vendor', 'notes', 'item_id', 'project_id', 'funding_source_id', 'budget_period_id']; const updates = [], values = []; for (const field of fields) if (field in req.body) { values.push(req.body[field]); updates.push(`${field} = $${values.length}`); } if (!updates.length) return res.status(400).json({ error: 'No valid fields to update' });
  const current = await pool.query('SELECT * FROM transactions WHERE id=$1', [req.params.id]); if (!current.rowCount) return res.status(404).json({ error: 'Transaction not found' });
  if ('type' in req.body || 'direction' in req.body) { const currentType = req.body.type ?? current.rows[0].type, currentDirection = req.body.direction ?? current.rows[0].direction, currentFundingSourceId = req.body.funding_source_id !== undefined ? req.body.funding_source_id : current.rows[0].funding_source_id; if (currentDirection === 'expense' && !expenseTypes.includes(currentType)) return res.status(400).json({ error: `'${currentType}' is not a valid type for an expense transaction` }); if (currentDirection === 'income' && !incomeTypes.includes(currentType)) return res.status(400).json({ error: `'${currentType}' is not a valid type for an income transaction` }); if (currentDirection === 'income' && requiresFundingSource.includes(currentType) && !currentFundingSourceId) return res.status(400).json({ error: `funding_source_id is required for type '${currentType}'` }); }
  if ('funding_source_id' in req.body && req.body.funding_source_id && !(await pool.query('SELECT id FROM funding_sources WHERE id = $1', [req.body.funding_source_id])).rowCount) return res.status(400).json({ error: 'funding_source_id references a non-existent funding source' }); const effectiveDirection = req.body.direction ?? current.rows[0].direction, effectiveType = req.body.type ?? current.rows[0].type, effectiveProjectId = req.body.project_id ?? current.rows[0].project_id; if (effectiveDirection === 'expense' && effectiveType === 'project_expense' && !effectiveProjectId) return res.status(400).json({ error: 'project_id is required for project_expense transactions' });
  if (req.body.budget_period_id) { const period = await pool.query('SELECT start_date,end_date FROM budget_periods WHERE id=$1', [req.body.budget_period_id]); if (!period.rowCount) return res.status(400).json({ error: 'budget_period_id references a non-existent budget period' }); const txDate = req.body.date || current.rows[0].date; if (period.rows[0].start_date && txDate < String(period.rows[0].start_date).slice(0,10)) return res.status(400).json({ error: 'transaction date is before the selected budget period' }); if (period.rows[0].end_date && txDate > String(period.rows[0].end_date).slice(0,10)) return res.status(400).json({ error: 'transaction date is after the selected budget period' }); }
  values.push(req.params.id); try { const result = await pool.query(`UPDATE transactions SET ${updates.join(', ')} WHERE id = $${values.length} RETURNING *`, values); await writeAuditLog({ req, action: 'UPDATE', entityType: 'transaction', entityId: req.params.id, oldValue: current.rows[0], newValue: result.rows[0] }); res.json(result.rows[0]); } catch (err) { console.error(err); res.status(500).json({ error: err.message || 'Failed to update transaction' }); }
});

router.delete('/:id', hasPermission('finance.delete'), requireExistingTransactionProjectDelete, async (req, res) => { try { const result = await pool.query('DELETE FROM transactions WHERE id = $1 RETURNING *', [req.params.id]); if (!result.rowCount) return res.status(404).json({ error: 'Transaction not found' }); await writeAuditLog({ req, action: 'DELETE', entityType: 'transaction', entityId: req.params.id, oldValue: result.rows[0] }); res.status(204).send(); } catch (err) { console.error(err); res.status(500).json({ error: err.message || 'Failed to delete transaction' }); } });

export default router;